hmcts/ia-case-api

Jenkinsfile_nightly
build.gradle

Some mutation testing tweaks that were spotted during review for RIA-466
The mutation tests don't appear to be running as part of the build pipeline like originally thought, so I've added the tests to the nightly build as a safety net. A separate PR can be created to address the build pipeline step if necessary.
The success threshold was increased to a future-proof level, and one that should help ensure quality of tests are kept high.
- bumped the Pitest version
- upped the mutationThreshold to 90%
- added mutation tests to nightly build

RIA-466 mutation testing tweaks

---

Jenkinsfile_CNP

This changes adds the mutation tests to the build pipeline (they're already part of the overnight pipeline)
This means that PRs will fail when test coverage isn't up to scratch, rather than wait for the overnight tests to run. This should increase quality of the code being released.
(If in future the build pipeline starts taking too long to run, then at that point the decision can be taken about relying on the overnight tests)
Used `after('test') { ... }` to trigger the Pitest tool because the overnight `enableMutationTest()`command  did not work.

RIA-466 added mutation tests to build pipeline

---

.gitignore
Jenkinsfile_CNP
Jenkinsfile_parameterized
build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/WelcomeTest.java

This change adds Serenity reporting to the existing RestAssured tests.
Serenity creates a really clear test report as it's output, which should help pin-point failures (and hopefully their reasons).
Serenity was included as dependency for the project and incorporated in the functionalTest. The Jenkinsfiles were updated to publish the reports as part of the builds.

RIA-473 Add serenity

---

Jenkinsfile_CNP
Jenkinsfile_parameterized

Serenity reports were not being correctly archived by Jenkins, and so this change fixes that. 
Otherwise any failures that have been correctly reported by Jenkins would not be available for viewing without this change

[PREVIEW] RIA-473 make Jenkins archive serenity reports correctly

---

src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/EndpointSecurityTest.java
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/WelcomeTest.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/controllers/WelcomeController.java
src/main/resources/application.yaml

Primary goal is to stop the error logs filling up with Auth Errors when Azure pings the root endpoint.

Welcome endpoint re-enabled with JSON and no cache headers (for Zap)

---

build.gradle

Upgraded tomcat in response to CVE-2019-0232, CVE-2019-0199

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/PostSubmitCallbackDispatcher.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/PreSubmitCallbackDispatcher.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/PostSubmitCallbackDispatcherTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/PreSubmitCallbackDispatcherTest.java

[RIA-1539](https://tools.hmcts.net/jira/browse/RIA-1539)
pre-submit callback handlers are sorted based on dispatch priority and handler name (class name) value
Spring doesn't guarantee the same order of beans in injected list. There is a way to force Spring to use desired order.
[https://www.baeldung.com/spring-injecting-collections](https://www.baeldung.com/spring-injecting-collections) 5.1
I think the best way is sorting handlers in constructor than thinking about another annotation in handler bean component.
```
[ ] Yes
[x] No
```

RIA-1539 pre-submit and post-submit callback handlers ordering

---

zap-known-issues.xml

[RIA-1643](https://tools.hmcts.net/jira/browse/RIA-1643)
zap alerts
Some warnings are already ignored, but there is a new one too:
- A Client Error response code was returned by the server: Existing
https://ia-case-api-aat.service.core-compute-aat.internal/asylum/ccdSubmitted
https://ia-case-api-aat.service.core-compute-aat.internal/asylum/ccdAboutToSubmit
https://ia-case-api-aat.service.core-compute-aat.internal/asylum/ccdAboutToStart
We do not provide authentication to the ZAP worker so getting 403 status is ok. We do not perform testing for authenticated user.
- X-Content-Type-Options Header Missing: Existing
https://ia-case-api-aat.service.core-compute-aat.internal/v2/api-docs
https://ia-case-api-aat.service.core-compute-aat.internal/
ZAP report suggests to X-Content-Type-Options …

silent zap alerts related to server not application

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/CcdScenarioRunnerTest.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/field/JourneyType.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppellantNameForDisplayFormatter.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeReferenceNumberTruncator.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppellantNameForDisplayFormatterTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeReferenceNumberTruncatorTest.java

When we create a case for AIP there will be a few difference,
- We will create an AIP case using a citizen user
- The case may not have any data when it is created so we cannot
generate the display name and truncate the home office reference until
the appeal is submitted.
https://tools.hmcts.net/jira/browse/RIA-2162
```
[ ] Yes
[X] No
```

RIA-2162 Create AIP case

---

src/functionalTest/resources/scenarios/RIA-730-RIA-971-home-office-truncator.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeReferenceNumberTruncator.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeReferenceNumberTruncatorTest.java

Only truncate home office reference number when an appeal is submitted
not when it is edited or started. Then the aip or rep will see the
value they entered not the truncated version.
https://tools.hmcts.net/jira/browse/RIA-2191
```
[ ] Yes
[X] No
```

RIA-2191 Truncate the home office reference on appeal submitted

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RemoveAppealFromOnlineHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RemoveAppealFromOnlineHandlerTest.java

Fix for RIA-1500. 
[RIA-1500](https://tools.hmcts.net/jira/browse/RIA-1500)
_Record an application_ link removed from Applications tab for the **removeAppealFromOnline** event.
```
[ ] Yes
[x] No
```

RIA-1500 fix for record an application link

---

src/functionalTest/resources/scenarios/RIA-2493-reasons-for-appeal-repped.json
src/functionalTest/resources/scenarios/RIA-2493-reasons-for-appeal.json
src/functionalTest/resources/templates/minimal-aip-appeal-submitted.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/State.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/PreSubmitCallbackDispatcher.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/eventvalidation/AsylumCaseEventValidForJourneyTypeChecker.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/eventvalidation/EventValidForJourneyType.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/eventvalidation/EventValidForJourneyTypeChecker.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/StateTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/PreSubmitCallbackDispatcherTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/eventvalidation/AsylumCaseEventValidForJourneyTypeCheckerTest.java

As part of the aip flow we are adding new states and events. The TCW
could trigger those events so we want to prevent this by returning them
an error. Added a new handler that will check the journey type for
certain events and throw an exception to prevent any further handlers
firing. The exception is then handled and an error returned to CCD.
https://tools.hmcts.net/jira/browse/RIA-2493

RIA-2493 Prevent AIP events being triggered for Repped journey

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/eventvalidation/AsylumCaseEventValidForJourneyTypeChecker.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-2484
- Adds new events requestReasonsForAppeal and submitReasonsForAppeal to be forwarded into the notification service
- Adds editReasonsForAppeal event used in citizen AIP journeys
```
[ ] Yes
[ x] No
```

RIA-2484 - Reasons For Appeal

---

src/functionalTest/resources/scenarios/RIA-2558-change-hearing-centre.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ChangeHearingCentreConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ChangeHearingCentreHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DeriveHearingCentreHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ChangeHearingCentreConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ChangeHearingCentreHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DeriveHearingCentreHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-2558
- Added a pre submit handler for the `changeHearingCentre` event to change the `hearingCentre` in the case.
- Added a post submit handker for the `changeHearingCentre` event to display confirmation.
```
[ ] Yes
[x] No
```

RIA-2558: Change hearing centre

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/eventvalidation/AsylumCaseSendDirectionEventValidForJourneyTypeChecker.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/eventvalidation/AsylumCaseSendDirectionEventValidForJourneyTypeCheckerTest.java

We disabled all SEND_DIRECTION events for AIP cases. This enables them
if they are going to the respondent as they don't see any difference
between a repped and aip journey.

RIA-2773 Enable AIP directions to respondent

---

src/functionalTest/resources/scenarios/RIA-2513-remove-flag-confirmation.json
src/functionalTest/resources/scenarios/RIA-2513-remove-flag-preparer.json
src/functionalTest/resources/scenarios/RIA-2513-remove-flag.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/CaseFlagType.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/flagcase/RemoveFlagConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/flagcase/RemoveFlagHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/flagcase/RemoveFlagPreparer.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/CaseFlagTypeTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/flagcase/RemoveFlagConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/flagcase/RemoveFlagHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/flagcase/RemoveFlagPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/CaseFlagAppenderTest.java

https://tools.hmcts.net/jira/browse/RIA-2513
- A new handler created to handle the removing a flag event.
- A preparer created to collate the current flags in the case, to create a dynamic list of the flags.
- Functional tests added.
```
[ ] Yes
[x] No
```

RIA-2513: Removing flags

---

config/owasp/suppressions.xml
src/functionalTest/resources/scenarios/RIA-2829-PrepairTimeExtension.json
src/functionalTest/resources/scenarios/RIA-2829-ReviewTimeExtension.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/TimeExtensionHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/TimeExtensionAppender.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/TimeExtensionHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/TimeExtensionAppenderTest.java

https://tools.hmcts.net/jira/browse/RIA-2873
Enables `reviewTimeExtension` to be forwarded to the notifications service
Added time extension appender to handle time extensions on submission.
Added time extension handler
```
[ ] Yes
[ x] No
```

RIA-2873: time extension submission re-write

---

src/functionalTest/resources/scenarios/RIA-2829-ReviewTimeExtension-clarifying-questions.json
src/functionalTest/resources/scenarios/RIA-2829-ReviewTimeExtension-cma-requirements.json
src/functionalTest/resources/scenarios/RIA-2829-ReviewTimeExtension-reasons-for-appeal.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewTimeExtensionsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewTimeExtensionsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-2976
https://tools.hmcts.net/jira/browse/RIA-3153
https://tools.hmcts.net/jira/browse/RIA-3157
Extends the review time extension handler to work with any state defined on the stateToDirectionTag method.
Added functional tests and unit tests.
```
[ ] Yes
[x ] No
```

RIA-2976 & RIA-3153 & RIA-3157: Time Extensions for CMARequirements & Clarifying Questions

---

Jenkinsfile_CNP
Jenkinsfile_nightly
Jenkinsfile_parameterized
build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/CcdScenarioRunnerTest.java
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/util/AuthorizationHeadersProvider.java
src/functionalTest/resources/scenarios/RIA-3144-SetupAppellantDocuments.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ClarifyingQuestionAnswer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AddAppellantDocumentsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AddAppellantDocumentsHandlerTest.java

Create an appellantDocuments list to be displayed on the documents
tab. This will include any evidence the appellant has submitted about
their case. For the moment this includes the reasons for appeal evidence
and any clarify questions evidence.
https://tools.hmcts.net/jira/browse/RIA-3144

RIA-3144 Appellant documents on Documents tab

---

src/functionalTest/resources/scenarios/RIA-2957-adjourn-without-a-date.json
src/functionalTest/resources/scenarios/RIA-2960-restore-case-state.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AdjournWithoutDateHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListEditCaseHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RestoreStateFromAdjournHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AdjournWithoutDateHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListEditCaseHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RestoreStateFromAdjournHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-2960
- Created a new handler for restoreStateFromAdjourn event.
- Updated adjournHearingWithoutDate handler to keep previous state and listing date.
- Updated functional tests.
```
[ ] Yes
[ x] No
```

Ria 2960 Relist the case from adjourned state

---

build.gradle

[RIA-3370](https://tools.hmcts.net/jira/browse/RIA-3370)
jackson-core from 2.10.0.pr3 to 2.11.2
jackson-databind from 2.10.0.pr3 to 2.11.2
jackson-datatype-jsr310 from 2.10.0.pr2 to 2.11.2
```
[ ] Yes
[x] No
```

 jackson lib bumped from 2.10.0 to 2.11.2

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealReferenceNumberHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealReferenceNumberHandlerTest.java

[RIA-3583](https://tools.hmcts.net/jira/browse/RIA-3583)
Updated appealReferenceNumberHandler dispatch priority to earliest.
```
[ ] Yes
[x] No
```

RIA-3583 Updated the AppealReferenceNumberHandler dispatch priority to earliest

---

src/functionalTest/resources/scenarios/RIA-2935-EA-appeal-fee-pay-later-hearing.json
src/functionalTest/resources/scenarios/RIA-2935-EA-appeal-fee-pay-later-without-hearing.json
src/functionalTest/resources/scenarios/RIA-2935-EA-appeal-fee-pay-now-hearing.json
src/functionalTest/resources/scenarios/RIA-2935-EA-appeal-fee-pay-now-without-hearing.json
src/functionalTest/resources/scenarios/RIA-3025-successful-payment-for-pa-appeal-type-at-case-building.json
src/functionalTest/resources/scenarios/RIA-3025-successful-payment-for-pa-appeal-type-at-listing.json
src/functionalTest/resources/scenarios/RIA-3082-EA-failed-payment-account-deleted-pay-now-with-hearing.json
src/functionalTest/resources/scenarios/RIA-3082-EA-failed-payment-account-deleted-pay-now-without-hearing.json
src/functionalTest/resources/scenarios/RIA-3082-EA-failed-payment-account-on-hold-pay-now-with-hearing.json
src/functionalTest/resources/scenarios/RIA-3082-EA-successful-payment-pay-now-with-hearing.json
src/functionalTest/resources/scenarios/RIA-3082-EA-successful-payment-pay-now-without-hearing.json
src/functionalTest/resources/scenarios/RIA-3082-HU-failed-payment-account-on-hold-pay-now-with-hearing.json
src/functionalTest/resources/scenarios/RIA-3082-PA-failed-payment-account-deleted-pay-now-without-hearing.json
src/functionalTest/resources/scenarios/RIA-3163-PA-failed-payment-account-deleted-respondent-review-state.json
src/functionalTest/resources/scenarios/RIA-3163-PA-failed-payment-account-on-hold-listing-state.json
src/functionalTest/resources/scenarios/RIA-3163-PA-successful-payment-case-building-state.json.json
src/functionalTest/resources/scenarios/RIA-3468-pa-appeal-type-pay-now.json
src/functionalTest/resources/scenarios/RIA-3471-ea-appeal-type-pay-now-ou-of-time.json
src/functionalTest/resources/scenarios/RIA-3471-hu-appeal-type-pay-now-ou-of-time.json
src/functionalTest/resources/scenarios/RIA-3471-pa-appeal-type-pay-now-ou-of-time.json
src/functionalTest/resources/scenarios/RIA-3498-error-on-submit-when-option-is-payNow-for-HU.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SubmitAppealPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SubmitAppealPreparerTest.java

[RIA-3711](https://tools.hmcts.net/jira/browse/RIA-3711)
Issues fixed of the Payments AAT testing
1. Label name changed from 'Pending payment' to 'Payment pending'
2. Error on submitAppeal event if a saved draft appeal for EA/HU with PayNow option.
3. The overview tab text changed from 'Pay and submit your appeal' to 'Pay for and submit your appeal'
```
[ ] Yes
[x] No
```

RIA-3711 payments aat issue fixes

---

src/functionalTest/resources/scenarios/RIA-3683-list-case-start-flag-on.json
src/functionalTest/resources/scenarios/RIA-3683-list-reheard-case-start-flag-off.json
src/functionalTest/resources/scenarios/RIA-3683-list-reheard-case-start-flag-on.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListCasePreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListCasePreparerTest.java

Fix for issues discovered in AAT prior to release of reheard feature:
1. "Previous recordings" title no longer displays in the `Hearing and appointment` and `Documents` tab if none exist. 
2. "Hearing centre, hearing date and hearing length" fields are cleared at the start of the listing process for a reheard case.
[RIA-3683](https://tools.hmcts.net/jira/browse/RIA-3683)
[RIA-3784](https://tools.hmcts.net/jira/browse/RIA-3784)
See Jira
```
[ ] Yes
[x] No
```

RIA-3683-RIA-3784 fix - clear pre-populated fields

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/RemissionDetails.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/RemissionDetailsAppender.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/RemissionDetailsTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/RemissionDetailsAppenderTest.java

[RIA-3850](https://github.com/hmcts/ia-case-api/compare/RIA-3859)
Supporting classes for storing remission details as a collection
```
[ ] Yes
[x] No
```

RIA-3859 Remission details as collection

---

src/functionalTest/resources/scenarios/RIA-3634-customise-hearing-bundle-about-to-start.json
src/functionalTest/resources/scenarios/RIA-3634-customise-hearing-bundle.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CustomiseHearingBundlePreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CustomiseHearingBundlePreparerTest.java

https://tools.hmcts.net/jira/browse/RIA-3634
RIA-3634: Fix for customise hearing bundle to pre-populate the documents
```
[ ] Yes
[X] No
```

RIA-3634: Fix for customise hearing bundle to pre-populate the documents

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/FeeUpdateReason.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdateMidEvent.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/FeeUpdateReasonTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdateMidEventTest.java

[RIA-3793](https://tools.hmcts.net/jira/browse/RIA-3793)
Case-officer and Admin-officer manageFeeUpdate for the type Appeal not valid
```
[ ] Yes
[x] No
```

RIA-3793 Manage fee update for the type appeal not valid

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/BaseLocation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CaseManagementLocationService.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CaseManagementLocationServiceTest.java

https://tools.hmcts.net/jira/browse/RWA-497
fixes an issue where baselocation field was set as null when newcastle was selected
```
[ ] Yes
[x ] No
```

RWA-497: BaseLocation BugFix Newcastle

---

src/functionalTest/resources/scenarios/RIA-3555-RIA-3763-RIA-3784-submit-new-hearing-requirements.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DraftHearingRequirementsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DraftHearingRequirementsHandlerTest.java

[RIA-4369](https://tools.hmcts.net/jira/browse/RIA-4363)
appealOfOutCountry case-field is being initialised for older appeals.
As appealOutOfCountry case-field is missing for the older appeals causing submit-hearing-requirements to fail as it is a mandatory field in the event.
```
[ ] Yes
[x] No
```

RIA-4369 initialize appealOutOfCountry case-field for the older appeals

---

src/functionalTest/resources/scenarios/RIA-4546-edit-appeal-aip-errors.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AipEditAppealPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AipEditAppealPreparerTest.java

https://tools.hmcts.net/jira/browse/RIA-4546
Disabling and showing error message on edit appeal action for AIP appeals
```
[ ] Yes
[X] No
```

RIA-4546: Disabling and showing error message on edit appeal action for AIP appeals

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewDraftHearingRequirementsPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewDraftHearingRequirementsPreparerTest.java

[RIA-4833](https://tools.hmcts.net/jira/browse/RIA-4833)
Review hearing requirements event is broken for the older appeal before OOC, due to the incorrect permissions for the appealOutOfCountry casefield.
```
[ ] Yes
[x] No
```

RIA-4833 appealOutOfCountry field for old cases

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ServiceRequestHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ServiceRequestHandlerTest.java

[RIA-6109](https://tools.hmcts.net/jira/browse/RIA-6109)
- ServiceRequestHandler added to trigger creation of Service Request in ia-case-payments-api when event is SUBMIT_APPEAL
```
[ ] Yes
[x] No
```

Ria 6109 create service request when submitting appeal

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealSubmitHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ServiceRequestHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SubmitAppealPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/MarkPaymentPaidPreparer.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealSubmitHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ServiceRequestHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SubmitAppealPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/MarkPaymentPaidPreparerTest.java

- [RIA-6070](https://tools.hmcts.net/jira/browse/RIA-6070)
- Allow creation of Service Request from "generateServiceRequest" event
- Retain some old events to allow for in-flight cases
```
[ ] Yes
[x] No
```

Ria 6070 retain old events inflight cases

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HasServiceRequestAlreadyValueHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HasServiceRequestAlreadyValueHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-5725
- added handler to set value for hasServiceRequestAlready in aboutToStart stage
- value is set to 'no' when appeal is saved when there is no value set yet
```
[ ] Yes
[X] No
```

Ria-5725 qa fix notifications

---

build.gradle
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealSubmitHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordRemissionDecisionStateHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealSubmitHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordRemissionDecisionStateHandlerTest.java

[RIA-6169](https://tools.hmcts.net/jira/browse/RIA-6169)
- Added flag to be used to show 'markAppealPaid' and 'moveToSubmitted' events
- Added flag to be used to show/hide service-request tab
- Added logic for service-request to be generated when 'recordRemissionDecision' event results in REMISSION_REJECTED
```
[ ] Yes
[x] No
```

RIA-6169 service requests and remissions

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AutomaticEndAppealForNonPaymentEaHuTrigger.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AutomaticEndAppealForNonPaymentEaHuTriggerTest.java

https://tools.hmcts.net/jira/browse/RIA-6223
- Trigger handler to schedule endAppealAutomatically event on the Submit Appeal event for EA and HU cases
- application.yaml value set to 14 days (20160 mins)
- Unit tests
```
[ ] Yes
[X] No
```

Ria-6223 ea hu end appeal automatically

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordOutOfTimeDecisionPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordOutOfTimeDecisionPreparerTest.java

[RIA-6269 (Scenario 4)](https://tools.hmcts.net/jira/browse/RIA-6269)
- When starting event "recordOutOfTimeDecision", if the value of "paAppealTypePaymentOption" of an old case is `payOffline` it'll throw an error because that FixedRadioList now only allows "payNow" and "payLater" (no more ~`payOffline`~). Any `payOffline` value gets translated to `payLater` in the ABOUT_TO_START handler of the event, so it doesn't throw any error about case data validation.
```
[ ] Yes
[x] No
```

RIA-6269 Conform paAppealTypePaymentOption "payOffline" to "payLater"

---

build.gradle
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordRemissionDecisionStateHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/PayOfflineMigrationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordRemissionDecisionStateHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/PayOfflineMigrationHandlerTest.java

[RIA-6229](https://tools.hmcts.net/jira/browse/RIA-6229) and others
- Added PayOfflineMigrationHandler to conform any `payOffline` value of "paAppealTypePaymentOption" to `payLater` (the new fee&pay integration only allows "payNow" and "payLater" values, so any old in-flight case with "payOffline" values would make the triggering of an event fail, since that value no longer exists in the fixedList)
```
[ ] Yes
[x] No
```

RIA-6229 Add PayOfflineMigrationHandler

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordRemissionDecisionStateHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordRemissionDecisionStateHandlerTest.java

[https://tools.hmcts.net/jira/browse/RIA-6229](https://tools.hmcts.net/jira/browse/RIA-6229)
- Made the `recordRemissionDecision` event write `paymentStatus` with "Pending payment" when decision is "approved" or "partiallyApproved" only if not present (leave as is if there's a value already)
This is so that when a remission is requested after a payment has been taken, if the remission is rejected, `paymentStatus` doesn't go back to "Pending payment"
```
[ ] Yes
[x] No
```

RIA-6229 RecordRemissionDecision to populate paymentStatus if empty

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/PostSubmitCallbackHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestFeeRemissionHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestFeeRemissionHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-6290
- New flag 'requestFeeRemissionFlagForServiceRequest' which is only set to 'Yes' when a LR triggers the 'requestFeeRemission' event after submitting the case, which allows us to stop anymore service requests being generated for all case types.
```
[ ] Yes
[X] No
```

RIA-6290 New flag as condition for service request generation

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EditAppealAfterSubmitHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HearingTypeHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HearingTypeHandlerTest.java

JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/RIA-6418
Change description
This story cover the scenario where a LR appeals for a client who is in detention.
Existing screens to be removed if detained
Your client's address
The appellant's contact preference
New screens if detained
Is your client in detention?
Where is your client detained?
In which IRC is your client detained? (needs lookup functionality)
In which prison is your client detained? (needs lookup functionality)
Is your client still serving their custodial sentence?
Does your client have a pending bail application?
Is this an ADA?
Removal directions
Existing screens with changes if detained
Home Office details (only changes if ADA)
Change question about letter to: What date was the Home Office decision letter …

Ria 6148 detained appeal part 3

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/CustodialSentenceDate.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/callback/Callback.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CustodialDateValidator.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EditAppealAfterSubmitHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/StartAppealMidEvent.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/PreSubmitCallbackDispatcher.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/controllers/PreSubmitCallbackController.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/CustodialSentenceDateTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CustodialDateValidatorTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EditAppealAfterSubmitHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/StartAppealMidEventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/controllers/PreSubmitCallbackControllerTest.java

[RIA-6459](https://tools.hmcts.net/jira/browse/RIA-6459)
- Added `pageId` parameter to `/ccdMidEvent` endpoint to allow for multiple midEvent calls from the same event, which necessary in `startAppeal` as part of this ticket (doesn't break other pre-existing calls because the parameter is optional and they'll keep working as before)
- Added validator for `custodialDate` to check it's a future date if present
- Did not make the field in Scenario 5 optional because it's being developed in another ticket and wasn't ready when opening this PR (it's a very small change in ia-ccd-definitions)
```
[ ] Yes
[x] No
```

RIA-6459 Custodial date validator and midEvent endpoint parameter

---

src/functionalTest/resources/scenarios/RIA-3680-home-office-reference-mid-event.json
src/functionalTest/resources/scenarios/RIA-3680-home-office-reference-mid-event_edit_appeal.json
src/functionalTest/resources/scenarios/RIA-515-lodge-appeal-confirmation.json

- RIA-515* failed after WA R2 merge; added a LD flag to exclude WA R3 feature while running this test.
- RIA-3680* - failed due to change in EditAppealAfterSubmit handler. It was changed to be triggered only at MidEvent with pageId & about_to_submit in Edit_Appeal_After_Submit. It no longer sets the field Submission_out_of_time as Yes/No at Start/Edit Appeal. This scenario is already covered in RIA-369.

RIA-6547: Enabled the functional tests

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LetterSentOrReceivedHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LetterSentOrReceivedHandlerTest.java

[RIA-6550](https://tools.hmcts.net/jira/browse/RIA-6550)
- Made LetterSentOrReceivedHandler conditional to journey type being non-AIP (not needed and is problematic for AIP journey)
```
[ ] Yes
[x] No
```

RIA-6550 letter sent or received handler non aip

---

src/functionalTest/resources/scenarios/RIA-6437-add-stateless-age-assessment-start-appeal.json
src/functionalTest/resources/scenarios/RIA-6437-add-stateless-age-assessment-submit-appeal-in-time.json
src/functionalTest/resources/templates/minimal-age-assessment-appeal-started.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/HandlerUtils.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HearingTypeHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeDecisionDateChecker.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeReferenceNumberTruncator.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LetterSentOrReceivedHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/HandlerUtilsTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HearingTypeHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeDecisionDateCheckerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeReferenceNumberTruncatorTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LetterSentOrReceivedHandlerTest.java

- Updated handlers to skip checks if it is a AAA case: HomeOfficeReferenceNumberTruncator, LetterSentOrReceivedHandlerTest,
- if AAA, check dateOnDecisionLetter and write if submission out of time or not.
- Added a helper method in HandlerUtils, to check if appeal type is AG.
- Added functional test to check start and submit AG appeal.
```
[ ] Yes
[x] No
```

RIA-6437: Save & submit Age Assessment appeal - part 3

---

src/functionalTest/resources/scenarios/RIA-6526-list-case-ada-start.json
src/functionalTest/resources/scenarios/RIA-6526-request-respondent-evidence-ada-start.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListEditCaseHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestRespondentEvidenceHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListEditCaseHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestRespondentEvidenceHandlerTest.java

[RIA-6526](https://tools.hmcts.net/jira/browse/RIA-6526)
- Added `CALCULATED_HEARING_DATE` flag and calculations to elaborate it
- Added `LISTING_AVAILABLE_FOR_ADA` flag that ccd will need to use to display the listCase event in `awaitingRespondentEvidence` (set in the event that results in that state, i.e. `REQUEST_RESPONDENT_EVIDENCE`)
```
[ ] Yes
[x] No
```

RIA-6526 Set flags for listCase for accelerated detained appeals

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListEditCaseHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListEditCaseHandlerTest.java

[RIA-6528](https://tools.hmcts.net/jira/browse/RIA-6528)
- Set new flag ACCELERATED_DETAINED_APPEAL_LISTED to Yes when an ADA case gets listed. The flag is then used in CCD to show the Hearing & Appointment tab on the UI. Another flag was normally used (SUBMIT_HEARING_REQUIREMENTS_AVAILABLE) but this is also used for other things, so it may unlock stuff that shouldn't be unlocked at this stage for an ADA case
```
[ ] Yes
[x] No
```

RIA-6528 Hearing&Appointment tab for ADA

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MakeAnApplicationMidEvent.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/MakeAnApplicationTypesProvider.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/MakeAnApplicationTypesProviderTest.java

[RIA-6501](https://tools.hmcts.net/jira/browse/RIA-6501)
- New application types now restricted to users with LR role
- `makeAnApplicationDetailsLabel` now showing for `JUDGE_REVIEW_LR` application type just like `JUDGE_REVIEW`
```
[ ] Yes
[x] No
```

RIA-6501 Make new application types exclusive to LR role

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AppealTypeForDisplay.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/FeesHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AppealTypeForDisplayTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeesHandlerTest.java

- For all ADA types, move the appeal to appealSubmitted irrespective of appealType (treat them as RP/DC).
- For Detained (Non-ADA) move the appeal to paymentPending for HU/EA/EUSS
- For PA, move appeal to submitted with paymentStatus = paymentPending.
(https://tools.hmcts.net/jira/browse/RIA-6563)
```
[ ] Yes
[x] No
```

RIA-6563: Fix the state for appeal after submit

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DirectionTag.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListEditCaseHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/DirectionPartiesResolver.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DirectionTagTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListEditCaseHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/DirectionPartiesResolverTest.java

[RIA-6533](https://tools.hmcts.net/jira/browse/RIA-6533)
A direction has to be created when an admin lists an ADA case (in `awaitingRespondentEvidence` state) and a notification with the same content has to be sent to the LR.
- Changed ListEditCaseHandler to manage flags for Accelerated Detained Appeal and add a direction.
```
[ ] Yes
[x] No
```

RIA-6533 List ADA Case direction

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AutomaticEndAppealForNonPaymentEaHuTrigger.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AutomaticEndAppealForNonPaymentEaHuTriggerTest.java

[RIA-6594](https://tools.hmcts.net/jira/browse/RIA-6594)
[RIA-6572](https://tools.hmcts.net/jira/browse/RIA-6572)
- AIP appeals don't have the `remissionType` field set, so originally the handler wouldn't be called (condition exiting at L54 [AutomaticEndAppealForNonPaymentEaHuTrigger.java](https://github.com/hmcts/ia-case-api/compare/ia-case-api-aip-payment...RIA-6594_RIA-6572_end_aip_appeals_automatically?expand=1#diff-3e8f7b7a43aa24ca1ac6c9db4c76908919575f827b75e23fe697b6597ab1f4ec))
- AIP appeals can now use the handler to set the 14 days timer to trigger `endAppeal` since the condition treats an empty `remissionType` as `noRemission`. This shouldn't accidentally allow other appeal types to use the handler, since the following condition filters out any appeal that isn't HU, EA, EU.
| …

RIA-6594 RIA-6572 Allow appeals with empty remissions to be ended

---

config/owasp/suppressions.xml
src/functionalTest/resources/templates/minimal-age-assessment-appeal-started.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DeriveHearingCentreHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DerivePostcodeHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DeriveHearingCentreHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DerivePostcodeHandlerTest.java

- Since the order of the screens (For Appellant details) is same, we will use the same fields for the non-AAA and AAA flows.
- Updated handlers, tests and functionalTestTemplate.
```
[ ] Yes
[x] No
```

RIA-6508: Remove AA* fields from the asylumCaseDefinitions

---

src/functionalTest/resources/scenarios/RIA-6604-ada-suitability-confirmation-suitable.json
src/functionalTest/resources/scenarios/RIA-6604-ada-suitability-confirmation-unsuitable.json
src/functionalTest/resources/scenarios/RIA-6604-ada-suitability-retrigger-errors.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AdaSuitabilityReviewDecision.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AdaSuitabilityReviewConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AdaSuitabilityReviewPreparer.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AdaSuitabilityReviewConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AdaSuitabilityReviewPreparerTest.java

- New event and related fields.
- Preparer to add error when Judges try to re-trigger the event in respondentReview state.
- Confirmation handler to add header and body depending on decision.
- Functional tests and unit tests.
<html>
<body>
<p>Testing notes</p>
<div class="table-wrap">
Appeal Type | ADASuitability Event available after Upload Appeal Response | Decision | PostState | Event available post decision | Error message on re-trigger
-- | -- | -- | -- | -- | --
Detained - ADA (DC) | Yes | Suitable | prepareForHearing | No | Not applicable
Detained - ADA (DC) | Yes | Unsuitable | respondentReview | Yes | Yes
Detained - nonADA (AG) | No | Not applicable | Not applicable | Not applicable | Not applicable
Non-Detained - nonAAA (DC) | No | Not applicable | Not applicable | Not …

RIA-6604: Added handlers for Ada suitability review event

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/CancelAutomaticEndAppealPaidConfirmation.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/CancelAutomaticEndAppealPaidConfirmationTest.java

[RIA-6572](https://tools.hmcts.net/jira/browse/RIA-6572)
- An AIP payment doesn't seem to use the `updatePaymentStatus` event to update the payment status, but it's resolved within the `paymentAppeal` event, which needs to be the qualifying event for the AIP journey for the CancelAutomaticEndAppealPaidConfirmation handler to update the trigger schedule to 100 years
Example below:
- 15:03:35: case 1674572435640710 is submitted, `endAppealAutomatically` event scheduled for 2 minutes later (15:05:35)
- 15:03:58: case 1674572435640710 gets paid, `endAppealAutomatically` event re-scheduled for ~100 years later (15:05:35)
- nothing gets logged on ia-case-api between 15:03 and 15:06, when the `endAppealAutomatically` event was first supposed to be triggered (but wasn't, because of it being …

RIA-6572 Wire AIP into the cancelling of automatic end of appeal

---

src/functionalTest/resources/scenarios/RIA-6586-transfer-out-of-ada-in-appeal-submitted-state.json
src/functionalTest/resources/scenarios/RIA-6604-ada-suitability-confirmation-unsuitable.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AdaSuitabilityReviewConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/TransferOutOfAdaConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/TransferOutOfAdaHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AdaSuitabilityReviewConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/TransferOutOfAdaConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/TransferOutOfAdaHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-6586
- Updated link to event in adaSuitability confirmation screen
- Added functional test for moving out of ADA in appeal submitted state, edited adaSuitability Unsuitable functional test with new confirmation link to event
- New confirmation screen after completing 'transferOutOfAda' event
- Handler to update caseData values and flag
- TCW and Judge authorisation to the event in application.yaml
- New and updated unit tests
```
[ ] Yes
[X] No
```

RIA-6586 Transfer out of ada event

---

src/functionalTest/resources/scenarios/RIA-6585-mark-appeal-as-ada-in-appeal-submitted-state-admin.json
src/functionalTest/resources/scenarios/RIA-6585-mark-appeal-as-ada-in-appeal-submitted-state-tcw.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/HandlerUtils.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/MarkAppealAsAdaConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MarkAppealAsAdaHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ProgressBarAdaSuffixAppender.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/MarkAppealAsAdaConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MarkAppealAsAdaHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-6585
* Include the new event 'markAppealAsAda' in the events enum
* Give relevant roles access to the event
* Create a pre-submit callback handler to mark appeal as ADA
* Create a post-submit callback handler to set the successful event confirmation message
* Some refactorings
* Functional/unit tests
```
[ ] Yes
[x] No
```

RIA-6585: Mark appeal as ADA event

---

src/functionalTest/resources/scenarios/RIA-6733-mark-hu-appeal-as-paid-admin-officer.json
src/functionalTest/resources/scenarios/RIA-6733-mark-pa-appeal-as-paid-case-officer.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/HandlerUtils.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/MarkPaymentPaidPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/HandlerUtilsTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/MarkPaymentPaidPreparerTest.java

https://tools.hmcts.net/jira/browse/RIA-6733
* Some refactoring to clean up code and make it readable
* Allow all internal detained cases ('isAdmin'= true and 'appellantInDetention'=true) in 'paymentPending' state to be marked as paid both by Admins and Caseworkers
* For non-internal cases, only Admins are allowed to 'mark appeal as paid' Caseworkers are not allowed
* Unit/Functional tests.
```
[ ] Yes
[x] No
```

RIA-6733: Make 'Mark appeal as paid' event available for internal cases

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/HandlerUtils.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DraftHearingRequirementsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListCasePreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ProgressBarAdaSuffixAppender.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewDraftHearingRequirementsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/TransferOutOfAdaHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DraftHearingRequirementsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListCasePreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ProgressBarAdaSuffixAppenderTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewDraftHearingRequirementsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/TransferOutOfAdaHandlerTest.java

[RIA-6662](https://tools.hmcts.net/jira/browse/RIA-6662)
- Six flag fields from the ADA journey reset to `NO`
- `adaSuffix` gets set to `"_ada"` when case is ADA and set to `""` when case transfers out of ADA
The below are changes to the logic I've made to allow myself to progress the case, but I have no acceptance criteria to go by:
- Added UI error to prevent user from triggering `LIST_CASE` after the case has been listed (redirecting the user to use `EDIT_CASE_LISTING` instead
- Added logic to enable `EDIT_CASE_LISTING` after CW review of hearing requirements when transferred out of ADA
- Added flag suffix to show a different progress bar when the case transferred out of ADA but has submitted hearing requirements already
**Does this PR introduce a breaking change?** (check one with …

RIA-6662 Changes necessary for progress bar conversion to non-ADA

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealUserRoleAppender.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealUserRoleAppenderTest.java

https://tools.hmcts.net/jira/browse/RIA-6735
RIA-6735 - 
* Disabling internal case creation Submit appeal notifications
* Updating isAdmin flag to also be called on about to submit for startAppeal as it was not setting for LR journey cases.
```
[ ] Yes
[x] No
```

RIA-6735 -

---

charts/ia-case-api/Chart.yaml
config/owasp/suppressions.xml
src/functionalTest/resources/scenarios/RIA-6856-application-types-available-ada-internal-case-after-hearing-req.json
src/functionalTest/resources/scenarios/RIA-6856-application-types-available-ada-internal-case-before-hearing-req.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/MakeAnApplicationTypesProvider.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/MakeAnApplicationTypesProviderTest.java

[RIA-6856](https://tools.hmcts.net/jira/browse/RIA-6856)
- `Transfer` should not be available. It's only available for non ADA cases from the 'prepareForHearing' state onwards
- `Adjourn` and `Expedite` are available for internal ADA cases in the 'awaitingRespondentEvidence' state, and continue to be available for non-ADA cases after listing
- `Update hearing requirements` is available after 'submitHearingRequirements' is done
There's quite a bit of code repetition in this PR because I didn't feel like deviating too much from the grid that the `switch` block sets up, so it's easily understandable what each state is supposed to incorporate. I guess I could make it drier but it'd deform the straightforward approach of the `switch` block.
**Does this PR introduce a breaking change?** (check …

RIA-6856 makeAnApplicationTypes available for some internal ada cases

---

charts/ia-case-api/Chart.yaml
infrastructure/state.tf
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/util/MapValueExpander.java
src/functionalTest/resources/scenarios/RIA-1293-ftpa-appellant-out-of-time-flag-on-submit.json
src/functionalTest/resources/scenarios/RIA-2581-ftpa-respondent-in-time-homeoffice-generic-submit.json
src/functionalTest/resources/scenarios/RIA-2581-ftpa-respondent-out-of-time-flag-set-homeoffice-generic.json
src/functionalTest/resources/scenarios/RIA-2581-ftpa-respondent-out-of-time-flag-set-homeoffice-pou.json
src/functionalTest/resources/scenarios/RIA-3132-ftpa-reheard-appellant-flag-on.json
src/functionalTest/resources/scenarios/RIA-3132-ftpa-reheard-respondent-flag-on.json
src/functionalTest/resources/scenarios/RIA-3954-ftpa-appellant-in-time-flag-off-submit-ooc.json
src/functionalTest/resources/scenarios/RIA-3954-ftpa-appellant-out-of-time-flag-on-submit-ooc.json
src/functionalTest/resources/scenarios/RIA-3954-ftpa-respondent-in-time-flag-set-homeoffice-generic-ooc.json
src/functionalTest/resources/scenarios/RIA-3954-ftpa-respondent-out-of-time-flag-set-homeoffice-generic-ooc.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaAppellantPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaRespondentPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaAppellantPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaRespondentPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandlerTest.java

[RIA-6647](https://tools.hmcts.net/jira/browse/RIA-6647)
- Migrated `ftpaApplicationDeadline` (Date field) to `ftpaApplicationDeadlineDate` (String field) in order to format the date in full (15 March 2023). A Date field will always show as 15 Mar 2023 on the frontend, DATETIMEDISPLAY does not work in ccd.
- Changed functional tests and added the functionality of passing a String date in full dynamically to the tests. Just like `${TODAY}` will evaluate to `"2023-03-15"`, `${TODAY_FULL_DATE}` will evaluate to `"15 March 2023"`
```
[ ] Yes
[X] No
```

RIA-6647 change date field to string

---

charts/ia-case-api/Chart.yaml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AutomaticDirectionRequestingHearingRequirementsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DirectionHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewAmendDirectionHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewDraftHearingRequirementsPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AutomaticDirectionRequestingHearingRequirementsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DirectionHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewAmendDirectionHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewDraftHearingRequirementsPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

[RIA-6586](https://tools.hmcts.net/jira/browse/RIA-6586)
- if case transferred out of ADA with hearing requirements submitted:
- Made direction be skipped during `Request Home Office Response`
- Made simultaneous notification be skipped as well, since it referenced details produced inside the (now absent) direction
- Made `Review Hearing Requirement` throw a UI error if triggered (reutilizing the same UI error currently being thrown if the user tries to trigger the event twice)
- Made `Edit Case Listing` be enabled during `Request Home Office Response` (last step before going to 'listing'), but kept the enabling step in `Review Hearing Requirements` as well, since _that_ is going to be the last step before going to 'listing' for ex ADA cases that had not submitted hearing requirements
- …

RIA-6586 Transfer out of ADA loose ends

---

config/owasp/suppressions.xml
src/functionalTest/resources/scenarios/RIA-6906-mark-appeal-as-detained.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/PrisonNomsNumber.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/MarkAppealAsDetainedConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/BailApplicationNumberHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CustodialDateValidator.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DetentionStatusHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MarkAppealAsDetainedHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinitionTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/MarkAppealAsDetainedConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/BailApplicationNumberHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CustodialDateValidatorTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DetentionStatusHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MarkAppealAsDetainedHandlerTest.java

[RIA-6906](https://tools.hmcts.net/jira/browse/RIA-6906)
- added `PrisonNomsNumber` entity which didn't use to exist
- new event **markAppealAsDetained** with handler which maps `prisonNomsNumberAo` and `dateCustodialSentenceAo` to `prisonNomsNumber` and `dateCustodialSentence` before the end of the event
- made `DetentionStatusHandler` set detention status to "detained" when the event is `markAppealAsDetained`
- made `BailApplicationNumberHandler` and `CustodialDateValidator` use validation during the new event too
- made valid
```
[ ] Yes
[x] No
```

Ria 6906 mark appeal as detained

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CustodialDateValidator.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CustodialDateValidatorTest.java

https://tools.hmcts.net/jira/browse/RIA-6990
Return as soon as client in custody == no
Return as soon as date is null (optional field)
Changed how dateCustodialSentence and dateCustodialSentenceAo are extracted/parsed.
```
[ ] Yes
[X] No
```

RIA-6990 Fix CustodialDateValidator

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/TransferOutOfAdaConfirmation.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/TransferOutOfAdaConfirmationTest.java

https://tools.hmcts.net/jira/browse/RIA-6586
- Adding missing 'the' in confirmation content
```
[ ] Yes
[X] No
```

RIA-6586 Fixing typo in confirmation text

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSavedConfirmation.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSavedConfirmationTest.java

https://tools.hmcts.net/jira/browse/RIA-7003
- Adding new content for Unrrepped/Internal/Admin-created cases confirmation screen for startAppeal event and logic to show correct version for both LR and Admin
- Added new unit test 
```
[ ] Yes
[X] No
```

RIA-7003 unrep start appeal confirmation content change

---

bin/variables/load-preview-environment-variables.sh
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SetCaseAsUnrepresentedHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SetCaseAsUnrepresentedHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7029
- Created a new handler when triggerent event 'removeRepresentation - Stop representing a client" to set isAdmin to true to see the overview tab AIP - manual flag and events.
- Clear out the old LR info from the case data
```
[ ] Yes
[X] No
```

RIA-7029 Handler to set isAdmin to Yes when stop representing a client

---

src/integrationTest/java/uk/gov/hmcts/reform/iacaseapi/component/testutils/fixtures/CaseDetailsForTest.java
src/integrationTest/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/UserDetailsRequestScopeTest.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AsylumSupplementaryDataFixingHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AsylumSupplementaryDataFixingHandlerTest.java

[RIA-7052](https://tools.hmcts.net/jira/browse/RIA-7052)
([RIA-6516](https://tools.hmcts.net/jira/browse/RIA-6516))
- With supplementary data being set from the AIP frontend, the setting of supplementary data from the backend can be muted when the case is AIP and the user is `"citizen"` (avoiding a 400 exception)
- changed integration test to verify that idamApi is now called two times instead of one (since a new call is being made to verify the user's role when choosing to skip the setting of supplementary data)
```
[ ] Yes
[x] No
```

RIA-7052 Skip BE handling of supplementary data if citizen in AIP journey

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AsylumSupplementaryDataFixingHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AsylumSupplementaryDataFixingHandlerTest.java

[RIA-7052](https://tools.hmcts.net/jira/browse/RIA-7052)
- Skipped supplementary data setting when `START_APPEAL` as a Citizen user, as in that scenario supplementary data are set from the FE, and in other events the data-setting will be skipped because data won't be null anymore
```
[ ] Yes
[x] No
```

RIA-7052 Skip supplementary data setting form BE if startAppeal + citizen

---

src/functionalTest/resources/scenarios/RIA-7105-case-officer-sends-non-standard-direction-to-appellant-aip.json
src/functionalTest/resources/scenarios/RIA-7105-case-officer-sends-non-standard-direction-to-respondent-aip.json
src/functionalTest/resources/scenarios/RIA-7105-judge-sends-non-standard-direction-to-appellant-aip.json
src/functionalTest/resources/scenarios/RIA-7105-judge-sends-non-standard-direction-to-respondent-aip.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/eventvalidation/AsylumCaseSendDirectionEventValidForJourneyTypeChecker.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/eventvalidation/AsylumCaseSendDirectionEventValidForJourneyTypeCheckerTest.java

https://tools.hmcts.net/jira/browse/RIA-7105
* Enable Non Standard Directions to the Appellant for AIP appeals
```
[ ] Yes
[x] No
```

RIA-7105: Enable Non Standard Directions to the Appellant

---

charts/ia-case-api/Chart.yaml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

[RIA-7044](https://tools.hmcts.net/jira/browse/RIA-7044)
- Adding the Mark as ready for transfer to UT event to the send notification handler
```
[ ] Yes
[X] No
```

RIA-7044 Mark as ready transfer to UR event to notification handler

---

charts/ia-case-api/Chart.yaml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MarkAsReadyForUtTransferHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MarkAsReadyForUtTransferHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7046
- Recording state before transferring to UT so when reinstated it is put back in same state as before
- Clearing reinstate fields to mirror End Appeal process
```
[ ] Yes
[X] No
```

RIA-7046 Reinstate appeal changes after Transfer to UT

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReinstateAppealStateHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReinstateAppealStateHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7030
Updated value of decision maker role for reinstate appeal from "Tribunal Caseworker" to "Legal Officer", when the decisionMaker is TCW.
```
[ ] Yes
[X] No
```

RIA-7030 Update reinstateAppeal decisionMaker from TCW to LO

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewDraftHearingRequirementsPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewDraftHearingRequirementsPreparerTest.java

https://tools.hmcts.net/jira/browse/RIA-7116
-Added the default length for hearing according to the different appeal type
-Added the unit test of setting default length in different appeal type
```
[ ] Yes
[X] No
```

RIA-7116 Set appeal type length by default for hearing requirements

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReinstateAppealStateHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReinstateAppealStateHandlerTest.java

* Cleared appealReadyForUtTransfer field so that UI content on ended state is accurate when appeal not ended through markAsReadyForUtTransfer event
* Added test case for clearing the field
* Cleared appealReadyForUtTransfer field so that UI content on ended state is accurate when appeal not ended through markAsReadyForUtTransfer event
* Added test case for clearing the field
```
[ ] Yes
[X] No
```

RIA-7397 markAsReadyForUtTransfer -> reinstateAppeal -> endAppeal incorrect content

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EndAppealHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReinstateAppealStateHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EndAppealHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReinstateAppealStateHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7397
*Moved the clearing of UtAppealReferenceNumber from ReinstateAppealStateHandler to EndAppealHandler
```
[ ] Yes
[ ] No
```

RIA-7397 moving clearing of UtAppealReferenceNumber to end appeal handler

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListCaseWithoutHearingRequirementsPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListCaseWithoutHearingRequirementsPreparerTest.java

https://tools.hmcts.net/jira/browse/RIA-7220
-Added the ListCaseWithoutHearingRequirementsPreparer for listCaseWithoutHearingRequirements event
-Added the unit test for ListCaseWithoutHearingRequirementsPreparer
-Set the default appeal type length as ticket mention
```
[ ] Yes
[X] No
```

RIA-7220 set appeal type length by default for list without req

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeDecisionDateChecker.java

https://tools.hmcts.net/jira/browse/RIA-7239
When appeal is changed from in-country (ADA) to OOC, the in-country fields such as isADA can remain. An extra check has been inserted to ensure the appeal is not treated as ADA if OOC decision type is present. If it is present, we know the appeal was moved from in-country to OOC.
Tested and was able to move from ADA to OOC and save/submit appeal successfully. 
```
[ ] Yes
[X] No
```

RIA-7239 Add OOC decision type check when handling ADA appeals

---

config/checkstyle/checkstyle.xml
config/owasp/suppressions.xml

RIA-7385
Different IDEs apply different formatting by default. Some of the rules in the checkstyle currently get in the way, without any meaningful benefit. Best to remove them.
```
[ ] Yes
[x] No
```

RIA-7385 Remove pendantic checkstyle rules

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java

* Reverting adding async event to send notif handler as this is done manually in advanced bundling handler
```
[ ] Yes
[ ] No
```

RIA-7199 revert async in send notif handler

---

charts/ia-case-api/values.preview.template.yaml
src/functionalTest/resources/scenarios/RIA-7509-submit-hearing-requirements-with-witness-interpreters.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DynamicMultiSelectList.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/InterpreterLanguagesDynamicListUpdater.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/WitnessesMidEventHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/InterpreterLanguagesDynamicListUpdaterTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/WitnessesMidEventHandlerTest.java

[RIA-7509](https://tools.hmcts.net/jira/browse/RIA-7509)
**📊📈📉 [DIAGRAM on CONFLUENCE](https://tools.hmcts.net/confluence/display/~Marcello.Fabbri/Interpreter+Language+refactor+for+witnesses)**
Added logic to: 
- extrapolate the witnesses from the collection (`witnessDetails`) into the individual fields (`witness1`, witness2`...)
- fill the witness list elements according to the individual witnesses (`witness1` -> `witnessListElement`1 ...)
- read the selected type of interpreter (spoken/sign) each witness requires (`witness1InterpreterLanguageCategory `, `witness2InterpreterLanguageCategory`...) and fill the dynamic lists inside the InterpreterLanguageRefData complex type of each subsequent page accordingly (`witness1InterpreterSpokenLanguage`, `witness2InterpreterSpokenLanguage`...)
| …

RIA-7509 witness interpreters

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/WitnessDetails.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CreateFlagHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewDraftHearingRequirementsPreparer.java

[RIA-7641](https://tools.hmcts.net/jira/browse/RIA-7641)
- Renamed `getWitnessFullName` to `buildWitnessFullName`. If the method looks like a getter (starts with _-get_) it'll build an object with such field even if not declared in the class, and then it'll fail validation when passed to CCD.
```
[ ] Yes
[x] No
```

RIA-7641 Rename getter-like field to something non-getter-like

---

charts/ia-case-api/Chart.yaml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/InterpreterLanguagesUtils.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DraftHearingRequirementsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/InterpreterLanguagesDynamicListUpdater.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateHearingRequirementsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/WitnessesMidEventHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DraftHearingRequirementsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateHearingRequirementsHandlerTest.java

[RIA-7641](https://tools.hmcts.net/jira/browse/RIA-7641)
- Made handlers clear interpreter fields for appellant if `isInterpreterServicesNeeded` is set to no (otherwise they'd persist in the case data even if invisible on the UI)
```
[ ] Yes
[x] No
```

RIA-7641 Clear appellant interpreter language when updating hearing reqs

---

build.gradle
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/WitnessDetails.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/InterpreterLanguagesUtils.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/InterpreterLanguagesDynamicListUpdater.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/WitnessesDraftMidEventHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/WitnessesUpdateMidEventHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/InterpreterLanguagesDynamicListUpdaterTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/WitnessesDraftMidEventHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/WitnessesUpdateMidEventHandlerTest.java

[RIA-7642](https://tools.hmcts.net/jira/browse/RIA-7642)
- Logic to retain the old witnesses and their language selections into the new list of witnesses, so that old witnesses' fields are prepopulated and new witnesses' fields are unselected but functional
E.G.
```
Witness1 = German
Witness2 = Polish
Witness3 = /
Witness4 = Japanese
Witness5 = Arabic
Witness6 = Turkish
```
DELETING WITNESS4
```
Witness1 = German
Witness2 = Polish
Witness3 = /
------------------------> [Witness4 = Japanese]
Witness(5)4 = Arabic
Witness(6)5 = Turkish
```
ADDING ANOTHER WITNESS NEEDING Finnish
```
Witness1 = German
Witness2 = Polish
Witness3 = /
Witness4 = Arabic
Witness5 = Turkish
[Witness6 = Finnish]   <------------------------
```
Witness4 no longer needs Japanese, but is ex-Witness5 (Arabic)
Witness5 no …

RIA-7642 Update hearing reqs witnesses languages

---

charts/ia-case-api/Chart.yaml
src/functionalTest/resources/scenarios/RIA-3763-RIA-submit-hearing-requirements-single-requirements-exist.json
src/functionalTest/resources/scenarios/RIA-3763-submit-reheard-hearing-requirements-multiple-requirements-exist.json
src/functionalTest/resources/scenarios/RIA-3763-submit-reheard-hearing-requirements-single-requirements-exist.json
src/functionalTest/resources/scenarios/RIA-436-RIA-2087-submit-hearing-requirements.json
src/functionalTest/resources/scenarios/RIA-587-hearing-requirements-request-docmosis-enabled.json
src/functionalTest/resources/scenarios/RIA-7507-submit-hearing-requirements-with-interpreter-sign-language.json
src/functionalTest/resources/scenarios/RIA-7507-submit-hearing-requirements-with-interpreter-spoken-language.json
src/functionalTest/resources/scenarios/RIA-7750-party-id-generation-draft-hearing-requirement.json
src/functionalTest/resources/scenarios/RIA-7750-party-id-generation-edit-appeal-out-of-country-with-sponsor.json
src/functionalTest/resources/scenarios/RIA-7750-party-id-generation-edit-appeal.json
src/functionalTest/resources/scenarios/RIA-7750-party-id-generation-start-appeal-out-of-country-with-sponsor.json
src/functionalTest/resources/scenarios/RIA-7750-party-id-generation-start-appeal.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/WitnessDetails.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/PartyIdHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/PartyIdHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7750
- Party ID generation for  appellant, legal rep, witness and sponsor by using JAVA UUID
- Party ID generation involve the startAppeal, editAppeal and draftHearingRequirements event
- Some of the functional tests need to be disabled because of the change of https://github.com/hmcts/ia-case-documents-api/pull/662. After merging the change of ia-case-documents-api, those functional tests could be active again
```
[ ] Yes
[X] No
```

RIA-7750 party ID generation LR journey

---

config/owasp/suppressions.xml
src/functionalTest/resources/scenarios/RIA-3763-RIA-submit-hearing-requirements-single-requirements-exist.json
src/functionalTest/resources/scenarios/RIA-3763-submit-reheard-hearing-requirements-multiple-requirements-exist.json
src/functionalTest/resources/scenarios/RIA-3763-submit-reheard-hearing-requirements-single-requirements-exist.json
src/functionalTest/resources/scenarios/RIA-436-RIA-2087-submit-hearing-requirements.json
src/functionalTest/resources/scenarios/RIA-587-hearing-requirements-request-docmosis-enabled.json
src/functionalTest/resources/scenarios/RIA-7507-submit-hearing-requirements-with-interpreter-sign-language.json
src/functionalTest/resources/scenarios/RIA-7507-submit-hearing-requirements-with-interpreter-spoken-language.json
src/functionalTest/resources/scenarios/RIA-7752-aip-party-id-generation-edit-appeal-out-of-country-with-sponsor.json
src/functionalTest/resources/scenarios/RIA-7752-aip-party-id-generation-edit-appeal.json
src/functionalTest/resources/scenarios/RIA-7752-aip-party-id-generation-start-appeal-out-of-country-with-sponsor.json
src/functionalTest/resources/scenarios/RIA-7752-aip-party-id-generation-start-appeal.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryEditAppealAipHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryEditAppealHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/PartyIdHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryEditAppealAipHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryEditAppealHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/PartyIdHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7752
- Party ID generation for appellant and sponsor by using JAVA UUID when the appeal is AIP journey
- Add the unit test for AIP journey
- Resume the functional tests of "draftHearingRequirement" event because the PR of https://github.com/hmcts/ia-case-documents-api/pull/662 has been merged to branch
- Temporarily suppress the CVE problem
```
[ ] Yes
[X] No
```

RIA-7752 party ID generation AIP journey

---

src/functionalTest/resources/scenarios/RIA-7480-review-add-in-private-flag.json
src/functionalTest/resources/scenarios/RIA-7483-7579-appellant-witness-case-level-case-flags.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/CaseFlagValue.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/PartyFlagIdValue.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/StrategicCaseFlag.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/HandlerUtils.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppellantCaseFlagsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CreateFlagHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EvidenceInPrivateCaseFlagsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HearingRequirementsAppellantCaseFlagsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/HandlerUtilsTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppellantCaseFlagsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CreateFlagHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EvidenceInPrivateCaseFlagsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HearingRequirementsAppellantCaseFlagsHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7869
* Some refactorings
* Create a class to enclose the ID-VALUE pair for witness level flags (for clarity and documentation of the use of the ID here as an identifier for the witness related to the flags)
* Update 'CreateFlagsHandler' to use this new class for Witness flags
* Use 'witnessPartyId' field as the ID for the witness level flags. This 'witnessPartyId' is set to the ID part of the witness level flags to create a 1:1 map between a witness and a witness level set of flags.
```
[ ] Yes
[x] No
```

RIA-7869 Allow unique identifying of flags based off witnesses

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DetentionFacilityEditAppealHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DetentionFacilityEditAppealHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7839
- Due to removing detention screens for edit post submit event, these fields cannot be edited and do not need to be clearing any fields
- Only field that may still need cleared is on Removal directions screen so that part remains as was
```
[ ] Yes
[X] No
```

RIA-7839 edit post submit detention handler changes

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7706
https://tools.hmcts.net/jira/browse/RIA-7278
* Enabled requestResponseAmend event to internal events to handle
* Updated SendNotificationHandlerTest
```
[ ] Yes
[X] No
```

RIA-7278 RIA-7706 Enable internal notification for requestResponseAmend event

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java

[RIA-7793](https://tools.hmcts.net/jira/browse/RIA-7793)
- Added new `handleHearingException` event to config

RIA-7793 Trigger event for Hmc exception to make WA task

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/InterpreterLanguagesUtils.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/WitnessesUpdateMidEventHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/InterpreterLanguagesUtilsTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/WitnessesUpdateMidEventHandlerTest.java

[RIA-7922](https://tools.hmcts.net/jira/browse/RIA-7922)
- Made sure the fieldsToBeCleared list that collects fields to be cleared is emptied each time the user goes through the `whichWitnessRequiresInterpreter` page, otherwise it keeps stale data, as the class is a bean

RIA-7922 Maintanance for witness fields

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/InterpreterLanguagesUtils.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DraftHearingRequirementsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/WitnessesUpdateMidEventHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DraftHearingRequirementsHandlerTest.java

[RIA-7922](https://tools.hmcts.net/jira/browse/RIA-7922)
- Added check against NPE in WitnessesUpdateMidEventHandler
- Added check for old language to be empty OR present with an object with null fields
- Cleared WitnessListElement(N) when submitting of `draftHearingRequirements` (field only used for AIP screens)

RIA-7792 clear witness list element fields

---

src/functionalTest/resources/scenarios/RIA-7338-review-sign-language-appellant-flag.json
src/functionalTest/resources/scenarios/RIA-7338-update-sign-language-appellant-flag.json
src/functionalTest/resources/scenarios/RIA-7658-review-add-witness-interpreter.json
src/functionalTest/resources/scenarios/RIA-7658-update-witness-interpreter.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/StrategicCaseFlagType.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppellantInterpreterLanguageFlagsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateHearingRequirementsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/WitnessInterpreterLanguageFlagsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppellantInterpreterLanguageFlagsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/WitnessInterpreterLanguageFlagsHandlerTest.java

[RIA-7837](https://tools.hmcts.net/jira/browse/RIA-7837)
- Changed enum value (`Sign language` --> `Sign language interpreter`)
- Made sure InterpreterLanguageRefData only has enabled value (no dynamic list if language manually entered, no manual language if no manual language selected.

RIA-7837 Update witness flags when language manual

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/field/Document.java

https://tools.hmcts.net/jira/browse/RIA-7478
Added ignore 'document_hash' property for Document.java

RIA-7478 Added ignore 'document_hash' property for Document.java

---

src/functionalTest/resources/scenarios/RIA-7714_ho_respond_to_costs.json
src/functionalTest/resources/scenarios/RIA-7714_lr_respond_to_costs.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ApplyForCosts.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RespondToCostsConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RespondToCostsPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/applyforcosts/RespondToCostsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/ApplyForCostsAppender.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/ApplyForCostsProvider.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ApplyForCostsTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/applyForCosts/RespondToCostsConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RespondToCostsPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/applyforcosts/RespondToCostsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/ApplyForCostsAppenderTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/ApplyForCostsProviderTest.java

- Preparer: to validate if user can trigger the event or not & if yes, then populate DynamicList for the dropdown.
- Handler: to set the field values on the applyForCosts object and clear the fields.

RIA-7714 Added new event 'Respond to costs'

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/StrategicCaseFlagService.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/StrategicCaseFlagServiceTest.java

[RIA-7837](https://tools.hmcts.net/jira/browse/RIA-7837)
- Made sure flags get updated when a manual language gets updated with another manual language
(issue was that both old and new languages had null code/key, so null equalling null would make the condition return true when checking whether the language matched the flag)

RIA-7837 Update caseflags for manual languages updated with manual languages

---

config/owasp/suppressions.xml
src/functionalTest/resources/scenarios/RIA-7780-decide-an-application-change-hearing-type-error.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DecideAnApplicationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DecideAnApplicationHandlerTest.java

[RIA-8397](https://tools.hmcts.net/jira/browse/RIA-8397)
- Made condition to delete hearing request be based on current state of the case instead of state that was written into the application at the time the application was submitted

RIA-8397 Take state for deletion condition from case instead of application

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LegalRepresentativeUpdateDetailsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/PinInPostActivated.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/PartyIdService.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LegalRepresentativeUpdateDetailsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/PartyIdServiceTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/PinInPostActivatedTest.java

[RIA-8432](https://tools.hmcts.net/jira/browse/RIA-8432)
[RIA-8433](https://tools.hmcts.net/jira/browse/RIA-8433)
- `legalRepIndividualPartyId` and `legalRepOrganisationPartyId` to be cleared when all other LR fields are cleared (`PIP_ACTIVATION` event)
- Calling `resetLegalRepPartyId(asylumCase)` in `LegalRepresentativeUpdateDetailsHandler.java` to regenerate `legalRepIndividualPartyId` and `legalRepOrganisationPartyId` when `UPDATE_LEGAL_REPRESENTATIVES_DETAILS` runs because of a change in LR (cannot call it from another class otherwise CHANGE_ORGANISATION_REQUEST_FIELD will have been cleared by then)

RIA-8432 RIA-8433 Tweak legalRepPartyId(s)

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java

[RIA-8419](https://tools.hmcts.net/jira/browse/RIA-8419)
- Added `decisionWithoutHearingListed` event

RIA-8419 Decision without hearing listed

---

src/functionalTest/resources/scenarios/RIA-7983-review-hearing-requirements-auto-hearing-request-enabled.json
src/functionalTest/resources/scenarios/RIA-7986-list-case-without-hearing-requirements-automatically-failed.json
src/functionalTest/resources/scenarios/RIA-7987-RIA-7988-review-hearing-requirements-auto-request-hearing-failed.json
src/functionalTest/resources/scenarios/RIA-7987-RIA-7988-review-hearing-requirements-auto-request-hearing-succeeded.json
src/functionalTest/resources/scenarios/RIA-8231-list-case-without-hearing-requirements-automatically-panel-required.json
src/functionalTest/resources/scenarios/RIA-8231-review-hearing-requirements-auto-request-hearing-panel-required.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/HandlerUtils.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AutoRequestHearingConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ListCaseWithoutHearingRequirementsConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ReviewHearingRequirementsConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListCaseWithoutHearingRequirementsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewDraftHearingRequirementsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/HandlerUtilsTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AutoRequestHearingConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ListCaseWithoutHearingRequirementsConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ReviewHearingRequirementsConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListCaseWithoutHearingRequirementsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewDraftHearingRequirementsHandlerTest.java

[RIA-8231](https://tools.hmcts.net/jira/browse/RIA-8231)
- Added `!isPanelRequired` to the conditions for autorequesting a hearing when executing `reviewHearingRequirements` and `listCaseWithoutHearingRequirements`

RIA-8231 Panel requirement for reviewHearingRequirements and listCaseWithoutHearingRequirements

---

src/functionalTest/resources/scenarios/RIA-8074-internal-ejp-case-request-case-edit-direction.json
src/functionalTest/resources/scenarios/RIA-8074-internal-ejp-force-request-case-building-direction.json
src/functionalTest/resources/scenarios/RIA-8074-internal-ejp-request-case-building-direction.json
src/functionalTest/resources/scenarios/RIA-8074-internal-ejp-request-new-hearing-requirements-direction.json
src/functionalTest/resources/scenarios/RIA-8074-internal-ejp-request-response-review-direction.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/HandlerUtils.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestCaseBuildingPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestCaseEditPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestHearingRequirementsDirectionHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestNewHearingRequirementsDirectionPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestResponseReviewHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/DirectionPartiesResolver.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/HandlerUtilsTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestCaseBuildingPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestCaseEditPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestHearingRequirementsDirectionTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestResponseReviewHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/DirectionPartiesResolverTest.java

https://tools.hmcts.net/jira/browse/RIA-8074
- Standard direction party being set to 'Appellant' for EJP scenario: 
**isEjp = Yes, appellantInDetention = No, isLegallyRepresentedEjp = No**
- Updates to DirectionPartiesResolver and handlers/preparers for these events:
**REQUEST_CASE_EDIT,
REQUEST_CASE_BUILDING,
FORCE_REQUEST_CASE_BUILDING,
REQUEST_RESPONSE_REVIEW,
REQUEST_NEW_HEARING_REQUIREMENTS.**

RIA-8074 Standard direction party appellant for EJP scenario

---

charts/ia-case-api/Chart.yaml
src/functionalTest/resources/scenarios/RIA-7456-edit-appeal-detained-ejp-case.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EjpEditAppealHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HearingTypeHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/IsEjpHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EjpEditAppealHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HearingTypeHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/IsEjpHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7456
- EjpEditAppealHandler: this new handler handles scenarios when editing between EJP repped and unrepped, EJP to Paper form and Paper form to EJP.
- HearingTypeHandler: updated logic to include ejp check for Edit Appeal to set the correct value to show dateLetterReceived for all EJP flows
- IsEjpHandler: updated to set this flag to Yes/No for Edit Appeal event
- Updated and new unit tests
- New functional test for detained scenario

RIA-7456 EJP Edit appeal handling Part 2 - detained

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HearingsUpdateHearingRequest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HearingsUpdateHearingRequestTest.java

[RIA-8601](https://tools.hmcts.net/jira/browse/RIA-8601)
- Use `changeHearingVenue` instead of `changeHearingLocation` because it's of type "hearingVenue" and renders correctly on XUI

RIA-8601 change hearing location fix

---

src/functionalTest/resources/scenarios/RIA-7457-edit-appeal-non-detained-ejp-case.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EjpAppellantLegalPracticeAddressMidEventHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EjpContactPreferenceFieldMidEventHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EjpContactPreferenceFieldsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EjpEditAppealHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EjpAppellantLegalPracticeAddressMidEventHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EjpContactPreferenceFieldMidEventHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EjpContactPreferenceFieldsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EjpEditAppealHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7457
- Updates to EJP handlers and mid events to allow handling for Edit Appeal event
- Additional logic to handle clearing of fields when editing between different screens in non-detained flow
- Updated unit tests
- New functional test for EJP non-detained

RIA-7457 EJP Edit appeal part 3 - non detained handlers

---

src/functionalTest/resources/scenarios/RIA-7458-edit-appeal-after-submit-detained-ejp-case.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EditAppealAfterSubmitHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/StartAppealMidEvent.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EditAppealAfterSubmitHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/StartAppealMidEventTest.java

https://tools.hmcts.net/jira/browse/RIA-7458
- Adding 'editAppealAfterSubmit' event to StartAppealMidEvent handler so that the utReferenceNumber validation works
- Adding a check so that out of time fields are not handled for EJP cases (where no decision date is present) in EditAppealAfterSubmitHandler to prevent exception being thrown
- Unit tests updated and functional test added

RIA-7458 EJP Edit appeal after submit

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HearingsUpdateHearingRequest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HearingsUpdateHearingRequestTest.java

[RIA-8659](https://tools.hmcts.net/jira/browse/RIA-8659)
- Added midEvent trigger for `updateHearingRequest` on the date page to prevent users from selecting that the date needs to change with a date range where neither start or end dates are populated (since both fields now have to be optional to allow for the absence of one of them but not both of them)

RIA-8659 Add error to midEvent if date range selected but both start/end empty

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListAssistIntegrationHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/AsylumFieldLegalRepNameFixer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListAssistIntegrationHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/AsylumFieldLegalRepNameFixerTest.java

[RIA-8661](https://tools.hmcts.net/jira/browse/RIA-8661)
- Made "legalRepName" and "legalRepFamilyName" be read and checked during `listAssistIntegration` to detect if "legalRepFamilyName" is empty and needs to be extrapolated from "legalRepName", so old cases that had no "legalRepFamilyName" conform to new cases where first and last name are written in two separate fields

RIA-8661 Fix legalRepFamilyName if needed in ListAssistIntegrationHandler

---

src/functionalTest/resources/scenarios/RIA-8253-mark-appeal-as-remitted.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/MarkAppealAsRemittedConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MarkAppealAsRemittedUploadDecisionHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/MarkAppealAsRemittedConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MarkAppealAsRemittedUploadDecisionHandlerTest.java

- Added confirmation handler for the new event : Mark Appeal As Remitted.

RIA-8253 Added handler to rename the uploaded remittal decision document

---

src/functionalTest/resources/scenarios/RIA-8239-updateTribunalDecision-rule-31-list.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DecisionAndReasons.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateTribunalAppealDecisionRule31.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DecisionAndReasonsTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateTribunalAppealDecisionRule31Test.java

https://tools.hmcts.net/jira/browse/RIA-8239
Added rule 31 updated decisions

RIA-8239 Added rule 31 updated decisions

---

charts/ia-case-api/Chart.yaml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordAdjournmentDetailsMidEventHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordAdjournmentDetailsMidEventHandlerTest.java

[RIA-8742](https://tools.hmcts.net/jira/browse/RIA-8742)
- Made dropdown list with hearing location in `recordAdjournmentDetails` resort to querying the location in hearing details from HMC when `listCaseHearingCentre` is null (before listing) or is present with an empty epims id (`remoteHearing` | `decisionWithoutHearing`)

RIA-8742 Prepopulate location from hmc value if local epims id empty

---

src/functionalTest/resources/scenarios/RIA-8158-8219-updateTribunalDecision-rule-32.json
src/functionalTest/resources/scenarios/RIA-8220-8219-update-tribunal-decision-rule32.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateTribunalDecisionHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateTribunalDecisionHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8219
- show overview information when judge trigger rule 32
- set the value for updateTribunalDecisionDateRule32 and reasonRehearingRule32 when triggered updateTribunalDecision event with rule 32
- updated the unit test and functional test

RIA-8219 update tribunal decision rule32 overview tab post event

---

src/functionalTest/resources/scenarios/RIA-8157-updateTribunalDecisionDocument-rule-31-normal.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaAppellantPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaRespondentPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateTribunalDecisionHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaAppellantPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaRespondentPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateTribunalDecisionHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8778
Allow user to apply FTPA again after update tribunal decision rule 31

RIA-8778 Allow user to apply FTPA again

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealTypeHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EditAppealTypePreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/NabaFeatureTogglePreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealTypeHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EditAppealTypePreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/NabaFeatureTogglePreparerTest.java

- updated the logic for 'AppealTypeForDisplay' and Edit Appeal Preparer, to skip the read of 'AppealTypeForDisplay' if the the feature toggle is turned off for NABA.

RIA-TASK OOC Feature toggle field

---

config/owasp/suppressions.xml
src/functionalTest/resources/scenarios/RIA-8230-dlrm-manage-fee-additional-payment-tribunal-action-confirmation-screen.json
src/functionalTest/resources/scenarios/RIA-8230-dlrm-manage-fee-no-action-tribunal-action-confirmation-screen.json
src/functionalTest/resources/scenarios/RIA-8230-dlrm-manage-fee-refund-tribunal-action-confirmation-screen.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/FeeTribunalAction.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/FeeUpdateReason.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ManageFeeUpdateConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdatePreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/FeeTribunalActionTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/FeeUpdateReasonTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ManageFeeUpdateConfirmationTest.java

https://tools.hmcts.net/jira/browse/RIA-8230
- Added confirmation screen dynamic content based on new Tribunal Action selection (new screen added to ccd-definitions)
- Retained previous logic for legacy scenarios where DLRM-refund feature flag value is not present/no
- Unit and functional tests

RIA-8230 Manage Fee Update confirmation screen updates

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/SourceOfAppeal.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/HandlerUtils.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealUserRoleAppender.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/HandlerUtilsTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealUserRoleAppenderTest.java

https://tools.hmcts.net/jira/browse/RIA-8376
Changes for Internal journey (Start appeal):
- Added 'IS_ADMIN', Source of Appeal, Definitions according to the modified ExUi screens.

 RIA-8376 start_appeal_internal

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LocationRefDataEnabler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LocationRefDataEnablerTest.java

[RIA-8851](https://tools.hmcts.net/jira/browse/RIA-8851)
- Made `isCaseUsingLocationRefData` be written at the end of the START_APPEAL event, so that it's set to YES when the Launch Darkly flag return true for the user(s) that are enabled to use Location Ref Data

RIA-8851 Set isLocationUsingRefData when starting case

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListEditCaseHandler.java

[RIA-8782](https://tools.hmcts.net/jira/browse/RIA-8782)
- `listCaseHearingCentre` is still needed in a number of places across the code of ia-case-api, ia-case-documents-api and ia-case-notifications-api. This trick will write `listCaseHearingCentre` in parallel with `listingLocation` until the ticket that properly cleans up the move from the old field (`listCaseHearingCentre`) to the new one (`listingLocation`)

RIA-8782 listing location alignment with list case hearing centre

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordRemissionDecisionStateHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordRemissionDecisionStateHandlerTest.java

https://tools.hmcts.net/jira/browse/DIAC-489
"hasServiceRequestAlready" changes in RecordRemissionDecisionStateHandler were reverted and causing issues in Service Request tab. Remove code setting ""hasServiceRequestAlready" value.

DIAC-489 Revert hasServiceRequestAlready changes in RecordRemissionDecisionStateHandler

---

src/contractTest/java/uk/gov/hmcts/reform/iacaseapi/consumer/roleassignment/RoleAssignmentApiConsumerTest.java

https://tools.hmcts.net/jira/browse/DIAC-505
remove header from pact consumer test

DIAC-505 - will remove close connection header from AM pact test

---

src/functionalTest/resources/scenarios/RIA-8975-add-is-aria-migrated-no.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/migratedcase/AriaCreateCaseHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/migratedcase/CreateMigratedCasePreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/migratedcase/StartAppealCreateCaseHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/migratedcase/AriaCreateCaseHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/migratedcase/StartAppealCreateCaseHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8975
Added handler to set isAriaMigrated for StartAppeal event

RIA-8975 Added handler to set isAriaMigrated for StartAppeal event

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordRemissionDecisionStateHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordRemissionDecisionStateHandlerTest.java

When Remission request is rejected, hasServiceRequest data field value should be empty/No to allow legal representative to make payment

DIAC-000 Revert service request value changes

---

build.gradle
config/owasp/suppressions.xml

[DIAC-557](https://tools.hmcts.net/jira/browse/DIAC-557)
Update postgresql to v42.4.4  (patch) fixing critical CVE-2024-1597
Update  uk.gov.service.notify notifications-java-client to v5.0.1-RELEASE (major) fixing [CVE-2023-5072](https://nvd.nist.gov/vuln/detail/CVE-2023-5072)
Exclude bouncy castle bcprov-jdk15on from Spring-Cloud-Starter-Bootstrap fixing [CVE-2023-33202](https://nvd.nist.gov/vuln/detail/CVE-2023-33202)
Remove unneeded suppressions

DIAC-557 CVE Fixes

---

charts/ia-case-api/Chart.yaml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestNewHearingRequirementsDirectionHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestNewHearingRequirementsDirectionHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-9452
When submitting hearing requirements without hearing state it saves previousHearingRequirements to the list. 
Added a check if Hearing centre is "DECISION_WITHOUT_HEARING" then skip this saving.

RIA-9452 bug_fix

---

charts/ia-case-api/Chart.yaml

https://tools.hmcts.net/jira/browse/DIAC-1152
DIAC-1152 Redis chart repo connection failure - Redis repository changed to oci://registry-1.docker.io/bitnamicharts and version to 20.13.4

DIAC-1152 Redis chart repo connection failure 

---

charts/ia-case-api/values.preview.template.yaml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AutomaticEndAppealForNonPaymentEaHuTrigger.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/AiPFeesHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/PaymentHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/PaymentStateHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AutomaticEndAppealForNonPaymentEaHuTriggerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/AiPFeesHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/PaymentStateHandlerTest.java

https://tools.hmcts.net/jira/browse/DIAC-1178
AiP appeals with remission should not be ended automatically before remission decision.
AiP appeals (HU/EU/EA) should be progressed to Appeal submitted state after payment.

DIAC-1178 AiP appeals with remission should not be ended automatically before remission decision

---

README.md
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryEditAppealHandler.java

Reverting fix 1173.  The line that was added was already in our detained branch so the only difference was that it broke our unit tests

DIAC-0000 Reverting fix 1173

---

src/functionalTest/resources/scenarios/DIAC-1160-update-case-appellant-in-person-manual-case-officer.json
src/functionalTest/resources/scenarios/DIAC-1160-update-case-appellant-in-person-manual.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppellantInPersonManualHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EditAppealAfterSubmitHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SetCaseAsUnrepresentedHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EditAppealAfterSubmitHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SetCaseAsUnrepresentedHandlerTest.java

https://tools.hmcts.net/jira/browse/DIAC-1425
DIAC-1425 updates to stop clearing LR details as part of remove representation

DIAC-1425 updates to stop clearing LR details as part of remove representation
