charts/ia-case-api/Chart.yaml
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ProgressBarAdaSuffixAppender.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ProgressBarAdaSuffixAppenderTest.java

[RIA-6618](https://tools.hmcts.net/jira/browse/RIA-6618)
- Add "_ada" suffix appender to be used in images URLs in progress bars
```
[ ] Yes
[x] No
```

RIA-6618 Add ProgressBarAdaSuffixAppender

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/MakeAnApplicationTypesProvider.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/MakeAnApplicationTypesProviderTest.java

https://tools.hmcts.net/jira/browse/RIA-6622
```
[ ] Yes
[x] No
```

RIA-6622 Changes to Make an application dropdown for ADA cases

---

Jenkinsfile_CNP
Jenkinsfile_parameterized
build.gradle
charts/ia-case-api/Chart.yaml
config/owasp/suppressions.xml
src/functionalTest/resources/scenarios/RIA-3298-remove-deport-flag.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/callback/DispatchPriority.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/CancelAutomaticEndAppealPaidConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AutomaticEndAppealForNonPaymentEaHuTrigger.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AutomaticEndAppealForRemissionRejectedTrigger.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DecideAnApplicationMidEvent.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseNotificationsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/PreSubmitCallbackDispatcher.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/callback/DispatchPriorityTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/CancelAutomaticEndAppealPaidConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AutomaticEndAppealForNonPaymentEaHuTriggerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AutomaticEndAppealForRemissionRejectedTriggerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseNotificationsHandlerTest.java

Prod Release Rebase

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UploadAppealFormHandler.java

Update to fix code quality issue
Update to fix code quality issue
```
[ ] Yes
[X ] No
```

Update to fix code quality issue

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UploadAppealFormHandler.java

To fix sonar quality gate issues
To fix sonar quality gate issues
```
[ ] Yes
[X ] No
```

To fix sonar quality gate issues

---

src/functionalTest/resources/scenarios/RIA-6647-ftpa-appellant-in-flight-cases-ooc-in-time-submission.json
src/functionalTest/resources/scenarios/RIA-6647-ftpa-appellant-in-flight-cases-ooc-out-of-time-submission.json
src/functionalTest/resources/scenarios/RIA-6647-ftpa-appellant-in-flight-cases-uk-in-time-submission.json
src/functionalTest/resources/scenarios/RIA-6647-ftpa-appellant-in-flight-cases-uk-out-of-time-submission.json
src/functionalTest/resources/scenarios/RIA-6647-ftpa-respondent-in-flight-cases-ooc-in-time-submission.json
src/functionalTest/resources/scenarios/RIA-6647-ftpa-respondent-in-flight-cases-ooc-out-of-time-submission.json
src/functionalTest/resources/scenarios/RIA-6647-ftpa-respondent-in-flight-cases-uk-in-time-submission.json
src/functionalTest/resources/scenarios/RIA-6647-ftpa-respondent-in-flight-cases-uk-out-of-time-submission.json
src/functionalTest/resources/templates/minimal-appeal-submitted-ooc.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaAppellantPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaRespondentPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaAppellantPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaRespondentPreparerTest.java

https://tools.hmcts.net/jira/browse/RIA-6647
Added functionality to handle in flight cases where no ftpaApplicationDeadline is present for appellant/respondent ftpa applications.
```
[ ] Yes
[X] No
```

Ria 6647 ftpa in flight rework

---

config/owasp/suppressions.xml
src/contractTest/java/uk/gov/hmcts/reform/iacaseapi/consumer/ccd/CcdSupplementaryConsumerTest.java
src/functionalTest/resources/scenarios/RIA-6542-aip-dc-submit-appeal.json
src/functionalTest/resources/scenarios/RIA-6542-aip-ea-submit-appeal.json
src/functionalTest/resources/scenarios/RIA-6542-aip-pa-payLater-submit-appeal.json
src/functionalTest/resources/scenarios/RIA-6542-aip-pa-payNow-submit-appeal.json
src/functionalTest/resources/templates/minimal-aip-appeal-started.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSubmittedConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/CancelAutomaticEndAppealPaidConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AsylumSupplementaryDataFixingHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AutomaticEndAppealForNonPaymentEaHuTrigger.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/FeesAndStatusCheckPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/FeesHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/PaymentStateHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/CcdSupplementaryUpdater.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/CancelAutomaticEndAppealPaidConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AutomaticEndAppealForNonPaymentEaHuTriggerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeesHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/FeesAndStatusCheckPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/CcdSupplementaryUpdaterTest.java

- rebased ia-case-api-aip-payment on master
```
[ ] Yes
[x] No
```

master <- AIP Payment rebased (DO NOT MERGE)

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AutomaticEndAppealForNonPaymentEaHuTrigger.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AutomaticEndAppealForNonPaymentEaHuTriggerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeesHandlerTest.java

Updates to rebase and fix  unit tests
Updates to rebase and fix  unit tests
```
[ ] Yes
[X ] No
```

Updates to rebase and fix  unit tests

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AutomaticEndAppealForNonPaymentEaHuTrigger.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AutomaticEndAppealForRemissionRejectedTrigger.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AutomaticEndAppealForNonPaymentEaHuTriggerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AutomaticEndAppealForRemissionRejectedTriggerTest.java

https://tools.hmcts.net/jira/browse/RIA-6854
Added ADA check on auto end appeal handlers and updated their unit tests.
```
[ ] Yes
[X] No
```

RIA-6854 Detained ADA appeals ending Automatically

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java

[RIA-6811](https://tools.hmcts.net/jira/browse/RIA-6811)
- Enable `DECIDE_AN_APPLICATION` for internal ADA cases notifications
```
[ ] Yes
[x] No
```

RIA-6811 Enable decideAnApplication for internal cases' notifications

---

src/functionalTest/resources/scenarios/RIA-6733-mark-hu-appeal-as-paid-admin-officer.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/MarkPaymentPaidPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/MarkPaymentPaidPreparerTest.java

https://tools.hmcts.net/jira/browse/RIA-6733
* Attempt to mark internal cases as paid should fail with error when awaiting remission decision or remission is approved
```
[ ] Yes
[x] No
```

RIA-6733 Make "Mark appeal as paid" event available for internal case creation

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java

https://tools.hmcts.net/jira/browse/RIA-6780
```
[ ] Yes
[x] No
```

RIA-6780: Request response review notification for internal ADA cases

---

charts/ia-case-api/Chart.yaml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java

[RIA-6920](https://tools.hmcts.net/jira/browse/RIA-6920)
- Added `makeAnApplication` to events that send notifications for internal cases
```
[ ] Yes
[x] No
```

RIA-6920 Add makeAnApplication to internal case notifications

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java

https://tools.hmcts.net/jira/browse/RIA-6781
Added ADA suitability review event to internal events to handle
```
[ ] Yes
[X] No
```

RIA-6781 ADA suitability review for internal cases - DET notification

---

infrastructure/state.tf

Update to increment azurerm version in terraform
Update to increment azurerm version in terraform
```
[ ] Yes
[X ] No
```

Update to increment azurerm version in terraform

---

charts/ia-case-api/Chart.yaml
charts/ia-case-api/values.yaml

Updates to fix postgress variable in values.yaml
Updates to fix postgress variable in values.yaml
```
[ ] Yes
[X ] No
```

Updates to fix postgress variable in values.yaml

---

charts/ia-case-api/Chart.yaml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java

https://tools.hmcts.net/jira/browse/RIA-6784
```
[ ] Yes
[x] No
```

RIA-6784: Enable 'applyForFTPAAppellant' for internal cases

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java

https://tools.hmcts.net/jira/browse/RIA-6785
```
[ ] Yes
[x] No
```

RIA-6785: Enable 'applyForFTPARespondent' event for internal cases

---

src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/RIA-6901
Modified yaml entry and changed value for ada ftpa time to appeal from 5 to 7.
```
[ ] Yes
[X] No
```

Ria 6901 ADA ftpa time to appeal should be changed from 5 to 7

---

src/functionalTest/resources/scenarios/RIA-1293-ftpa-appellant-out-of-time-flag-on-submit.json
src/functionalTest/resources/scenarios/RIA-2581-ftpa-respondent-in-time-homeoffice-generic-submit.json
src/functionalTest/resources/scenarios/RIA-2581-ftpa-respondent-out-of-time-flag-set-homeoffice-generic.json
src/functionalTest/resources/scenarios/RIA-2581-ftpa-respondent-out-of-time-flag-set-homeoffice-pou.json
src/functionalTest/resources/scenarios/RIA-3132-ftpa-reheard-appellant-flag-on.json
src/functionalTest/resources/scenarios/RIA-3132-ftpa-reheard-respondent-flag-on.json
src/functionalTest/resources/scenarios/RIA-3954-ftpa-appellant-in-time-flag-off-submit-ooc.json
src/functionalTest/resources/scenarios/RIA-3954-ftpa-appellant-out-of-time-flag-on-submit-ooc.json
src/functionalTest/resources/scenarios/RIA-3954-ftpa-respondent-in-time-flag-set-homeoffice-generic-ooc.json
src/functionalTest/resources/scenarios/RIA-3954-ftpa-respondent-out-of-time-flag-set-homeoffice-generic-ooc.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaAppellantPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaRespondentPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaAppellantPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaRespondentPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-6950
-Revert back full month implementation from PR:
https://github.com/hmcts/ia-ccd-definitions/pull/1044/files
https://github.com/hmcts/ia-case-api/pull/1314/files
-As discussion with Marcello, keep some files remain unchanged from above PR (Chart.yaml, state.tf and MapValueExpander)
```
[ ] Yes
[X] No
```

RIA-6950 FTPA journey (Revert back Full month implementation)

---

config/owasp/suppressions.xml

To suppress CVEs for doc store release
To suppress CVEs for doc store release
```
[ ] Yes
[X ] No
```

To suppress CVEs for doc store release

---

config/owasp/suppressions.xml

To revert CDAM changes in prod
To revert CDAM changes in prod
```
[ ] Yes
[X ] No
```

To revert CDAM changes in prod

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/main/resources/application.yaml

[RIA-6132](https://tools.hmcts.net/jira/browse/RIA-6132)
- `applyForFTPAAppellant` enabled for citizen
```
[ ] Yes
[x] No
```

RIA-6132: Appellant Submits FTPA Application - In Time

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/PreSubmitCallbackDispatcherTest.java

[RIA-6112](https://tools.hmcts.net/jira/browse/RIA-6112)
[RIA-6133](https://tools.hmcts.net/jira/browse/RIA-6133)
- Use feature toggle to disable notifications for `applyForFTPAAppellant` if feature flag false && journey is AIP
```
[ ] Yes
[x] No
```

RIA-6112 RIA-6133 Enable/Disable ftpa notification with feature flag

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

[RIA-6115](https://tools.hmcts.net/jira/browse/RIA-6115)
- Don't allow notifications for `APPLY_FOR_FTPA_RESPONDENT` when FTPA AIP feature is disabled and journey is AIP
```
[ ] Yes
[x] No
```

RIA-6115 FTPA submitted by HO (AIP journey)

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/CcdScenarioRunnerTest.java
src/functionalTest/resources/scenarios/RIA-2783-edit-documents.json

https://tools.hmcts.net/jira/browse/RIA-6560
Updates to allow functional tests to run on windows machines.
```
[ ] Yes
[x] No
```

RIA-6560 - Functional tests improvements

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java

https://tools.hmcts.net/jira/browse/RIA-7030
Added reinstate appeal event to internal events to handle
```
[ ] Yes
[X] No
```

RIA-7030 add reinstate appeal event to internalEventsToHandle

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java

https://tools.hmcts.net/jira/browse/RIA-7031
* Added submitAppeal event to internalEventsToHandle method
```
[ ] Yes
[X] No
```

RIA-7031 submitAppeal unrepped/internal notifications

---

charts/ia-case-api/values.preview.template.yaml
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java

https://tools.hmcts.net/jira/browse/RIA-7032
RIA-7032 - Adding end appeal event notification for internal cases
```
[ ] Yes
[x] No
```

RIA-7032 - Adding end appeal event notification for internal cases

---

src/functionalTest/resources/scenarios/RIA-635-appeal-saved-confirmation-edit.json
src/functionalTest/resources/scenarios/RIA-815-appeal-saved-confirmation-start.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSavedConfirmation.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSavedConfirmationTest.java

https://tools.hmcts.net/jira/browse/RIA-7068
- Updated appealSaved confirmation screen handler so that both Admin and LRs see new content 'the appeal' plus unit tests changes
```
[ ] Yes
[X] No
```

RIA-7068 LR appeal saved confirmation screen content change

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSubmittedConfirmation.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSubmittedConfirmationTest.java

https://tools.hmcts.net/jira/browse/RIA-7009
RIA-7009 - QA fix - updating submit appeal confirmation screen images
```
[ ] Yes
[x] No
```

RIA-7009 - QA fix - updating confirmation screen images

---

config/checkstyle/checkstyle.xml
src/integrationTest/java/uk/gov/hmcts/reform/iacaseapi/component/testutils/TestClassOrderer.java
src/integrationTest/resources/junit-platform.properties

RIA-6987
```
[ ] Yes
[x] No
```

RIA-6987 Fix integration tests execution order

---

src/functionalTest/resources/scenarios/RIA-2864-HandleClarifyingQuestions.json
src/functionalTest/resources/scenarios/RIA-3017-HandleCmaRequirements.json
src/functionalTest/resources/scenarios/RIA-3144-SetupAppellantDocuments.json
src/functionalTest/resources/scenarios/RIA-4540-RIA-4272-direction-publish-on-HandleClarifyingQuestions.json
src/functionalTest/resources/scenarios/RIA-4540-RIA-4272-direction-publish-on-HandleCmaRequirements.json
src/functionalTest/resources/scenarios/RIA-4722-complete-clarifying-questions.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ChangeDirectionDueDateActionAvailableUpdater.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendDirectionActionAvailableUpdater.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ChangeDirectionDueDateActionAvailableUpdaterTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendDirectionActionAvailableUpdaterTest.java

https://tools.hmcts.net/jira/browse/RIA-7105
```
[ ] Yes
[x] No
```

RIA-7105: Enable Non Standard Directions for AIP Applications

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SetCaseAsUnrepresentedHandler.java

Change logic usage after code smell on pipeline.
```
[ ] Yes
[X] No
```

RIA-7040 Fixing code smell issues for pipeline build

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseNotificationsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseValidatePreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/HomeOfficeApiService.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/AsylumCaseCallbackApiDelegator.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/controllers/advice/CallbackControllerAdvice.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/AsylumCaseCallbackApiDelegatorTest.java

RIA-7171
Added additional logging to diagnose an issue in production
```
[ ] Yes
[x] No
```

RIA-7171 Improved logging to diagnose an issue

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MinorTagHandler.java

To fix quality gate failure
To fix quality gate failure
```
[ ] Yes
[X ] No
```

To fix quality gate failure

---

bin/add-roles.sh

Roles update, added ia_caselinks_profile to preview env
```
[ ] Yes
[x ] No
```

RIA-7254_roles_update: add ia_caselinks_profile

---

charts/ia-case-api/values.preview.template.yaml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7158
* Added requestCaseBuilding event to GenerateDocumentHandler
* Updated GenerateDocumentHandlerTest
```
[ ] Yes
[X] No
```

RIA-7158 Added requestCaseBuilding event to GenerateDocumentHandler

---

src/functionalTest/resources/templates/minimal-age-assessment-appeal-started.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealTypeHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ProgressBarAdaSuffixAppender.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealTypeHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ProgressBarAdaSuffixAppenderTest.java

https://tools.hmcts.net/jira/browse/RIA-7254
Added naba checks to reduce need for Naba CCD defs to be released alongside code
```
[ ] Yes
[x] No
```

RIA-7254 - Added checks for Naba flag

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EndAppealHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EndAppealHandlerTest.java

Reverts hmcts/ia-case-api#1368

Revert "changes for endAppealAutomatically"

---

config/owasp/suppressions.xml

Suppressed vulnerability temporarily to allow an urgent fix to be deployed

Suppressing vulnerability temporarily

---

src/functionalTest/resources/scenarios/RIA-610-user-details-added-to-case.json
src/functionalTest/resources/templates/minimal-ada-appeal-submitted.json
src/functionalTest/resources/templates/minimal-aip-appeal-submitted.json
src/functionalTest/resources/templates/minimal-appeal-submitted-ooc.json
src/functionalTest/resources/templates/minimal-appeal-submitted.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MinorTagHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateDetentionLocationCaseNoteHandler.java

RIA-7117: Fix Sonar warning

---

src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/RIA-7187
- Updated direction due date to 13 working days for ADA cases (LR/Internal cases)
```
[ ] Yes
[X] No
```

RIA-7187 Updated direction due date for request case building

---

config/owasp/suppressions.xml
src/functionalTest/resources/scenarios/RIA-7484-set-flag-for-update-s94b-status-event.json
src/functionalTest/resources/scenarios/RIA-7484-update-s94b-status-error.json
src/functionalTest/resources/scenarios/RIA-7484-update-s94b-status.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/S94bStatusHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/S94bStatusHandlerTest.java

[RIA-7484](https://tools.hmcts.net/jira/browse/RIA-7484)
[RIA-7424](https://tools.hmcts.net/jira/browse/RIA-7424)
- Added handler for new `updateS94bStatus` event
- Added some flag-setting for some fields
```
[ ] Yes
[x] No
```

RIA-7484 RIA-7424 Handling of S94B

---

src/functionalTest/resources/scenarios/RIA-3555-RIA-3763-RIA-3784-submit-new-hearing-requirements.json
src/functionalTest/resources/scenarios/RIA-3582-RIA-3763-RIA-3784-review-submit-hearing-adjustments-cleared-adjustments.json
src/functionalTest/resources/scenarios/RIA-3582-RIA-3763-RIA-3784-review-submit-hearing-adjustments-current-adjustments-standard-appeal.json
src/functionalTest/resources/scenarios/RIA-3582-RIA-3763-RIA-3784-review-submit-hearing-adjustments-current-adjustments.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/WitnessDetails.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewDraftHearingRequirementsPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DraftHearingRequirementsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewDraftHearingRequirementsPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewUpdateHearingRequirementsPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateHearingRequirementsHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7416
```
[ ] Yes
[x] No
```

RIA-7416: Split witness names to capture first and last names in LR journey

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTag.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTagTest.java

https://tools.hmcts.net/jira/browse/RIA-7173
- Added new document tag for DET attachment letter 'internalAdaSuitability'
- Updated unit test
```
[ ] Yes
[X] No
```

RIA-7173 Adding new document tag 'internalAdaSuitability'

---

config/owasp/suppressions.xml
src/functionalTest/resources/scenarios/RIA-7353-list-case-without-hearing-hequirements-for-retrieving-hearing-channel-type-mid-event.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListCaseWithoutHearingRequirementsMidEventHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListCaseWithoutHearingRequirementsMidEventHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7353
-Added the new page of hearing channel type when trigger "listCaseWithoutHearingRequirements" event
-Retrieve the hearing channel type from common reference data
-Suppressed the CVE problem
```
[ ] Yes
[X] No
```

RIA-7353 set hearing channel type when listing without requirements

---

charts/ia-case-api/Chart.yaml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7172
Added REQUEST_RESPONDENT_REVIEW event to document generation
```
[ ] Yes
[ x ] No
```

RIA-7172: Enable letter generation for 'Request Respondent Review' event

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java

https://tools.hmcts.net/jira/browse/RIA-7199
* Added generate hearing bundle event for internal cases notifications
```
[ ] Yes
[X] No
```

RIA-7199 internal generate hearing bundle event added to sendNotification

---

src/functionalTest/resources/scenarios/RIA-1309-upload-appeal-response-homeoffice-confirmation-generic-user.json
src/functionalTest/resources/scenarios/RIA-1309-upload-appeal-response-homeoffice-confirmation.json
src/functionalTest/resources/scenarios/RIA-1309-upload-appeal-response-homeoffice-submit-generic-user.json
src/functionalTest/resources/scenarios/RIA-1309-upload-appeal-response-homeoffice-submit.json
src/functionalTest/resources/scenarios/RIA-1810-upload-amend-appeal-response-add-new-homeoffice-generic-submit.json
src/functionalTest/resources/scenarios/RIA-1810-upload-amend-appeal-response-add-new-homeoffice-lart-submit.json
src/functionalTest/resources/scenarios/RIA-2177-upload-appeal-response-amend-homeoffice-lart-about_to_start.json
src/functionalTest/resources/scenarios/RIA-2177-upload-appeal-response-amend-homeoffice-lart-errors.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandlerTest.java

RIA-7197: Enable letter generation for 'Upload Appeal Response' event

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java

https://tools.hmcts.net/jira/browse/RIA-7199
* Added async stitching complete event to internal events to handle for notifications
```
[ ] Yes
[X] No
```

RIA-7199 added async stitching complete event to internal events to handle

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandlerTest.java

RIA-7200
add async event to doc gen handler
```
[ ] Yes
[ ] No
```

Ria 7200 add async event to doc gen handler

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/WitnessesMidEventHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/WitnessesMidEventHandlerTest.java

[RIA-7566](https://tools.hmcts.net/jira/browse/RIA-7566)
[RIA-7578](https://tools.hmcts.net/jira/browse/RIA-7578)
- Added error to UI when adding more than 10 witnesses during `draftHearingRequirements` and `updateHearingRequirements`
```
[ ] Yes
[x] No
```

RIA-7566 Limit witnesses to 10

---

infrastructure/main.tf

RIA-7383
Adds new secret that will be used to validate that the deployed application has access to Azure vault secrets (prevents misconfiguration due to incompatibility in libraries that on occasion need upgrading).
```
[ ] Yes
[x] No
```

RIA-7383 Adding secret

---

src/functionalTest/resources/scenarios/RIA-7483-7579-appellant-witness-case-level-case-flags.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/StrategicCaseFlag.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/WitnessDetails.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CreateFlagHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewDraftHearingRequirementsPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/StrategicCaseFlagTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CreateFlagHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7483
```
[ ] Yes
[x] No
```

RIA-7483 Case flags can be added to witnesses

---

charts/ia-case-api/values.preview.template.yaml

RIA-7383
Wiring secrets to the preview pods to prevent build issues related to the secrets being unavailable in preview.
```
[ ] Yes
[x] No
```

RIA-7383 Wiring secrets to preview pods

---

src/functionalTest/resources/scenarios/RIA-3763-RIA-submit-hearing-requirements-single-requirements-exist.json
src/functionalTest/resources/scenarios/RIA-7337-RIA-7340-RIA-2031-update-hearing-requirements.json
src/functionalTest/resources/scenarios/RIA-7337-RIA-7340-RIA-7507-update-hearing-requirements-with-sign-language-interpreter.json
src/functionalTest/resources/scenarios/RIA-7337-RIA-7340-RIA-7507-update-hearing-requirements-with-spoken-language-interpreter.json
src/functionalTest/resources/scenarios/RIA-7337-RIA-7340-review-hearing-requirements-create-hearing-loop-and-wheelchair-access-flags.json
src/functionalTest/resources/scenarios/RIA-7337-RIA-7340-update-hearing-requirements-deactivate-hearing-loop-flags.json
src/functionalTest/resources/scenarios/RIA-7337-RIA-7340-update-hearing-requirements-deactivate-wheelchair-access-flags.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/StrategicCaseFlagType.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AnonymousByDefaultHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HearingRequirementsAppellantCaseFlagsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AnonymousByDefaultHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HearingRequirementsAppellantCaseFlagsHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7337
https://tools.hmcts.net/jira/browse/RIA-7340
```
[ ] Yes
[x] No
```

RIA-7337 RIA-7340 Add Hearing loop and Wheelchair access flag when requested by appellant

---

charts/ia-case-api/Chart.yaml
charts/ia-case-api/values.preview.template.yaml
charts/ia-case-api/values.yaml

Fix issue preventing files from being viewed or downloaded in media-viewer on preview environment
```
[ ] Yes
[x] No
```

RIA-TASK Fix for Media-viewer issues on Preview

---

charts/ia-case-api/Chart.yaml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/Parties.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/PartiesTest.java

https://tools.hmcts.net/jira/browse/RIA-7653
Added missing value to Parties - appellantAndRespondent
```
[ ] Yes
[x ] No
```

RIA-7653_parties_missing_value

---

charts/ia-case-api/Chart.yaml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/InterpreterLanguagesUtils.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DraftHearingRequirementsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/InterpreterLanguagesDynamicListUpdater.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateHearingRequirementsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/WitnessesMidEventHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DraftHearingRequirementsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateHearingRequirementsHandlerTest.java

[https://tools.hmcts.net/jira/browse/RIA-7509](url) (extra work)
- Building on what's already been developed in other PRs:
- static lists moved to a final Utils class
- some fields getting cleared under some circumstances
```
[ ] Yes
[x] No
```

RIA-7509 Clear some fields when needed and move static lists to Utils

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/CaseFlagValue.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AnonymousByDefaultHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HearingRequirementsAppellantCaseFlagsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AnonymousByDefaultHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HearingRequirementsAppellantCaseFlagsHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7677
```
[ ] Yes
[x] No
```

RIA-7677 Update CaseFlagValue, include created date and modified date

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/CaseFlagValue.java

https://tools.hmcts.net/jira/browse/RIA-7677
```
[ ] Yes
[x] No
```

RIA-7677 Ignore unknown CaseFlagValue properties

---

config/owasp/suppressions.xml

---
- Suppressions
```
[ ] Yes
[x] No
```

RIA-6614 Suppressions

---

build.gradle
config/owasp/suppressions.xml

RIA-7721
Upgrade libraries to solve vulnerabilities
```
[ ] Yes
[x] No
```

RIA-7721 Solve vulnerabilities

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/StartAppealMidEvent.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/StartAppealMidEventTest.java

https://tools.hmcts.net/jira/browse/RIA-7475
- Mid event logic added when switching from OOC to In Country. Clearing OOC fields
```
[ ] Yes
[X] No
```

RIA-7475 OOC edit after submit flow

---

config/owasp/suppressions.xml

RIA-7585 Suppress vulnerability on NABA branch

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7561
Added requestHearingRequirementsFeature to events to handle for doc generation
```
[ ] Yes
[X] No
```

RIA-7561 Added requestHearingRequirementsFeature to events to handle for doc generation

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java

https://tools.hmcts.net/jira/browse/RIA-7280
https://tools.hmcts.net/jira/browse/RIA-7673
Added  internal detained ADA and non-ADA edit case listing event to send notification handler.
```
[ ] Yes
[ x ] No
```

RIA-7280 added edit case listing event to send notification handler

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandlerTest.java

* Added decideAnApplication event to GenerateDocumentHandler
* Update tests in GenerateDocumentHandlerTest
```
[ ] Yes
[ ] No
```

RIA-7364 Added decideAnApplication event to GenerateDocumentHandler

---

src/functionalTest/resources/scenarios/RIA-7480-update-add-in-private-flag.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EvidenceInPrivateCaseFlagsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EvidenceInPrivateCaseFlagsHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7480
```
[ ] Yes
[X ] No
```

RIA-7480 Change of requirements to update hearing adjustments

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AsylumSupplementaryDataFixingHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AsylumSupplementaryDataFixingHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7614
Fixedsupplementary data handler
```
[ ] Yes
[ x ] No
```

RIA-7614 fixed supplementary data handler

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/CaseFlagDetail.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/CaseFlagValue.java

[https://tools.hmcts.net/jira/browse/
- Amend classes to allow for deserialization with Jackson
```
[ ] Yes
[x] No
```

RIA-7804 Fix problem with adding flags past the first one

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EditAppealAfterSubmitHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/StartAppealMidEvent.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EditAppealAfterSubmitHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/StartAppealMidEventTest.java

https://tools.hmcts.net/jira/browse/RIA-7521
https://tools.hmcts.net/jira/browse/RIA-7527
- Backend changes to clear suitability fields when editing post submission in ADA scenario
```
[ ] Yes
[X] No
```

RIA-7521 RIA-7527 Handle suitability field clearing

---

charts/ia-case-api/Chart.yaml
charts/ia-case-api/values.preview.template.yaml
charts/ia-case-api/values.yaml

Updated Bundling dependencies for Preview
```
[ ] Yes
[x] No
```

RIA-TASK - Updated Bundling dependencies for Master

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7701
```
[ ] Yes
[ x ] No
```

RIA-7701 Added transfer out of ADA event to document generation

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/CaseFlagDetail.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/CaseFlagValue.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/StrategicCaseFlagType.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AnonymousByDefaultHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AnonymousByDefaultHandlerTest.java

RIA-7816 retrofit bug fixes to case flags branch
RIA-7816 retrofit bug fixes to case flags branch
```
[ ] Yes
[X ] No
```

RIA-7816 retrofit bug fixes to case flags branch

---

charts/ia-case-api/Chart.yaml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7330
- Adding event for document generation
```
[ ] Yes
[X] No
```

RIA-7330 appellant ftpa decided granted document

---

charts/ia-case-api/values.preview.template.yaml
config/owasp/suppressions.xml

[RIA-7166](https://tools.hmcts.net/jira/browse/RIA-7166)
```
[ ] Yes
[x] No
```

RIA-7166 adding required document env variable for upload

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7326
* Added applyForFTPAAppellant event to GenerateDocumentHandler
* Updated GenerateDocumentHandlerTest
```
[ ] Yes
[X] No
```

RIA-7326 Added applyForFTPAAppellant event to GenerateDocumentHandler

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java

https://tools.hmcts.net/jira/browse/RIA-7698
Added send notification for internal transfer out of ADA event
```
[ ] Yes
[ x ] No
```

RIA-7698 Added send notification for internal transfer out of ADA event

---

Jenkinsfile_CNP
charts/ia-case-api/values.preview.template.yaml
config/owasp/suppressions.xml

Merge master changes to NABA case-api
```
[ ] Yes
[x] No
```

RIA-TASK - Merge Master Changes to NABA case-api

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java

https://tools.hmcts.net/jira/browse/RIA-7329
https://tools.hmcts.net/jira/browse/RIA-7676
* Enabling notification generation for residentJudgeFtpaDecision event
```
[ ] Yes
[X] No
```

RIA-7329 Enabling notification generation for residentJudgeFtpaDecision event

---

charts/ia-case-api/values.preview.template.yaml
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/EM-5181
Updated Bundling DB details for Preview to resolve the issue on AAT.
```
[ ] Yes
[X] No
```

RIA-TASK - Updated Bundling DB details for Preview

---

charts/ia-case-api/values.preview.template.yaml

https://tools.hmcts.net/jira/browse/RIA-7878
```
[ ] Yes
[ x ] No
```

RIA-7814 added ia-preview resource group and service bus

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java

https://tools.hmcts.net/jira/browse/RIA-7321 - ADA
https://tools.hmcts.net/jira/browse/RIA-7689 - Non-ADA
- Adding 'Update hearing requirements' event to be handled for internal cases and send notifications
```
[ ] Yes
[X] No
```

RIA-7321 RIA-7689 Adding internal event for notification

---

src/functionalTest/resources/scenarios/RIA-7635-Update-interpreter-details-confirmation.json
src/functionalTest/resources/scenarios/RIA-7699-Update-interpreter-booking-status-confirmation.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/UpdateInterpreterBookingStatusConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/UpdateInterpreterDetailsConfirmation.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/UpdateInterpreterBookingStatusConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/UpdateInterpreterDetailsConfirmationTest.java

RIA-7699 - Fix incorect tab url

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/StartAppealMidEvent.java

https://tools.hmcts.net/jira/browse/RIA-7514
- Adding 'Start appeal' to the mid event handler
```
[ ] Yes
[X] No
```

RIA-7514 Adding start appeal to mid event

---

src/functionalTest/resources/scenarios/RIA-7635-Update-interpreter-details-about-to-submit.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/InterpreterLanguageRefData.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SignLanguageForAppellantCaseFlagsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SpokenLanguageForAppellantCaseFlagsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateInterpreterBookingStatusPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateInterpreterDetailsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateInterpreterBookingStatusPreparerTest.java

RIA-7579 Address reliability issues flagged by Sonarcloud

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7427
- Added following events to GenerateDocumentHandler: uploadAdditionalEvidence and uploadAddendumEvidenceAdminOfficer
```
[ ] Yes
[X] No
```

RIA-7427 Adding events for doc generation

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppellantCaseFlagsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SignLanguageForAppellantCaseFlagsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SpokenLanguageForAppellantCaseFlagsHandler.java

https://tools.hmcts.net/jira/browse/RIA-7412
```
[ ] Yes
[ X] No
```

RIA-7412 fixed issue of appellant sign language set to no

---

charts/ia-case-api/Chart.yaml
charts/ia-case-api/values.preview.template.yaml
config/owasp/suppressions.xml
src/contractTest/resources/application.properties
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/CaseFlagDetail.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/CaseFlagValue.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/LegacyCaseFlag.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/StrategicCaseFlag.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CreateFlagHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/S94bStatusHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AnonymousByDefaultHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CreateFlagHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/CaseFlagAppenderTest.java

RIA-7903 Resolve conflicts and rebase with master
RIA-7903 Resolve conflicts and rebase with master
```
[ ] Yes
[X ] No
```

RIA-7903 Resolve conflicts and rebase with master

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EditAppealAfterSubmitHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeDecisionDateChecker.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EditAppealAfterSubmitHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeDecisionDateCheckerTest.java

https://tools.hmcts.net/jira/browse/RIA-7888
RIA-7888 Set HomeOfficeReferenceNumber to GWFReferenceNumber when appellant selects refusalOfHumanRights or RefusePermit
```
[ ] Yes
[X] No
```

RIA-7888 Set HomeOfficeReferenceNumber to GWFReferenceNumber when appellant selects refusalOfHumanRights or RefusePermit

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7279
* Enabled requestResponseAmend document generation
```
[ ] Yes
[X] No
```

RIA-7279 Enabled requestResponseAmend document generation

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java

https://tools.hmcts.net/jira/browse/RIA-7426 - ADA
https://tools.hmcts.net/jira/browse/RIA-7692 - Non-ADA
- Adding 'Upload Additional Evidence' event to internal lists to enable notifications
```
[ ] Yes
[X] No
```

RIA-7426 RIA-7692 Enabling notification for upload additional evidence

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7437
adding SEND_DIRECTION generateDoc event
```
[ ] Yes
[x ] No
```

RIA-7437 updating send direction roles

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7691 - ADA
https://tools.hmcts.net/jira/browse/RIA-7693 - Non-ADA
- Enabling the notification for event 'uploadAddendumEvidenceAdminOfficer"
```
[ ] Yes
[X] No
```

RIA-7691 RIA-7693 Enabling notification for upload addendum evidence AO

---

src/functionalTest/resources/scenarios/RIA-7657-review-add-witness-interpreter.json
src/functionalTest/resources/scenarios/RIA-7657-update-witness-interpreter.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SpokenLanguageForWitnessCaseFlagsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/WitnessCaseFlagsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SpokenLanguageForWitnessCaseFlagsHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7657
```
[ ] Yes
[X ] No
```

RIA-7657 Added spoken language flag for witness

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandlerTest.java

- RIA-7690 and RIA-7433
- Enable document generation as well.
```
[ ] Yes
[x] No
```

RIA-7432 Enable notifications when LO changes hearing centre

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SpokenLanguageForWitnessCaseFlagsHandler.java

https://tools.hmcts.net/jira/browse/RIA-7657

RIA-7657 incorrect order of param's

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UploadAddendumEvidenceLegalRepHomeOfficeAdminOfficerHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UploadAddendumEvidenceLegalRepHomeOfficeAdminOfficerHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7691 - ADA
https://tools.hmcts.net/jira/browse/RIA-7693 - Non-ADA
Added DispatchPriority 'Latest' to handler so value isn't clear until notification is sent

RIA-7692 RIA-7693 adding latest dispatch to handler

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTag.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTagTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7418
Added edit appeal event when delegating callbacks to documents-API as part of the document generation process
```
[ ] Yes
[x] No
```

RIA-7418 Appeal edited - ADA & Non ADA (Letter)

---

Jenkinsfile_CNP
bin/add-org-roles-to-users.sh

https://tools.hmcts.net/jira/browse/RIA-7814
Added 3 more WA user roles for preview

RIA-7814 Added 3 more WA user roles for preview

---

charts/ia-case-api/Chart.yaml
charts/ia-case-api/values.preview.template.yaml

Preview environment improvements
```
[ ] Yes
[x] No
```

RIA-TASK - Preview environment improvements

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7370
* Enabled document generation when HO uploads additional evidence
* Enabled document generation when HO uploads addendum evidence
* Enabled document generation when LO uploads addendum evidence
* Updated GenerateDocumentHandlerTest

RIA-7370 Enabled doc generation for HO upload additional/addendum evidence and LO upload addendum evidence

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7466
https://tools.hmcts.net/jira/browse/RIA-7710
https://tools.hmcts.net/jira/browse/RIA-7369
https://tools.hmcts.net/jira/browse/RIA-7709
* Enable HO uploads additional/addendum evidences event for internal notifications

RIA-7466 RIA-7710 RIA-7369 RIA-7709 Enable HO uploads additional/addendum evidences event for internal notifications

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7443
https://tools.hmcts.net/jira/browse/RIA-7711
* Enabled uploadAddendumEvidence notifications for internal cases
* Updated SendNotificationHandlerTest

RIA-7443 RIA-7711 Enabled uploadAddendumEvidence notifications for internal cases

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7439
Document generation for Internal HO Direction due date changed
Unit tests

RIA-7439 ho_change_direction_due_date

---

charts/ia-case-api/values.preview.template.yaml

Added env var to stitching service to prevent logging to AAT

RIA-TASK - Updated Stitching Service

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandlerTest.java

RIA-7696 (For non -ADA)
RIA-7471 -Enable letter generation for the same event.

RIA-7470 Enable 'change direction due date' notifications 

---

.github/renovate.json
config/owasp/suppressions.xml

RIA-1234 replacing renovate.json with basic config

---

src/main/resources/application.yaml

[RIA-7881](https://tools.hmcts.net/jira/browse/RIA-7881)
- enable `listCase` for system user

RIA-7881 List the case automatically

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/SourceOfAppeal.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/SourceOfAppealTest.java

* Added new sourceOfAppeal variable to definitions
* Created enum class for source of appeal option values
* Added unit test for new enum class
https://tools.hmcts.net/jira/browse/RIA-7410

RIA-7410 source of appeal

---

src/functionalTest/resources/scenarios/RIA-7703-map-interpreter-to-interpreter-case-flags.json
src/functionalTest/resources/scenarios/RIA-7703-remove-interpreter-flags.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RemoveCaseFlagHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RemoveCaseFlagHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7703

RIA-7703 update callback stage 

---

src/functionalTest/resources/scenarios/RIA-7703-map-interpreter-to-interpreter-case-flags.json
src/functionalTest/resources/scenarios/RIA-7703-remove-interpreter-flags.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RemoveCaseFlagHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RemoveCaseFlagHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7703

RIA-7703 change of event for interpreter flags

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/MakeAnApplicationTypes.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/DecideAnApplicationConfirmation.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/DecideAnApplicationConfirmationTest.java

https://tools.hmcts.net/jira/browse/RIA-7842
Editing success page "Next Steps" are correct after granting application

RIA-7842 Editing granting application success page.

---

charts/ia-case-api/values.preview.template.yaml

adding in CCD_DEFINITION_STORE_API_BASE_URL to preview values to allo…w for adding roles properly

RIA-1234 preview.vaues update

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/StrategicCaseFlagService.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/StrategicCaseFlagServiceTest.java

https://tools.hmcts.net/jira/browse/RIA-7951
* Populate subtype key and value in interpreter language flags with language code and name respectively.

RIA-7951 Refactoring Service Hearing Values payload generation

---

config/owasp/suppressions.xml
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/RIA-7537
Additional role access being given to Legal officer for EJP cases
- [x ] README and other documentation has been updated / added (if needed)
- [x ] Does this PR introduce a breaking change

RIA-7537 EJP LO additional events

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RemoveWitnessCaseFlagsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/WitnessInterpreterLanguageFlagsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/WitnessesDraftMidEventHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/WitnessesUpdateMidEventHandler.java

[RIA-7922](https://tools.hmcts.net/jira/browse/RIA-7922)
- Added logs for investigation of discrepancies between behavior on local env and demo env

RIA-7792 Add logs temporarily for demo investigation

---

src/functionalTest/resources/scenarios/RIA-7771-record-adjournment-details-changes-appeal-status-to-adjourn.json
src/functionalTest/resources/scenarios/RIA-7771-record-adjournment-details-confirmation.json
src/functionalTest/resources/scenarios/RIA-7771-record-adjournment-details-does-not-change-appeal-status-to-adjourn.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/HearingAdjournmentDay.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RecordAdjournmentDetailsConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HearingChannelsDynamicListUpdater.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordAdjournmentDetailsStateHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RecordAdjournmentDetailsConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HearingChannelsDynamicListUpdaterTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordAdjournmentDetailsStateHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7771

RIA-7771 Record adjournment details for List Assist hearing - next hearing

---

src/main/resources/application.yaml

RIA-7882 Trigger edit case listing event
RIA-7882 Trigger edit case listing event

RIA-7882 Trigger edit case listing event

---

src/functionalTest/resources/scenarios/RIA-7338-review-sign-language-appellant-flag.json
src/functionalTest/resources/scenarios/RIA-7338-update-sign-language-appellant-flag.json
src/functionalTest/resources/scenarios/RIA-7412-review-interpreter-language-flag.json
src/functionalTest/resources/scenarios/RIA-7412-update-interpreter-language-flag.json
src/functionalTest/resources/scenarios/RIA-7657-review-add-witness-interpreter.json
src/functionalTest/resources/scenarios/RIA-7657-update-witness-interpreter.json
src/functionalTest/resources/scenarios/RIA-7658-review-add-witness-interpreter.json
src/functionalTest/resources/scenarios/RIA-7658-update-witness-interpreter.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/StrategicCaseFlagService.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppellantInterpreterLanguageFlagsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/WitnessInterpreterLanguageFlagsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/StrategicCaseFlagServiceTest.java

https://tools.hmcts.net/jira/browse/RIA-7617

RIA-7617 Fix issue with interpreter language flag name format

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/EndAppealConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/HearingsUpdateHearingRequestConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EndAppealHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HearingsUpdateHearingRequest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/EndAppealConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/HearingsUpdateHearingRequestConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EndAppealHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HearingsUpdateHearingRequestTest.java

(https://tools.hmcts.net/jira/browse/RIA-7904)
- [x ] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)

RIA-7904 - Inform user if hearing cannot be auto updated + refactor end appeal event

---

src/functionalTest/resources/scenarios/RIA-7509-submit-hearing-requirements-with-witness-interpreters.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/WitnessDetails.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/InterpreterLanguagesUtils.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DraftHearingRequirementsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateHearingRequirementsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/WitnessHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/WitnessInterpreterLanguagesDynamicListUpdater.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/WitnessesDraftMidEventHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/WitnessesUpdateMidEventHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/WitnessesService.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/InterpreterLanguagesUtilsTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CreateFlagHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DraftHearingRequirementsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RemoveWitnessCaseFlagsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateHearingRequirementsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/WitnessCaseFlagsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/WitnessInterpreterLanguageFlagsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/WitnessInterpreterLanguagesDynamicListUpdaterTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/WitnessesDraftMidEventHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/WitnessesServiceTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/WitnessesUpdateMidEventHandlerTest.java

[RIA-7922](https://tools.hmcts.net/jira/browse/RIA-7922)
- Got rid of `WITNESS_LIST_ELEMENT_N` collection of fields
- Added `isWitnessDeleted` property to `witnessDetails`
- Changed the logic to base itself of whether witnesses are being deleted or not

RIA-7792 Refactor of logic around witness related fields

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListEditCaseHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListEditCaseHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7978
Prevent edit case listing direction

RIA-7978 Prevent edit case listing direction appending

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/applyforcosts/ApplyForCostsMidEvent.java
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/RIA-7713
Added to applicationprops.yml and MidEvent new role Generic Home Office

RIA-7713 apply_for_costs: Add_generic_home_office_role

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RecordAdjournmentDetailsConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordAdjournmentDetailsStateHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RecordAdjournmentDetailsConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordAdjournmentDetailsStateHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7830

RIA-7830 trigger hearings api on record adjournment details event

---

src/functionalTest/resources/scenarios/RIA-6694-submit-appeal-by-admin.json
src/functionalTest/resources/scenarios/RIA-7444-start-appeal-internal-detained-ejp-case.json
src/functionalTest/resources/scenarios/RIA-7444-start-appeal-internal-detained-paper-form-case-not-ejp.json
src/functionalTest/resources/scenarios/RIA-7447-submit-appeal-by-admin-detained-ejp.json
src/functionalTest/resources/scenarios/RIA-7447-submit-appeal-by-admin-non-detained-ejp.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/HandlerUtils.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSubmittedConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryEditAppealHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealTypeHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HearingTypeHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeDecisionDateChecker.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/IsEjpHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LetterSentOrReceivedHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/NabaFeatureTogglePreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UploadAppealFormHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/FeesHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/HandlerUtilsTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSubmittedConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryEditAppealHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealTypeHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HearingTypeHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeDecisionDateCheckerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/IsEjpHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LetterSentOrReceivedHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/NabaFeatureTogglePreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UploadAppealFormHandlerTest.java

RIA-8888 Ejp journey naba rebase fix v2

---

src/functionalTest/resources/scenarios/RIA-7769-prepopulate-record-adjournment-details.json
src/functionalTest/resources/scenarios/RIA-7813-remove-witness-flags.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordAdjournmentDetailsMidEventHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordAdjournmentDetailsMidEventHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7769

RIA-7769 prepopulate record adjournment details

---

config/owasp/suppressions.xml

To fix NABA pipeline to build preview env

RIA-8888 Added CVE-2023-31582 suppression

---

infrastructure/main.tf

Update postgres flexible server db module name

DIAC-113 Update postgres flexible server db module name

---

src/functionalTest/resources/scenarios/RIA-7450-submit-ejp-transfer-down-appeal-by-admin-documents.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTag.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UploadEjpDocumentsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTagTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UploadEjpDocumentsHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7450
Added handler to handle EJPcase creation documents

RIA-7450 added handler to handle ejp case creation documents

---

charts/ia-case-api/Chart.yaml
config/owasp/suppressions.xml
infrastructure/main.tf
infrastructure/state.tf
infrastructure/variables.tf

add postgres 15 terraform module

DIAC-113 - add postgres 15 terraform module

---

charts/ia-case-api/Chart.yaml
config/owasp/suppressions.xml
infrastructure/main.tf
infrastructure/state.tf
infrastructure/variables.tf

add new terraform modeuls for ithc

DIAC-113 - add postgres 15 terraform module ithc

---

charts/ia-case-api/Chart.yaml
src/functionalTest/resources/scenarios/RIA-7803_oot_apply_for_costs_end_appeal.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ApplyForCosts.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/applyforcosts/ApplyForCostsConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendDecisionAndReasonsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/applyforcosts/ApplyForCostsFeatureTogglerPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/applyforcosts/ApplyForCostsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/ApplyForCostsAppender.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ApplyForCostsTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/applyForCosts/ApplyForCostsConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendDecisionAndReasonsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/applyforcosts/ApplyForCostsFeatureTogglerPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/applyforcosts/ApplyForCostsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/ApplyForCostsAppenderTest.java

https://tools.hmcts.net/jira/browse/RIA-7803
Late costs application - Out of time screen implementation, added new fields for OOT screen, unit tests, FT, updated sendDecisionAndReasons handler with the date the event is triggered.

RIA-7803 apply_for_costs_oot

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinitionTest.java

RIA-7668 - Update field

---

src/functionalTest/resources/scenarios/RIA-7450-submit-ejp-transfer-down-appeal-by-admin-documents.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UploadEjpDocumentsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UploadEjpDocumentsHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7450
Updated EJP file name

RIA-7450 Updated EJP file name

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateHearingRequirementsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateHearingRequirementsHandlerTest.java

[RIA-7837](https://tools.hmcts.net/jira/browse/RIA-7837)
- Made sure that ref data language (dynamic list) gets cleared if the complex type has a manual language, and vice versa made sure that manual language gets cleared if user did not choose to type language manually. This is necessary for case flags to update correctly.

RIA-7837 Sanitize appellant language complex types

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7734
Added new event to SendNotificationHandler and updated the test for it

RIA-7734 apply_for_costs_respondent_notification_v2

---

src/functionalTest/resources/scenarios/RIA-7481-review-add-audio-video-flag.json
src/functionalTest/resources/scenarios/RIA-7481-update-add-audio-video-flag.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/StrategicCaseFlagType.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HearingRequirementsAppellantFlagsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HearingRequirementsAppellantFlagsHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7481
- Added multimedia evidence flag if granted by legal officer
- Added unit test and functional test

RIA-7481 add multimedia evidence flag if granted by legal officer

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java

https://tools.hmcts.net/jira/browse/RIA-7661
Added code functionality and test scenarios

RIA-7661 Appeal transferred to the First-tier Tribunal - HO notification

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java

https://tools.hmcts.net/jira/browse/RIA-7929
Added missing HO notification and functional test scenarios

RIA-7929 Decision without a hearing - Existing HO notification

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateInterpreterDetailsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateInterpreterDetailsHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7963
RIA-7963 Update HMC when interpreter details event is triggered

RIA-7963 Update HMC when interpreter details event is triggered

---

.github/renovate.json
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/DIAC-2
Updating renovate config

DIAC-002 Updating renovate config

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7796
Added to SendNotificationHandler 'RespondToCosts' event

RIA-7796 respond_to_costs_applicant

---

Jenkinsfile_CNP
build.gradle
charts/ia-case-api/values.yaml
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/CcdCaseCreationTest.java
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/HearingsUpdateHearingRequestFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/RecordAdjournmentDetailsPreparerFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/RecordAdjournmentDetailsStateHandlerFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/util/IdamAuthProvider.java
src/functionalTest/resources/application-functional.yaml
src/functionalTest/resources/templates/start-appeal-aip.json
src/functionalTest/resources/templates/start-appeal-legalrep.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java

https://tools.hmcts.net/jira/browse/RIA-7977

RIA-7977 - Create functional tests for ia-case-api delegator to ia-hearings-api

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java

https://tools.hmcts.net/jira/browse/RIA-7942
Added event to internal events to handle list

RIA-7942 Force case to SHR

---

infrastructure/main.tf

Delete ia-case-api postgres flexible server

DIAC-113 delete ia-case-api postgres flexible server

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/applyforcosts/ApplyForCostsFeatureTogglerPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/applyforcosts/ApplyForCostsFeatureTogglerPreparerTest.java

https://tools.hmcts.net/jira/browse/RIA-7803
Added condition for Reinstated appeal status. If it presented then OOT screens should be hidden.

RIA-7803 oot_fix

---

infrastructure/main.tf
infrastructure/variables.tf

delete ia-case-api postgres flexible server in ITHC

DIAC-113 delete ia-case-api postgres flexible server in ITHC

---

infrastructure/main.tf
infrastructure/variables.tf

Add ia-case-api postgres flexible server in Demo

DIAC-113 Add ia-case-api postgres flexible server in Demo

---

infrastructure/main.tf

Add ia-case-api postgres flexible server in ITHC

DIAC-113 Add ia-case-api postgres flexible server in ITHC

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordAdjournmentDetailsMidEventHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordAdjournmentDetailsMidEventHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7769
RIA-7769 Fix HearingChannel and HearingLocation prepopulate.

RIA-7769 Fix HearingChannel and HearingLocation prepopulate.

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HearingsUpdateHearingRequest.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordAdjournmentDetailsPreparer.java

RIA-7994 - fix sonal check

---

.github/renovate.json

https://tools.hmcts.net/jira/browse/DIAC-2
Updating renovate config to exclude pact versions

DIAC-002 updating renovate JSON to exclude pact versions

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordAdjournmentDetailsMidEventHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordAdjournmentDetailsMidEventHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7768
RIA-7768 change HEARING_CENTER to LIST_CASE_HEARING_CENTRE when adjournment a hearing

RIA-7768 change HEARING_CENTER to LIST_CASE_HEARING_CENTRE when adjournment a hearing

---

.github/workflows/pr-title-validation.yml
build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/DIAC-173

DIAC-173 dependency fixes

---

config/owasp/suppressions.xml
src/functionalTest/resources/scenarios/RIA-7979-list-assist-integrated-location.json
src/functionalTest/resources/scenarios/RIA-7979-list-assist-unintegrated-location.json
src/functionalTest/resources/scenarios/RIA-7980-list-assist-integration-preparer-location-enabled-for-list-assist.json
src/functionalTest/resources/scenarios/RIA-7980-list-assist-integration-preparer-location-not-enabled-for-list-assist.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListAssistIntegratedHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListAssistIntegratedLocationsService.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListAssistIntegrationPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListAssistIntegratedHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListAssistIntegratedLocationsServiceTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListAssistIntegrationPreparerTest.java

https://tools.hmcts.net/jira/browse/RIA-7980

RIA-7980 Enable listAssistIntegration event only for list assist enabled hearing centres

---

config/owasp/suppressions.xml
infrastructure/main.tf

Remove ia-case-api postgres flexible server in AAT

DIAC-113 Remove ia-case-api postgres flexible server in AAT

---

infrastructure/main.tf

Add ia-case-api postgres flexible server terraform module

DIAC-113 Add ia-case-api postgres flexible server terraform module

---

infrastructure/main.tf

Retrigger roles and access generation

DIAC-113 - add force trigger for roles

---

config/owasp/suppressions.xml
src/functionalTest/resources/scenarios/RIA-7781-legal-rep-make-a-change-hearing-type-application.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/MakeAnApplicationTypes.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MakeAnApplicationMidEvent.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/MakeAnApplicationTypesProvider.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/MakeAnApplicationTypesTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MakeAnApplicationMidEventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/MakeAnApplicationTypesProviderTest.java

(https://tools.hmcts.net/jira/browse/RIA-7781)
- [x ] README and other documentation has been updated / added (if needed)
- [x ] tests have been updated / new tests has been added (if needed)

RIA-7781 - New Application type  Change hearing type

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordAdjournmentDetailsMidEventHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordAdjournmentDetailsMidEventHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7799
RIA-7799 Update cancellation reasons to use ref-data

RIA-7799 Update cancellation reasons to use ref-data

---

src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/RecordAdjournmentDetailsStateHandlerFunctionalTest.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordAdjournmentDetailsMidEventHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordAdjournmentDetailsMidEventHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7836
RIA-7836 Rename hearings cancellation/update reasons

RIA-7836 Rename hearings cancellation/update reasons

---

charts/ia-case-api/values.preview.template.yaml
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/controllers/advice/ErrorResponseLogger.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/controllers/advice/ErrorResponseLoggerTest.java

https://tools.hmcts.net/jira/browse/DIAC-78
Filter caseData logs and exclude them from error logs

DIAC-78 Exclude caseData from error response logs

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RecordAdjournmentDetailsConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HearingChannelsDynamicListUpdater.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RecordAdjournmentDetailsConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HearingChannelsDynamicListUpdaterTest.java

https://tools.hmcts.net/jira/browse/RIA-7771
RIA-7771 Fix hearingChannel initialization and confirmation message error

RIA-7771 Fix hearingChannel initialization and confirmation message error

---

charts/ia-case-api/Chart.yaml
charts/ia-case-api/values.yaml
src/main/resources/bootstrap.yaml

DIAC-113 Use postgres database version 15

DIAC-113 Switch to Postgres database v15

---

charts/ia-case-api/Chart.yaml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ReviewHearingRequirementsConfirmation.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ReviewHearingRequirementsConfirmationTest.java

https://tools.hmcts.net/jira/browse/RIA-7482
- added message and link in confirmation page when complete the "Hearing requirements" and "Update hearing adjustments" event
- added the unit test

RIA-7482 remind Legal Officer to add case flags after reviewing hearing requirements

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/RecordAdjournmentDetailsStateHandlerFunctionalTest.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordAdjournmentDetailsStateHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordAdjournmentDetailsStateHandlerTest.java

Jira link (if applicable)
https://tools.hmcts.net/jira/browse/RIA-8180
Change description
RIA-8180 Use a correct case state after adjourn a case.

RIA-8180 Use a correct case state after adjourn a case.

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/AutoHearingRequestService.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/AutoHearingRequestServiceTest.java

https://tools.hmcts.net/jira/browse/RIA-8346

RIA-8346 Auto hearing request feature toggle

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordAdjournmentDetailsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordAdjournmentDetailsHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8385

RIA-8385 Address issue with stale information not getting cleared

---

src/functionalTest/resources/scenarios/RIA-7983-review-hearing-requirements-about-to-start-event-auto-hearing-request-enabled.json
src/functionalTest/resources/scenarios/RIA-7983-review-hearing-requirements-auto-hearing-request-enabled.json
src/functionalTest/resources/scenarios/RIA-7984-list-case-without-hearing-hequirements-about-to-start-event-auto-hearing-request-enabled.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListCaseWithoutHearingRequirementsPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListCaseWithoutHearingRequirementsPreparerTest.java

https://tools.hmcts.net/jira/browse/RIA-7984

RIA-7984 Set hearing location when listing without requirements

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/HandlerUtils.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DecisionAndReasonsStartedPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListCaseWithoutHearingRequirementsPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordAdjournmentDetailsPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewDraftHearingRequirementsPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/HandlerUtilsTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DecisionAndReasonsStartedPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListCaseWithoutHearingRequirementsPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordAdjournmentDetailsPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewDraftHearingRequirementsPreparerTest.java

https://tools.hmcts.net/jira/browse/RIA-7985
- check and update autoHearingRequestEnable flag whether isAutoHearingRequestEnabled toggler is enabled or not
- apply these changes to "reviewHearingRequirements", "listCaseWithoutHearingRequirements", "recordAdjournmentDetails" and "decisionAndReasonsStarted" event
- Add the unit test

RIA-7985 list the case work allocation task is not created for List Assist hearing requests

---

Jenkinsfile_CNP
Jenkinsfile_nightly
Jenkinsfile_parameterized
bin/utils/idam-user-token-aat.sh
build.gradle
config/fortify-client.properties

https://tools.hmcts.net/jira/browse/DIAC-107

DIAC-107 turning fortify on

---

bin/utils/python_scripts/convert-json-to-txt.py
bin/utils/python_scripts/redact_info_from_json.py

https://tools.hmcts.net/jira/browse/DIAC-196
Adding additional fields for redacting script and also updating text converter script

DIAC-196 updating python scripts

---

src/functionalTest/resources/scenarios/RIA-7987-RIA-7988-review-hearing-requirements-auto-request-hearing-failed.json
src/functionalTest/resources/scenarios/RIA-7987-RIA-7988-review-hearing-requirements-auto-request-hearing-succeeded.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ReviewHearingRequirementsConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewDraftHearingRequirementsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ReviewHearingRequirementsConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewDraftHearingRequirementsHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7988

RIA-7988 Allow LO to decide whether to automatically request a hearing

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/MakeAnApplicationTypesProvider.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/MakeAnApplicationTypesProviderTest.java

https://tools.hmcts.net/jira/browse/RIA-8496
RIA-8496 Add change hearing type option to final bundling event for makeAnApplication

RIA-8496 Add change hearing type option to final bundling event for makeAnApplication

---

charts/ia-case-api/values.preview.template.yaml

Changed Preview env configuration for documents

RIA-1111 doc-fix

---

bin/utils/python_scripts/redact_info_from_json.py

https://tools.hmcts.net/jira/browse/DIAC-219
Added function to redact values from a CSV. Uses same fields as JSON redactor

DIAC-219 added CSV redactor

---

charts/ia-case-api/values.preview.template.yaml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/Parties.java

https://tools.hmcts.net/jira/browse/SNI-5296
Updating image policy to point to PR 373

DIAC-211 Updating parties class

---

src/contractTest/java/uk/gov/hmcts/reform/iacaseapi/consumer/refdata/LocationRefDataConsumerTest.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/refdata/LocationRefDataApi.java

[https://tools.hmcts.net/jira/browse/RIA-7983](https://tools.hmcts.net/jira/browse/RIA-7983)
- Swap `service-code` parameter name for `service_code`

RIA-7983 Fix service code parameter name

---

Jenkinsfile_CNP
Jenkinsfile_nightly
Jenkinsfile_parameterized
build.gradle
charts/ia-case-api/Chart.yaml
charts/ia-case-api/values.preview.template.yaml
charts/ia-case-api/values.yaml
config/owasp/suppressions.xml
docker-pactbroker-compose.yml

https://tools.hmcts.net/jira/browse/DIAC-228

DIAC-228 dependency and fortify fixes

---

config/owasp/suppressions.xml

RIA-2222 suppressions_fix

---

charts/ia-case-api/Chart.yaml
infrastructure/main.tf
src/functionalTest/resources/scenarios/RIA-8102-decide-ftpa-application-appellant-granted-mid-event.json
src/functionalTest/resources/scenarios/RIA-8102-decide-ftpa-application-appellant-reheard-rule35-mid-event.json
src/functionalTest/resources/scenarios/RIA-8102-decide-ftpa-application-respondent-granted-mid-event.json
src/functionalTest/resources/scenarios/RIA-8102-decide-ftpa-application-respondent-reheard-rule35-mid-event.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/FtpaResidentJudgeDecisionOutcomeType.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ResidentJudgeFtpaDecisionConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DecideFtpaApplicationMidEvent.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ResidentJudgeFtpaDecisionHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpperTribunalBundlePreparer.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ResidentJudgeFtpaDecisionConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DecideFtpaApplicationMidEventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaDecisionMidEventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ResidentJudgeFtpaDecisionHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpperTribunalBundlePreparerTest.java

https://tools.hmcts.net/jira/browse/RIA-8102
RIA-8102 create new DecideFtpaApplication event

RIA-8102 create new DecideFtpaApplication event

---

Jenkinsfile_CNP
src/functionalTest/resources/scenarios/RIA-8116-ftpa-appellant-in-time-submit-ftpa-list.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/FtpaApplications.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/FtpaDecisionCheckValues.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaAppellantHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaMigrateLegacyDataHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaRespondentHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ResidentJudgeFtpaDecisionHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/FtpaDisplayService.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaAppellantHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaMigrateLegacyDataHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaRespondentHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ResidentJudgeFtpaDecisionHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/FtpaDisplayServiceTest.java

https://tools.hmcts.net/jira/browse/RIA-8116
FTPA tab content update

RIA-8116 FTPA tab content update

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ResidentJudgeFtpaDecisionConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ResidentJudgeFtpaDecisionHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/FtpaDisplayService.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ResidentJudgeFtpaDecisionConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ResidentJudgeFtpaDecisionHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/FtpaDisplayServiceTest.java

https://tools.hmcts.net/jira/browse/RIA-8104
RIA-8104 Create Rule32 and 31

RIA-8104 Create Rule32 and 31

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8184
Added DECIDE_FTPA_APPLICATION to SendNotificationHandler, updated tests.

RIA-8184 ftpa_rule_31_32

---

infrastructure/main.tf

https://tools.hmcts.net/jira/browse/DIAC-158
decommission postgress v11

DIAC-158 - decommission postgress v11

---

src/functionalTest/resources/scenarios/RIA-8104-decide-ftpa-application-appellant-reheard-rule31-mid-event.json
src/functionalTest/resources/scenarios/RIA-8104-decide-ftpa-application-appellant-reheard-rule32-mid-event.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/FtpaApplications.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ResidentJudgeFtpaDecisionHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/FtpaDisplayService.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ResidentJudgeFtpaDecisionHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/FtpaDisplayServiceTest.java

https://tools.hmcts.net/jira/browse/RIA-8104
RIA-8104 Add new ftpaDecisionRemadeRule32TextArea field and show conditions

RIA-8104 Add new ftpaDecisionRemadeRule32TextArea field and show conditions

---

charts/ia-case-api/values.preview.template.yaml
infrastructure/main.tf

https://tools.hmcts.net/jira/browse/RIA-7925
Updated preview env configuration

RIA-7925 - Updated preview env configuration

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/FtpaApplications.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/FtpaDisplayService.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/FtpaDisplayServiceTest.java

https://tools.hmcts.net/jira/browse/RIA-8109
Added rule 35 data to ftpaList

RIA-8109 Added rule 35 data to ftpaList

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/FtpaDisplayService.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/FtpaDisplayServiceTest.java

https://tools.hmcts.net/jira/browse/RIA-8109
Added additional fields for rule 35

RIA-8109 Added additional fields for rule 35

---

charts/ia-case-api/values.preview.template.yaml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ResidentJudgeFtpaDecisionHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/FtpaDisplayService.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ResidentJudgeFtpaDecisionHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/FtpaDisplayServiceTest.java

https://tools.hmcts.net/jira/browse/RIA-8107
FTPA decided Rule 35 Overview tab

RIA-8107 FTPA decided Rule 35 Overview tab

---

Jenkinsfile_nightly

https://tools.hmcts.net/jira/browse/DIAC-236

DIAC-236 splitting tests into separate stages

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DecideFtpaApplicationMidEvent.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DecideFtpaApplicationMidEventTest.java

https://tools.hmcts.net/jira/browse/RIA-8622
Removed AIP reheardRule35 and remadeRule32 validation

RIA-8622 Removed AIP reheardRule35 and remadeRule32 validation

---

charts/ia-case-api/values.preview.template.yaml

https://tools.hmcts.net/jira/browse/RIA-8199
Added environment var to show event history on AIP

RIA-8199 Added environment var to show event history on AIP

---

src/functionalTest/resources/scenarios/RIA-8157-updateTribunalDecision-rule-31.json
src/functionalTest/resources/scenarios/RIA-8157-updateTribunalDecisionDocument-rule-31-error.json
src/functionalTest/resources/scenarios/RIA-8157-updateTribunalDecisionDocument-rule-31-normal.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateTribunalDecisionDocumentUploadRule31MidEvent.java

https://tools.hmcts.net/jira/browse/RIA-8157
- fix [the problem of sonarCloud](https://sonarcloud.io/project/issues?resolved=false&severities=BLOCKER%2CCRITICAL%2CMAJOR%2CMINOR&sinceLeakPeriod=true&types=BUG&pullRequest=1911&id=IACASEAPI&open=AY3u8-yRKs5QsniWP2iL)

RIA-8157 fix the code smell problem v2

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryEditAppealHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/NabaFeatureTogglePreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryEditAppealHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/NabaFeatureTogglePreparerTest.java

RIA-7892 Added handlers to use the feature toggle for ADA screens

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HearingChannelsDynamicListUpdater.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordAdjournmentDetailsMidEventHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordAdjournmentDetailsPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/CommonRefDataDynamicListProvider.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/RefDataUserService.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HearingChannelsDynamicListUpdaterTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordAdjournmentDetailsMidEventHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordAdjournmentDetailsPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/CommonRefDataDynamicListProviderTest.java

https://tools.hmcts.net/jira/browse/RIA-8612

RIA-8612 Fix issue with 'nextHearingFormat' field during 'recordAdjournmentDetails' event

---

charts/ia-case-api/values.preview.template.yaml

RIA-1111 fix_image_name

---

charts/ia-case-api/Chart.yaml
charts/ia-case-api/values.preview.template.yaml

Chart update for preview environment for Aip frontend Refund

RIA-1112 chart_update_for_aip_refund_preview

---

charts/ia-case-api/Chart.yaml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8243
Update Tribunal Decision R31 Notification

RIA-8243 Update Tribunal Decision R31 Notification

---

charts/ia-case-api/values.preview.template.yaml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/HelpWithFeesOption.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/RemissionOption.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/PaymentStateHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/PaymentStateHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8050
RIA-8050 modify appeal status when dlrmFeeRemission is activated and appeal has remission

RIA-8050 modify appeal status when dlrmFeeRemission is activated and appeal has remission

---

src/functionalTest/resources/scenarios/RIA-8110-decide-ftpa-application-record-appellant-reheardRule35.json
src/functionalTest/resources/scenarios/RIA-8110-decide-ftpa-application-record-respondent-reheardRule35.json
src/functionalTest/resources/scenarios/RIA-8116-decide-ftpa-application-record-appellant-reheardRule35.json
src/functionalTest/resources/scenarios/RIA-8116-decide-ftpa-application-record-respondent-reheardRule35.json
src/functionalTest/resources/scenarios/RIA-8116-migration-decideFtpaApplication-appellant-with-legacy-started-and-older-decision-reheardRule35.json
src/functionalTest/resources/scenarios/RIA-8116-migration-decideFtpaApplication-respondent-with-legacy-started-and-older-decision-reheardRule35.json
src/functionalTest/resources/scenarios/RIA-8158-updateTribunalDecision-rule-32.json

https://tools.hmcts.net/jira/browse/RIA-8731
Workaround for converting 3 different judges exclude fields into one

RIA-8731 Workaround applied

---

charts/ia-case-api/Chart.yaml
config/owasp/suppressions.xml

Update chart version for master pipeline.

RIA-TASK - Update chart

---

src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/CcdScenarioRunnerTest.java
src/functionalTest/resources/scenarios/RIA-2208-add-case-note-to-admin-officer.json
src/functionalTest/resources/scenarios/RIA-5292-add-payment-request-sent-case-note-to-admin-officer.json

https://tools.hmcts.net/jira/browse/DIAC-281

DIAC-281 fixing CcdScenarioRunnerTest

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateTribunalAppealDecisionRule31.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateTribunalAppealDecisionRule31Test.java

https://tools.hmcts.net/jira/browse/RIA-8157
Update to clear data in "summarise the changes made...." section

RIA-8157 Update tribunal decision data clear

---

bin/utils/python_scripts/filepath_settings.py

Adding extra fields to redactor

DIAC-219 adding extra fields to be redacted

---

src/functionalTest/resources/scenarios/RIA-8253-mark-appeal-as-remitted.json

Updated field id for remitted functional test

RIA-8257 Updated field id for remitted functional test

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/MarkAppealAsRemittedConfirmation.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/MarkAppealAsRemittedConfirmationTest.java

RIA-8253 Fix minor text changes for the confirmation body

---

charts/ia-case-api/values.preview.template.yaml
src/functionalTest/resources/scenarios/RIA-8253-mark-appeal-as-remitted.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/SourceOfRemittal.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MarkAppealAsRemittedUploadDecisionHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MarkAppealAsRemittedUploadDecisionHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8257
Added remitted case note

RIA-8257 Added remitted case note

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/SourceOfRemittal.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MarkAppealAsRemittedUploadDecisionHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8257
Updated Court of Appeal enum value

RIA-8257 Updated Court of Appeal enum value

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/State.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MarkAppealAsRemittedUploadDecisionHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/StateTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MarkAppealAsRemittedUploadDecisionHandlerTest.java

- Updated handler to populate fields required for Overview tab.

RIA-8254 Added state 'remitted'

---

config/owasp/suppressions.xml
src/functionalTest/resources/scenarios/RIA-8158-8219-updateTribunalDecision-rule-32.json
src/functionalTest/resources/scenarios/RIA-8220-8219-update-tribunal-decision-rule32.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateTribunalDecisionHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateTribunalDecisionHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8763
Added reheard internal flag to unlock rule32 path
Loop is fully tested to **decided** state after
Based on https://github.com/hmcts/ia-case-api/pull/2027, so 2027 needs to be merged first.

RIA-8763 Added reheard internal flag to unlock rule32 path

---

charts/ia-case-api/values.preview.template.yaml
config/owasp/suppressions.xml
src/functionalTest/resources/scenarios/RIA-8158-8219-updateTribunalDecision-rule-32.json
src/functionalTest/resources/scenarios/RIA-8220-8219-update-tribunal-decision-rule32.json
src/functionalTest/resources/scenarios/RIA-8239-updateTribunalDecision-rule-31-list.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTag.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateTribunalDecisionHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTagTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateTribunalDecisionHandlerTest.java

Merging refund with dlrm branches

RIA-1111 merge_dlrm

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/MarkPaymentPaidPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/MarkPaymentPaidPreparerTest.java

https://tools.hmcts.net/jira/browse/RIA-8062
RIA-8062 Update Mark appeal as paid logic to handle appeals with aip fee remission

RIA-8062 Update Mark appeal as paid logic to handle appeals with aip fee remission

---

charts/ia-case-api/values.preview.template.yaml

For testing definitions import issue

RIA-TASK - Update preview definition store api to use older image

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/RIA-8678
RIA-8678 Suppress vulnerability

RIA-8678 Suppress vulnerability

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MarkAppealAsRemittedUploadDecisionHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MarkAppealAsRemittedUploadDecisionHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8290
Reheard appeal - Reheard appeal - event refactor

RIA-8290 - Reheard appeal - event refactor

---

build.gradle

https://tools.hmcts.net/jira/browse/DIAC-352

DIAC-352 dependency fix

---

charts/ia-case-api/Chart.yaml
charts/ia-case-api/values.preview.template.yaml
config/owasp/suppressions.xml
src/functionalTest/resources/scenarios/RIA-3129-create-case-summary-for-reheard.json
src/functionalTest/resources/scenarios/RIA-8772-create-case-summary-for-reheard-remitted.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ReheardHearingDocuments.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CreateCaseSummaryHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MarkAppealAsRemittedUploadDecisionHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ReheardHearingDocumentsTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CreateCaseSummaryHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MarkAppealAsRemittedUploadDecisionHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8772
Added remitted reheard document complex collections

RIA-8772 Added remitted reheard document complex collections

---

config/owasp/suppressions.xml
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/CcdScenarioRunnerTest.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestFeeRemissionAipPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestFeeRemissionAipPreparerTest.java

https://tools.hmcts.net/jira/browse/RIA-8077
Refund requested - AiP notification

RIA-8077 refund requested notification aip

---

charts/ia-case-api/Chart.yaml
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/util/MapValueExpander.java
src/functionalTest/resources/scenarios/RIA-7714_ho_respond_to_costs.json
src/functionalTest/resources/scenarios/RIA-7715_ho_adds_evidence_to_costs.json
src/functionalTest/resources/scenarios/RIA-7715_legalrep_adds_evidence_to_costs.json
src/functionalTest/resources/scenarios/RIA-7716_judge_decide_apply_for_costs.json
src/functionalTest/resources/scenarios/RIA-7717-consider-making-new-costs-confirmation.json
src/functionalTest/resources/scenarios/RIA-7717-consider-making-new-costs-start.json
src/functionalTest/resources/scenarios/RIA-7717-consider_making_costs_submit.json

RIA-TASK - Fix failed functional tests

---

charts/ia-case-api/Chart.yaml

Upgrade XUI chart for unassigned task completion issue

RIA-TASK - Upgrade xui chart version 

---

src/functionalTest/resources/scenarios/RIA-2239-judge-end-appeal.json
src/functionalTest/resources/scenarios/RIA-3039-end-appeal-state-saved-for-reinstate.json
src/functionalTest/resources/scenarios/RIA-3302-ho-notifications-for-end-appeal-with-appeal-submitted-co.json
src/functionalTest/resources/scenarios/RIA-3763-update-hearing-requirements-case-officer-single-requirements-exist.json
src/functionalTest/resources/scenarios/RIA-3763-update-hearing-requirements-single-requirements-exist.json
src/functionalTest/resources/scenarios/RIA-3763-update-reheard-hearing-requirements-multiple-requirements-exist.json
src/functionalTest/resources/scenarios/RIA-3763-update-reheard-hearing-requirements-single-requirements-exist.json
src/functionalTest/resources/scenarios/RIA-4293-persisted-fields-update-representative-details.json
src/functionalTest/resources/scenarios/RIA-7337-RIA-7340-RIA-2031-update-hearing-requirements.json
src/functionalTest/resources/scenarios/RIA-7337-RIA-7340-RIA-7507-update-hearing-requirements-with-sign-language-interpreter.json
src/functionalTest/resources/scenarios/RIA-7337-RIA-7340-RIA-7507-update-hearing-requirements-with-spoken-language-interpreter.json
src/functionalTest/resources/scenarios/RIA-7337-RIA-7340-review-hearing-requirements-create-hearing-loop-and-wheelchair-access-flags.json
src/functionalTest/resources/scenarios/RIA-7635-Update-interpreter-details-confirmation.json
src/functionalTest/resources/scenarios/RIA-7699-Update-interpreter-booking-status-confirmation.json
src/functionalTest/resources/scenarios/RIA-7744-end-appeal-requires-manual-hearing-cancellation-confirmation.json
src/functionalTest/resources/scenarios/RIA-7769-prepopulate-record-adjournment-details.json
src/functionalTest/resources/scenarios/RIA-7813-remove-witness-flags.json
src/functionalTest/resources/scenarios/RIA-7979-list-assist-integrated-location.json
src/functionalTest/resources/scenarios/RIA-7979-list-assist-unintegrated-location.json
src/functionalTest/resources/scenarios/RIA-7983-review-hearing-requirements-about-to-start-event-auto-hearing-request-enabled.json
src/functionalTest/resources/scenarios/RIA-7984-list-case-without-hearing-hequirements-about-to-start-event-auto-hearing-request-enabled.json
src/functionalTest/resources/scenarios/RIA-7986-list-case-without-hearing-requirements-automatically-failed.json
src/functionalTest/resources/scenarios/RIA-7986-list-case-without-hearing-requirements-automatically-succeeded.json
src/functionalTest/resources/scenarios/RIA-7987-RIA-7988-review-hearing-requirements-auto-request-hearing-failed.json
src/functionalTest/resources/scenarios/RIA-7987-RIA-7988-review-hearing-requirements-auto-request-hearing-succeeded.json
src/functionalTest/resources/scenarios/RIA-8014-record-adjournment-details-auto-hearing-request-confirmation.json
src/functionalTest/resources/scenarios/RIA-8115-set-float-suitability-on-case-when-adjourning-on-day-of-hearing.json
src/functionalTest/resources/scenarios/RIA-823-end-appeal.json
src/functionalTest/resources/scenarios/RIA-8449-restore-state-from-adjourn-auto-request-hearing-failed.json
src/functionalTest/resources/scenarios/RIA-8449-restore-state-from-adjourn-auto-request-hearing-succeeded.json

- Disable snl functional tests

RIA-TASK Disable snl functional tests

---

charts/ia-case-api/values.preview.template.yaml

https://tools.hmcts.net/jira/browse/RIA-8259
- ia-aip-frontend PR 1116 updated for preview

RIA-8259 Updating image PR for ia-aip-frontend

---

charts/ia-case-api/values.preview.template.yaml

Updated payment preview env PR

RIA-8888 Updated payment preview env PR

---

src/functionalTest/resources/scenarios/RIA-8256-clear-mark-appeal-as-remitted-about-to-start.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MarkAppealAsRemittedPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MarkAppealAsRemittedPreparerTest.java

https://tools.hmcts.net/jira/browse/RIA-8256
Preparer to clear remitted data after a loop

RIA-8256 Clear remitted data

---

charts/ia-case-api/values.preview.template.yaml

Added links for Notifications and Documents api's preview env. services.

RIA-1111 update_preview_env_links

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/RemissionDetails.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestFeeRemissionAipPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestFeeRemissionAipPreparerTest.java

https://tools.hmcts.net/jira/browse/RIA-8086
RIA-8086 rename localAuthorityLetter to match ccd definitions

RIA-8086 rename localAuthorityLetter to match ccd definitions

---

charts/ia-case-api/Chart.yaml
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/HoursMinutes.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListCasePreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListCaseWithoutHearingRequirementsPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordAdjournmentDetailsMidEventHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestNewHearingRequirementsDirectionHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewDraftHearingRequirementsPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/HoursMinutesTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListCasePreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordAdjournmentDetailsMidEventHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestNewHearingRequirementsDirectionHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewDraftHearingRequirementsPreparerTest.java

[https://tools.hmcts.net/jira/browse/RIA-8811](https://tools.hmcts.net/jira/browse/RIA-8811)
- Change `listCaseHearingLength` to `listingLength` for integrated cases

RIA-8811 listingLength field

---

build.gradle
charts/ia-case-api/values.preview.template.yaml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTag.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSubmittedConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/GenerateServiceRequestMakeAPaymentConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RecordRemissionDecisionConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateServiceRequestPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendDecisionAndReasonsMidEventHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTagTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSubmittedConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/GenerateServiceRequestMakeAPaymentConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RecordRemissionDecisionConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateServiceRequestPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendDecisionAndReasonsMidEventHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ServiceRequestHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8609

RIA-8609 - Cherry picked from f68bad1e 03/04/2024 to 36a02261 11/04/2024

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/field/Document.java

RIA-TASK - Remove duplicated annotation

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/LocationRefDataService.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/model/refdata/CourtVenue.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/LocationRefDataServiceTest.java

[RIA-8841](https://tools.hmcts.net/jira/browse/RIA-8841)
- Filtered ref data locations by `isHearingLocation` and `courtStatus` attributes
- ### Checklist

RIA-8841 Filter locations

---

charts/ia-case-api/Chart.yaml
charts/ia-case-api/values.preview.template.yaml

--
Changed link to image for AiP to 1038

RIA-1122 change_link_for_aip

---

charts/ia-case-api/Chart.yaml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/MakeAnApplicationTypesProvider.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/MakeAnApplicationTypesProviderTest.java

RIA-8807 Make an application event in the Remitted state

---

Jenkinsfile_CNP
Jenkinsfile_nightly
Jenkinsfile_parameterized
charts/ia-case-api/values.preview.template.yaml

RIA-8860 merge_master

---

charts/ia-case-api/values.preview.template.yaml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealTypeHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealTypeHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8867
- [x ] tests have been updated / new tests has been added (if needed)

RIA-8867 - Fix isOutOfCountryEnabled field missing on AIP cases

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/HandlerUtils.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListCasePreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/HandlerUtilsTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListCasePreparerTest.java

[RIA-8782](https://tools.hmcts.net/jira/browse/RIA-8782)
- Added `listingLocation` to LIST_CASE

RIA-8782 Add listingLocation to ListCase

---

charts/ia-case-api/Chart.yaml
charts/ia-case-api/values.preview.template.yaml

RIA-TASK - Deploy bails to preview

RIA-TASK - Deploy bails to preview

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/MakeAnApplicationTypes.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MakeAnApplicationMidEvent.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/MakeAnApplicationTypesProvider.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/MakeAnApplicationTypesTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MakeAnApplicationMidEventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/MakeAnApplicationTypesProviderTest.java

https://tools.hmcts.net/jira/browse/RIA-8901
Updated Application under rule 31 or rule 32 value

RIA-8901 Updated Application under rule 31 or rule 32 value

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/HearingCentre.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListEditCaseHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListEditCaseHandlerTest.java

[RIA-8782](https://tools.hmcts.net/jira/browse/RIA-8782)
- Made `listCaseHearingCentre` remain aligned with `listingLocation`

RIA-8782 Maintain listingLocation aligned with listCaseHearingCentre

---

src/functionalTest/resources/scenarios/RIA-8782-list-case-about-to-start-listing-location-from-ref-data.json
src/functionalTest/resources/scenarios/RIA-8782-list-case-submit-with-listing-location-from-ref-data.json
src/functionalTest/resources/scenarios/RIA-8783-edit-case-listing-about-to-start-listing-location-from-ref-data.json
src/functionalTest/resources/scenarios/RIA-8783-edit-case-listing-submit-with-listing-location-from-ref-data.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EditCaseListingPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EditCaseListingPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListEditCaseHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8783

RIA-8783 Refactor "Edit case listing" to use location reference data

---

.github/renovate.json
.github/workflows/pr-title-validation.yml
Jenkinsfile_CNP
Jenkinsfile_nightly
Jenkinsfile_parameterized
bin/utils/idam-user-token-aat.sh
bin/utils/python_scripts/prep_import_data.py
bin/utils/python_scripts/redact_info_from_json.py
bin/utils/python_scripts/tests.py
build.gradle
charts/ia-case-api/Chart.yaml
charts/ia-case-api/values.preview.template.yaml
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/RIA-8934
RIA-8934 Update configuration files with master values

RIA-8934 Update configuration files with master values

---

Jenkinsfile_CNP
charts/ia-case-api/values.preview.template.yaml

- point the dmn branch to master as well.

RIA-TASK update preview env with up to date service PRs.

---

.github/workflows/pr-title-validation.yml
bin/utils/idam-user-token-aat.sh
bin/utils/python_scripts/prep_import_data.py
bin/utils/python_scripts/redact_info_from_json.py
bin/utils/python_scripts/tests.py
build.gradle
charts/ia-case-api/values.preview.template.yaml
config/owasp/suppressions.xml
src/functionalTest/resources/scenarios/RIA-8291-generate-reheard-hearing-bundle-remitted.json

RIA-TASK update remitted branch for master release

---

charts/ia-case-api/Chart.yaml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/HearingsUpdateHearingRequestConfirmation.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/HearingsUpdateHearingRequestConfirmationTest.java

https://tools.hmcts.net/jira/browse/RIA-8936
- set the new confirmation header in green box
- update the unit test

RIA-8936 auto update hearing request failure screen

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/StartAppealMidEvent.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/StartAppealMidEventTest.java

https://tools.hmcts.net/jira/browse/RIA-8377
Test coverage fix

RIA-8377 test_coverage

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/StartAppealMidEvent.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/StartAppealMidEventTest.java

https://tools.hmcts.net/jira/browse/RIA-8377
Fixed address validation occurs only for an admin.

RIA-8377 fixed_address_for_legalrep_validation

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/RIA-8286
Updated refund branch for WA DMNs

RIA-8286 Updated refund branch for WA DMNs

---

charts/ia-case-api/values.preview.template.yaml

Reverted image to point to latest.

RIA-TASK - Update values.preview.template.yaml

---

charts/ia-case-api/Chart.yaml
charts/ia-case-api/values.preview.template.yaml
charts/ia-case-api/values.yaml

Fix timed-event-service on preview

RIA-TASK - Fix timed-event-service on preview

---

charts/ia-case-api/values.preview.template.yaml
src/functionalTest/resources/scenarios/RIA-3734-RIA-7879-case-listing-belfast-hearing-venue.json
src/functionalTest/resources/scenarios/RIA-7879-case-listing-harmondsworth-hearing-venue.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/BaseLocation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/HearingCentre.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DeriveHearingCentreHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListEditCaseHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/HearingCentreFinder.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/LocationRefDataService.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/model/refdata/CourtVenue.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/utils/StaffLocation.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/BaseLocationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/HearingCentreTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DeriveHearingCentreHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListEditCaseHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/LocationRefDataServiceTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/utils/StaffLocationTest.java

https://tools.hmcts.net/jira/browse/RIA-8787

RIA-8787 Store epimsid of designated hearing centre on case submission

---

config/owasp/suppressions.xml
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/RIA-8061
Due to timed element to this ticket, need to update the time interval to be reasonable to allow for QA testing.
Changing to 2 mins

RIA-8061 updating minutes for testing on preview

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/StartAppealMidEvent.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/StartAppealMidEventTest.java

https://tools.hmcts.net/jira/browse/RIA-9111
Changed 'fixed' to 'postal' address

RIA-9111 fixed_address

---

src/functionalTest/resources/scenarios/RIA-8721-updateTribunalDecision-rule-31-updated-decision-allowed.json
src/functionalTest/resources/scenarios/RIA-8721-updateTribunalDecision-rule-31-updated-decision-dismissed.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateTribunalDecisionHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateTribunalDecisionHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8276
Added rule 31 decision check updated

RIA-8276 Added rule 31 decision check updated

---

charts/ia-case-api/values.preview.template.yaml
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/RIA-8061
Preview environment testing has been completed, changing minutes back to 7 days.

RIA-8061 - Preview testing completed - reverting time to match AC

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EndAppealHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EndAppealHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-9118

RIA-9118 Some refactoring for error handling in 'End appeal' handler

---

charts/ia-case-api/Chart.yaml
charts/ia-case-api/values.preview.template.yaml
charts/ia-case-api/values.yaml

Deploy timed-event-service to preview

RIA-TASK - Deploy timed-event-service on preview

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java

https://tools.hmcts.net/jira/browse/RIA-8320
Change description
Appeal fee changed(Additional payment required) - Non Detained (by post) notification

RIA-8320 letter notification internal update fee

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTag.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealWasNotSubmittedSupportingDocumentsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTagTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealWasNotSubmittedSupportingDocumentsHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8931
Added supporting documents save to Legal rep category.

RIA-8931 add_supporting_documents

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EditAppealAfterSubmitHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EditAppealAfterSubmitHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8326
RIA-8326 Allow edit after submit for OOC appeals

RIA-8326 Allow edit after submit for OOC appeals

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSubmittedConfirmation.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSubmittedConfirmationTest.java

https://tools.hmcts.net/jira/browse/RIA-9114
Changed image link for an Admin OOT case. Fixed test.

RIA-9114 change_oot_image_link

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealWasNotSubmittedSupportingDocumentsHandler.java

https://tools.hmcts.net/jira/browse/RIA-8931
Fixed supporting documents duplication issue in the documents tab.

RIA-8931 duplication_removal

---

Jenkinsfile_CNP
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/CcdScenarioRunnerTest.java

DIAC-489 - ignore functionals to deploy change

---

Jenkinsfile_CNP
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/CcdScenarioRunnerTest.java

Reverts hmcts/ia-case-api#2185

Revert "DIAC-489 - ignore functionals to deploy change"

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AdditionalInstructionsMidEventHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AdditionalInstructionsMidEventHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-9156

RIA-9156 Clear 'additional instruction' in relevant events when not required

---

src/functionalTest/resources/scenarios/RIA-2957-RIA-2959-RIA-3712-adjourn-without-a-date.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java

https://tools.hmcts.net/jira/browse/RIA-8344
Appeal remitted from the UT/CoA

RIA-8344 - Appeal remitted from the UT/CoA

---

config/owasp/suppressions.xml
src/functionalTest/resources/scenarios/RIA-9191-list-assist-integration-handler-update-witness-names.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListAssistIntegrationHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/WitnessNamesUpdateService.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/WitnessDetailsTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListAssistIntegrationHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/WitnessNamesUpdateServiceTest.java

https://tools.hmcts.net/jira/browse/RIA-9191

RIA-9191 Update witness names during 'List assist integration event'

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java

https://tools.hmcts.net/jira/browse/RIA-8333
Added event.DecideFtpaApplication to internal SendNOtificationHandler method

RIA-8333 add_decide_ftpa_application

---

bin/import-dmn-diagram.sh
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTag.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordOutOfTimeDecisionHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTagTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordOutOfTimeDecisionHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8306
late appeal can proceed - Non Detained & OOC(by post) notification

RIA-8306 late appeal can proceed letter

---

bin/import-bpmn-diagram.sh
bin/import-dmn-diagram.sh
bin/import-wa-bpmn-diagram.sh
bin/utils/organisational-role-assignment.sh

DIAC-123 for fixing pipeline PRs

---

src/functionalTest/resources/scenarios/RIA-8921-set-next-hearing-date-on-list-case-event-integrated.json
src/functionalTest/resources/scenarios/RIA-8922-set-next-hearing-date-on-edit-case-listing-event-integrated.json
src/functionalTest/resources/scenarios/RIA-8958-set-next-hearing-date-on-edit-case-listing-event-non-integrated.json
src/functionalTest/resources/scenarios/RIA-8958-set-next-hearing-date-on-list-case-event-non-integrated.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/NextHearingDetails.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListEditCaseHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/NextHearingDateService.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListEditCaseHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/NextHearingDateServiceTest.java

https://tools.hmcts.net/jira/browse/RIA-8921
- Set next hearing date during list case (RIA-8921)
- Set next hearing date during edit case listing (RIA-8922)

RIA-8921 Set next hearing date

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AddBaseLocationFromHearingCentreForOldCasesFixHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AddBaseLocationFromHearingCentreForOldCasesFixHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-9208
fix cml field null error
- [ x] tests have been updated / new tests has been added (if needed)

RIA-9208 - fix cml field null error

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AddBaseLocationFromHearingCentreForOldCasesFixHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AddBaseLocationFromHearingCentreForOldCasesFixHandlerTest.java

RIA-9208 - fix test

---

charts/ia-case-api/Chart.yaml
src/functionalTest/resources/scenarios/RIA-7507-submit-hearing-requirements-with-interpreter-sign-language.json
src/functionalTest/resources/scenarios/RIA-7507-submit-hearing-requirements-with-interpreter-spoken-language.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/InterpreterLanguagesUtils.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DraftHearingRequirementsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateHearingRequirementsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/InterpreterLanguagesUtilsTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DraftHearingRequirementsHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-9211
Fix for Interpreter language stored incorrectly
- [ x] tests have been updated / new tests has been added (if needed)

RIA-9211 - Fix for Interpreter language stored incorrectly

---

Jenkinsfile_CNP
Jenkinsfile_nightly
Jenkinsfile_parameterized
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/CcdScenarioRunnerTest.java
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/util/AuthorizationHeadersProvider.java
src/functionalTest/resources/scenarios/RIA-9152-aria-create-case-about-to-submit.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AriaCreateCaseHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CreateMigratedCasePreparer.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AriaCreateCaseHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-9152
Added ariaCreateCase event handler

RIA-9152 Added ariaCreateCase event handler

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/LocationRefDataService.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/model/refdata/CourtVenue.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/LocationRefDataServiceTest.java

https://tools.hmcts.net/jira/browse/RIA-8786
Add court location filter when fetching ref data CML so that Crown House and Arnhem House won't be returned.
- [ x] tests have been updated / new tests has been added (if needed)

RIA-8786 - Add court location filter

---

src/functionalTest/resources/scenarios/RIA-8969-progress-migrated-case-desired-state.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/migratedcase/ProgressMigratedCaseHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/migratedcase/ProgressMigratedCaseHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8969
Changed ABOUT_TO_START to ABOUT_TO_SUBMIT, added FT for ProgressMigratedCaseHandler.class

 RIA-8969 changed_callbackStage_to_submit

---

charts/ia-case-api/values.preview.template.yaml
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/RIA-8345
- Preview env var value added

RIA-8345 Adding env var to preview for time interval 1 min

---

src/contractTest/java/uk/gov/hmcts/reform/iacaseapi/consumer/roleassignment/RoleAssignmentApiConsumerTest.java
src/functionalTest/resources/scenarios/RIA-8921-set-next-hearing-date-on-list-case-event-integrated.json
src/functionalTest/resources/scenarios/RIA-8922-set-next-hearing-date-on-edit-case-listing-event-integrated.json
src/functionalTest/resources/scenarios/RIA-8958-set-next-hearing-date-on-edit-case-listing-event-non-integrated.json
src/functionalTest/resources/scenarios/RIA-8958-set-next-hearing-date-on-list-case-event-non-integrated.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/InterpreterLanguagesUtils.java

https://tools.hmcts.net/jira/browse/RIA-9201
fix npe when hearing requirement is submitted

RIA-9201 - fix npe when hearing requirement is submitted

---

src/functionalTest/resources/scenarios/RIA-9193-progress-migrated-case-HMC-mid-event.json
src/functionalTest/resources/scenarios/RIA-9193-progress-migrated-case-MoveIt-mid-event.json
src/functionalTest/resources/scenarios/RIA-9193-progress-migrated-case-VHH-mid-event.json
src/functionalTest/resources/scenarios/RIA-9193-progress-migrated-case-VHHToCCD-mid-event.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/MigrateAriaCasesDocumentUploaderConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MigrateAriaCasesDocumentUploaderMidEvent.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/MigrateAriaCasesDocumentUploaderConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MigrateAriaCasesDocumentUploaderMidEventTest.java

https://tools.hmcts.net/jira/browse/RIA-9193
RIA-9193 Add migrate aria documents screen

RIA-9193 Add migrate aria documents screen

---

charts/ia-case-api/values.preview.template.yaml
src/contractTest/java/uk/gov/hmcts/reform/iacaseapi/consumer/roleassignment/RoleAssignmentApiConsumerTest.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTag.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTagTest.java

RIA-9242 Fix callback error on createCaseSummary event
RIA-9242 Fix callback error on createCaseSummary event

RIA-9242 Fix callback error on createCaseSummary event

---

src/functionalTest/resources/scenarios/RIA-7657-review-add-witness-interpreter.json
src/functionalTest/resources/scenarios/RIA-7657-update-witness-interpreter.json
src/functionalTest/resources/scenarios/RIA-7658-review-add-witness-interpreter.json
src/functionalTest/resources/scenarios/RIA-7658-update-witness-interpreter.json
src/functionalTest/resources/scenarios/RIA-7813-remove-witness-flags.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RemoveWitnessCaseFlagsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/WitnessInterpreterLanguageFlagsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RemoveWitnessCaseFlagsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/WitnessInterpreterLanguageFlagsHandlerTest.java

- Interpreter language flag is not created or updated for witnesses in non-integrated cases
https://tools.hmcts.net/jira/browse/RIA-9244

RIA-9244 Refactor Auto Interpreter language flag creation/update

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/MigrateAriaCasesDocumentUploaderConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MigrateAriaCasesDocumentUploaderMidEvent.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/MigrateAriaCasesDocumentUploaderConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MigrateAriaCasesDocumentUploaderMidEventTest.java

https://tools.hmcts.net/jira/browse/RIA-9193
Sonar cloud fixes

RIA-9193 sonar cloud fix

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/PaymentStateHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/PaymentStateHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-9197
Added check to PaymentStateHandler for paid appeals to change their state to 'appealSubmitted'

RIA-9197 add check to paymentStateHandler to change state

---

charts/ia-case-api/values.preview.template.yaml
src/main/resources/application.yaml

Make Update Tribunal decision event available to LO
Make Update Tribunal decision event available to LO

RIA-9130 Make Update Tribunal decision event available to LO

---

Jenkinsfile_CNP
Jenkinsfile_nightly
Jenkinsfile_parameterized
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/CcdScenarioRunnerTest.java
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/util/AuthorizationHeadersProvider.java
src/functionalTest/resources/scenarios/RIA-8919-set-next-hearing-date-integrated.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListEditCaseHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/NextHearingDateHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListEditCaseHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/NextHearingDateHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8919

RIA-8919 Set next hearing date event - integrated

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/HandlerUtils.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ChangeHearingCentreHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DeriveHearingCentreHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListEditCaseHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/HandlerUtilsTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ChangeHearingCentreHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DeriveHearingCentreHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListEditCaseHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8798
Case list can be filtered on the case management location
- [x ] tests have been updated / new tests has been added (if needed)

RIA-8798 - Case list can be filtered on the case management location

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ChangeHearingCentreHandler.java

fix glasgow no email address found error when Change hearing centre

RIA-9260 - fix glasgow no email

---

src/functionalTest/resources/scenarios/RIA-8919-set-next-hearing-date-integrated.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/NextHearingDateHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/NextHearingDateHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-9262

RIA-9262 Update eventid of 'Set next hearing date'

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListEditCaseHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListEditCaseHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-9265
Fix for Change hearing centre event Locations list not matching after listing

RIA-9265 - Fix for Change hearing centre event Locations list not matching after listing

---

src/functionalTest/resources/scenarios/RIA-8980-set-next-hearing-date-non-integrated.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/NextHearingDateHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/NextHearingDateHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8980

RIA-8980 Set next hearing date event - non-integrated

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AutomaticInternalSendPaymentReminderTrigger.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AutomaticInternalSendPaymentReminderTriggerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8366
- Scheduling timed event for new event Send Payment Reminder Notification, 7 days after submit appeal

RIA-8366 Timed event for event Send Payment Reminder

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ChangeHearingCentreHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ChangeHearingCentreHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-9269
Fix for Change hearing centre not updating new ref data cml field

RIA-9269 - Fix for Change hearing centre not updating new ref data cml field

---

src/functionalTest/resources/scenarios/RIA-8975-add-is-aria-migrated-no.json
src/functionalTest/resources/scenarios/RIA-9152-aria-create-case-about-to-submit.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/migratedcase/AriaCreateCaseHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/migratedcase/StartAppealCreateCaseHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/migratedcase/AriaCreateCaseHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/migratedcase/StartAppealCreateCaseHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8975
Added isAriaMigratedFilter for case lister filtering

RIA-8975 Added isAriaMigratedFilter for case lister filtering

---

charts/ia-case-api/Chart.yaml
src/functionalTest/resources/scenarios/RIA-8969-progress-migrated-case-desired-state.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-9154
Update PROGRESS_MIGRATED_CASE to send a Notification

RIA-9154 - Update PROGRESS_MIGRATED_CASE to send a Notification

---

src/functionalTest/resources/scenarios/RIA-9238-refundConfirmation-confirmation.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RefundConfirmationConfirmation.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RefundConfirmationConfirmationTest.java

https://tools.hmcts.net/jira/browse/RIA-9238
- Adding confirmation screen for completing of new 'refundConfirmation' event
- Added unit test for this class

RIA-9238 Refund confirmation event confirmation screen

---

src/functionalTest/resources/scenarios/RIA-3792-manage-fee-update-of-refund-approved.json
src/functionalTest/resources/scenarios/RIA-3795-manage-fee-update-of-additional-fee-requested.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateServiceRequestPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdateHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RefundConfirmationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateServiceRequestPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdateHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RefundConfirmationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-9213
Added changes to allow 2nd service request where a full refund is processed because of change in decision type.

RIA-9213 second_service_request

---

charts/ia-case-api/values.preview.template.yaml
charts/ia-case-api/values.yaml

https://tools.hmcts.net/jira/browse/RIA-9214
Update preview values for fees-register service

RIA-9214 fee_register

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdateHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdateHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-9218
Add previously selected and updated(selected in manage fee update event) hearing options fields. Necessary for notifications text.

RIA-9218 add_hearing_fields

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryEditAppealHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DetentionFacilityEditAppealHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryEditAppealHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DetentionFacilityEditAppealHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-9225
Edit Appeal - In Country -> OOC

RIA-9225 - Edit Appeal - In Country -> OOC

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EditAppealAfterSubmitHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EditAppealAfterSubmitHandlerTest.java

See [RIA-9236](https://tools.hmcts.net/jira/browse/RIA-9236)
RIA-9236 Clear LR fields for internal cases and appellant representation

RIA-9236 Clear LR fields for internal cases and appellant representation

---

Jenkinsfile_CNP
src/functionalTest/resources/scenarios/RIA-9152-aria-create-case-about-to-submit.json
src/functionalTest/resources/scenarios/RIA-9458-aria-create-case-about-to-submit-missing-due-days-error.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/migratedcase/AriaCreateCaseHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/controllers/PreSubmitCallbackController.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/migratedcase/AriaCreateCaseHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-9458
Added aria migration task due day validation

RIA-9458 Added aria migration task due day validation

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8249
https://tools.hmcts.net/jira/browse/RIA-8250
- Enabling Document Generation for ia-case-api
- Document to be sent for Manage Fee update

RIA-8250 RIA-8249 Enabling document generation for Manage fee update for ia-case-api

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EditAppealAfterSubmitHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EditAppealAfterSubmitHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-9235
Fixed typo for appellantsRepresentation

RIA-9235 fix_typo

---

build.gradle
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryEditAppealHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DetentionFacilityEditAppealHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryEditAppealHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DetentionFacilityEditAppealHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8403
Revert changes from https://tools.hmcts.net/jira/browse/RIA-9225

RIA-8403 - Move Detained code to new Branch

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HearingCancelledHandler.java

https://tools.hmcts.net/jira/browse/RIA-9485

RIA-9485 Refactor handler for substantive hearing cancellation

---

build.gradle
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppellantPhoneNumberValidator.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppellantPhoneNumberValidatorTest.java

See [DIAC-575](https://tools.hmcts.net/jira/browse/DIAC-575)

DIAC-575 adding validation mid event for appellant phone number

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/FeesHelper.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/FeesHelperTest.java

https://tools.hmcts.net/jira/browse/RIA-9523
Fixed manageFeeUpdateHelper and its test

RIA-9523 bug_fix

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/HandlerUtils.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdateMidEvent.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordRemissionDecisionPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/MarkPaymentPaidPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/PaymentStateHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/HandlerUtilsTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdateMidEventTest.java

https://tools.hmcts.net/jira/browse/RIA-9527
Fixed case FEE_REMISSION_CHANGED conditions in ManageFeeUpdateMidEvent, added and edited junit tests.

RIA-9527 bug_fix

---

charts/ia-case-api/Chart.yaml
src/functionalTest/resources/scenarios/RIA-7458-edit-appeal-after-submit-detained-ejp-case.json

Disabled "RIA-7458 Edit appeal after submit - Detained EJP case'" FT for EJP cases

RIA-1111 ft_test_disable

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdateHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdateHandlerTest.java

See [RIA-9522](https://tools.hmcts.net/jira/browse/RIA-9522)
RIA-9522 Persist previous amountGbp and update fees

RIA-9522 Persist previous amountGbp and update fees

---

charts/ia-case-api/values.preview.template.yaml

DIAC-123 fixing hardcoded test password fortify flag

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryEditAppealHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EditAppealAfterSubmitHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryEditAppealHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EditAppealAfterSubmitHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-9237
OOC Edit appeal post submission - Ability to edit LR details
Also ensure rest of flow is as expected

RIA-9237 - OOC Edit appeal post submission - Ability to edit LR details

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdateHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdateHandlerTest.java

See [RIA-9542](https://tools.hmcts.net/jira/browse/RIA-9542)
RIA-9542 Persist previous amountGbp and update fees for feeTribunalAc…

RIA-9542 Persist previous amountGbp and update fees for feeTribunalAction cases

---

Jenkinsfile_CNP
charts/ia-case-api/values.preview.template.yaml

DIAC-123 fixing WA issue

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ServiceRequestHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ServiceRequestHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-9552
Removed AIP check for generate service request

RIA-9552 Removed AIP check for generate service request

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateServiceRequestPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateServiceRequestPreparerTest.java

https://tools.hmcts.net/jira/browse/RIA-9554
Make generate service request available for additional payment

RIA-9554 Make generate service request available for additional payment

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestNewHearingRequirementsDirectionHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestNewHearingRequirementsDirectionHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-9452
Remove preivously commited changes(commit-revert).

RIA-9452 commit_revert

---

Jenkinsfile_CNP
charts/ia-case-api/values.preview.template.yaml

DIAC-123 fixing enable_tes config

---

charts/ia-case-api/Chart.yaml

DIAC-123 adding TES to charts

---

charts/ia-case-api/values.preview.template.yaml
src/main/resources/application.yaml

Changed time duration for 1 minute

RIA-8366 change_time_for_QA

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/FeesHelper.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/FeesHelperTest.java

https://tools.hmcts.net/jira/browse/RIA-9564
Updated FeesHelper class, so it is not saving feeAmount(it is saving when we are paying the fees in the payments)

RIA-9654 bug_fix

---

src/functionalTest/resources/scenarios/RIA-3271-3628-home-office-response-for-appeal-submitted.json
src/functionalTest/resources/scenarios/RIA-3332-home-office-integration-flag-set-mark-appeal-paid.json
src/functionalTest/resources/scenarios/RIA-3332-home-office-response-for-appeal-submitted-mark-appeal-paid.json
src/functionalTest/resources/scenarios/RIA-3390-home-office-integration-flag-set.json
src/functionalTest/resources/scenarios/RIA-4116-ho-notification-eligible-flag-appeal-submitted.json

N/A
Disable functional tests to fix master pipeline

DIAC-000 Disable functional tests to fix master pipeline

---

src/functionalTest/resources/scenarios/RIA-8921-set-next-hearing-date-on-list-case-event-integrated.json
src/functionalTest/resources/scenarios/RIA-8922-set-next-hearing-date-on-edit-case-listing-event-integrated.json
src/functionalTest/resources/scenarios/RIA-8958-set-next-hearing-date-on-edit-case-listing-event-non-integrated.json
src/functionalTest/resources/scenarios/RIA-8958-set-next-hearing-date-on-list-case-event-non-integrated.json

See [RIA-9573](https://tools.hmcts.net/jira/browse/RIA-9573)
RIA-9573 fix FT for hearings

RIA-9573 fix FT for hearings

---

src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/CcdCaseCreationTest.java
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/HearingsUpdateHearingRequestFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/RecordAdjournmentDetailsPreparerFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/RecordAdjournmentDetailsStateHandlerFunctionalTest.java
src/functionalTest/resources/scenarios/RIA-8921-set-next-hearing-date-on-list-case-event-integrated.json
src/functionalTest/resources/scenarios/RIA-8922-set-next-hearing-date-on-edit-case-listing-event-integrated.json
src/functionalTest/resources/scenarios/RIA-8958-set-next-hearing-date-on-edit-case-listing-event-non-integrated.json
src/functionalTest/resources/scenarios/RIA-8958-set-next-hearing-date-on-list-case-event-non-integrated.json

https://tools.hmcts.net/jira/browse/RIA-9569
Remove disabled annotation from FT tests

RIA-2222 Remove disabled annotation from FT

---

src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/CcdCaseCreationTest.java
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/HearingsUpdateHearingRequestFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/RecordAdjournmentDetailsPreparerFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/RecordAdjournmentDetailsStateHandlerFunctionalTest.java
src/functionalTest/resources/templates/start-appeal-aip.json
src/functionalTest/resources/templates/start-appeal-legalrep.json

https://tools.hmcts.net/jira/browse/RIA-9569
Testing FT changes

RIA-1111 ft_test

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/MarkPaymentPaidPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/MarkPaymentPaidPreparerTest.java

https://tools.hmcts.net/jira/browse/RIA-9583
Edited MarkPaymentPaidPreparer and MarkPaymentPaidPreparerTest for NO_REMISSION path. As well refactored the classes.

RIA-9583 no_remission_path

---

charts/ia-case-api/values.preview.template.yaml

Fixing bails case api image policy

DIAC-528 fixing bail image values

---

charts/ia-case-api/values.preview.template.yaml

See [DIAC-528](https://tools.hmcts.net/jira/browse/DIAC-528)
Updating Location Ref Data URL endpoint

DIAC-528 Updating Location Ref Data url

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealWasNotSubmittedSupportingDocumentsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/migratedcase/StartAppealCreateCaseHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/MarkPaymentPaidPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeDecisionDateCheckerTest.java

Fix sonar maintainability issues

RIA-TASK Fix sonar maintainability issues

---

src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/CcdCaseCreationTest.java
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/HearingsUpdateHearingRequestFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/RecordAdjournmentDetailsPreparerFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/RecordAdjournmentDetailsStateHandlerFunctionalTest.java

RIA-1234 ft_issues

---

src/functionalTest/resources/templates/start-appeal-aip.json
src/functionalTest/resources/templates/start-appeal-legalrep.json

 RIA-1235 add_template_changes

---

src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/CcdCaseCreationTest.java

 RIA-1236 ft_fix

---

src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/CcdCaseCreationTest.java
src/functionalTest/resources/templates/start-appeal-aip.json
src/functionalTest/resources/templates/start-appeal-legalrep.json

RIA-4567 fix_v4

---

src/functionalTest/resources/templates/start-appeal-aip.json
src/functionalTest/resources/templates/start-appeal-legalrep.json

RIA-4567 ft_fix_v5

---

src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/HearingsUpdateHearingRequestFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/RecordAdjournmentDetailsPreparerFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/RecordAdjournmentDetailsStateHandlerFunctionalTest.java

RIA-1234 disabling FT test

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordRemissionDecisionStateHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordRemissionDecisionStateHandlerTest.java

https://tools.hmcts.net/jira/browse/DIAC-678
Fix "Service Request" tab error on appeals with remission decision "rejected" to allow Legal representatives to make payment.

DIAC-678 Fix record remission decision errors

---

bin/utils/python_scripts/es_dlq_scripts/process-es-dlq-files-extract-unique-cases.py

https://tools.hmcts.net/jira/browse/DIAC-661
Add python script to extract cases records from ES DLQ files

DIAC-661 Add script to extract cases records from ES DLQ files

---

Jenkinsfile_CNP
Jenkinsfile_nightly
Jenkinsfile_parameterized
charts/ia-case-api/Chart.yaml
charts/ia-case-api/values.preview.template.yaml
charts/ia-case-api/values.yaml
docker-compose.yml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/StoredNotification.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SaveNotificationsToDataHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/AsylumCaseNotificationApiSender.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/config/GovNotifyConfiguration.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/StoredNotificationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SaveNotificationsToDataHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/AsylumCaseNotificationApiSenderTest.java

Reverts hmcts/ia-case-api#2420

DIAC-546 Revert "DIAC-546 Revert "DIAC-546 new event to pull notification data given a notification ID""

---

Jenkinsfile_CNP
Jenkinsfile_nightly
Jenkinsfile_parameterized
charts/ia-case-api/Chart.yaml
charts/ia-case-api/values.preview.template.yaml
charts/ia-case-api/values.yaml
docker-compose.yml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/StoredNotification.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SaveNotificationsToDataHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/AsylumCaseNotificationApiSender.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/config/GovNotifyConfiguration.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/StoredNotificationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SaveNotificationsToDataHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/AsylumCaseNotificationApiSenderTest.java

Reverts hmcts/ia-case-api#2431

DIAC-546 - Revert DIAC-546 new event to pull notification data given a notification ID"

---

Jenkinsfile_CNP
bin/utils/idam-user-token-aat.sh
charts/ia-case-api/values.preview.template.yaml

https://tools.hmcts.net/jira/browse/DIAC-692 
Fix fortify issues for idam script

DIAC-692 Fix fortify issue in script

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SaveNotificationsToDataHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SaveNotificationsToDataHandlerTest.java

DIAC-706 - feature flag the save notification code

---

bin/utils/idam-user-token-aat.sh

RIA-9634 Update to remove hardcoded secret from script
RIA-9634 Update to remove hardcoded secret from script

RIA-9634 Update to remove hardcoded secret from script

---

build.gradle
charts/ia-case-api/Chart.yaml

DIAC-000 Upgrade charts

---

build.gradle

NA
Revert build.gradle changes

DIAC-000 Revert build.gradle changes

---

bin/add-roles.sh
charts/ia-case-api/values.preview.template.yaml
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/DIAC-649
Add robot user config for robot user role

DIAC-649 Add case note event for robot user

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RemoveRepresentationPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RemoveRepresentationPreparerTest.java

https://tools.hmcts.net/jira/browse/DIAC-854
Fix organisation policy validation in remove representative event

DIAC-854 fix organisation policy validation in remove representative event

---

charts/ia-case-api/Chart.yaml

DIAC-000 Upgrade java chart and servicebus chart

---

README-CALLBACKS.md

Create readme for the callbacks

---

charts/ia-case-api/values.preview.template.yaml

Revert WA changes in values.preview.template.yaml file

DIAC-681 Revert preview template changes

---

charts/ia-case-api/values.preview.template.yaml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/PaymentStateHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/PaymentStateHandlerTest.java

https://tools.hmcts.net/jira/browse/DIAC-970
SubmitAppeal event to set PA appeals' state to Appeal submitted.

DIAC-970 PA appeals state

---

.github/workflows/pr-title-validation.yml
Jenkinsfile_CNP
charts/ia-case-api/values.preview.template.yaml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/PaymentStateHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/PaymentStateHandlerTest.java

https://tools.hmcts.net/jira/browse/DIAC-1057
EA, HU and EU appeals state should be pending payment state until the payment is successful or remission request is approved.

DIAC-1057 Fix AiP HU EA EU appeals state

---

config/owasp/suppressions.xml
src/functionalTest/resources/scenarios/DIAC-898-edit-appeal-from-detained-to-out-of-country.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryEditAppealHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryEditAppealHandlerTest.java

https://tools.hmcts.net/jira/browse/DIAC-898
Clearing down detention fields when case is changed to an out of country appeal

DIAC-898 Detained Appeal Tab - LR Journey

---

src/integrationTest/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/DbAppealReferenceNumberGeneratorIntegrationTest.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealReferenceNumberHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/migratedcase/AriaCreateCaseHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/AppealReferenceNumberGenerator.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/DbAppealReferenceNumberGenerator.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealReferenceNumberHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/migratedcase/AriaCreateCaseHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/DbAppealReferenceNumberGeneratorTest.java

https://tools.hmcts.net/jira/browse/DIAC-1100
DIAC-1100 Detained appeals HMCTS reference generated with DE -  logic removed, test updated and some no longer required tests removed

DIAC-1100 Detained appeals DE reference

---

charts/ia-case-api/values.preview.template.yaml

DIAC-864 preview update to have latest hearings api image
DIAC-864 preview update to have latest hearings api image

DIAC-864 preview update to have latest hearings api image

---

infrastructure/main.tf

DIAC-688 - fix pipeline

---

Jenkinsfile_CNP
src/functionalTest/resources/scenarios/DIAC-976-set-detained-individual-flag-by-when-detained-appeal-submitted.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/StrategicCaseFlagType.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DetainedIndividualFlagHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DetainedIndividualFlagHandlerTest.java

https://tools.hmcts.net/jira/browse/DIAC-976
Adding case flag when appellant in detention

DIAC-976 Adding case flag when appellant in detention

---

charts/ia-case-api/Chart.yaml

DIAC-0000 Update Chart.yaml

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AnonymousByDefaultHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DetainedIndividualFlagHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/FlagHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/FlagHandlerTest.java

Fix sonar duplication issues for detained appeals branch

DIAC-9999 Fix sonar duplication issues for detained appeals branch

---

build.gradle

DIAC-1144 Fix pipelines failures

---

src/functionalTest/resources/scenarios/DIAC-976-set-detained-individual-flag-by-when-detained-appeal-submitted.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DetainedIndividualFlagHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DetainedIndividualFlagHandlerTest.java

https://tools.hmcts.net/jira/browse/DIAC-976
Fixing flag not showing bug.  Party (appellant name) not added so the UI didn't render it.

DIAC-976 fixing flag bug

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryEditAppealHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeDecisionDateChecker.java

https://tools.hmcts.net/jira/browse/DIAC-963
DIAC-963 Detained Appeal Label ICC Journey -  clear OutOfCountryCircumstances to fix in country submit

DIAC-963 Detained Appeal Label ICC Journey 

---

bin/add-roles.sh

DIAC-000 fix-preview-roles - add next-hearing-date-admin

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RemoveDetainedStatusHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RemoveDetainedStatusHandlerTest.java

https://tools.hmcts.net/jira/browse/DIAC-1130
Updating tabs to show detention removal status

DIAC-1130 Updating tabs to show detention removal status

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/StartAppealMidEvent.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/StartAppealMidEventTest.java

https://tools.hmcts.net/jira/browse/DIAC-1413
DIAC-1413 Clear Custodial Sentence for Bail Page
Test performed locally

DIAC-1413 Clear Custodial Sentence for Bail Page

---

src/functionalTest/resources/scenarios/DIAC-1141-set-detained-individual-flag-by-when-detained-appeal-marked-as-detained.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DetainedEditAppealHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MarkAppealAsDetainedHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DetainedEditAppealHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MarkAppealAsDetainedHandlerTest.java

https://tools.hmcts.net/jira/browse/DIAC-1312
fixing data clearing on edit appeal

DIAC-1312 fixing data clearing on edit appeal

---

src/functionalTest/resources/scenarios/DIAC-1160-update-case-appellant-in-person-manual-has-rep-details-start-error.json
src/functionalTest/resources/scenarios/DIAC-1160-update-case-appellant-in-person-manual-is-admin-error.json
src/functionalTest/resources/scenarios/DIAC-1160-update-case-appellant-in-person-manual-is-admin-start-error.json
src/functionalTest/resources/scenarios/DIAC-1237-update-case-appellant-in-person-manual-case-officer-start.json
src/functionalTest/resources/scenarios/DIAC-1237-update-case-appellant-in-person-manual-has-rep-details-start-error.json
src/functionalTest/resources/scenarios/DIAC-1237-update-case-appellant-in-person-manual-start.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SetCaseAsUnrepresentedHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SetCaseAsUnrepresentedHandlerTest.java

https://tools.hmcts.net/jira/browse/DIAC-1237
DIAC-1237 New Event - Update a case to AiP (Detained) - isAdmin set to YES Removed in SetCaseAsUnrepresentedHandler as now set in AiP Manual Event
Locally testing has been completed successfully

DIAC-1237 New Event - Update a case to AiP (Detained)

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RetriggerWaTasksForFixedCaseIdHandler.java

https://tools.hmcts.net/jira/browse/DIAC-1352
Fixing 1 potential race condition - Case 3 in the Jira Ticket

DIAC-1352 ia-case-api bugs to resolve - Case 3

---

charts/ia-case-api/values.preview.template.yaml
src/functionalTest/resources/scenarios/RIA-8970-substantive-hearings-can-be-manually-marked-as-cancelled-integrated.json
src/functionalTest/resources/scenarios/RIA-8970-substantive-hearings-can-be-manually-marked-as-cancelled-non-integrated.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/HearingCancelledConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/HearingCancelledConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

https://tools.hmcts.net/jira/browse/DIAC-1341
DIAC-1341 Cancellation of Production Notice Detained - HEARING_CANCELLED added to SendNotificationHandler, postNotificationSender removed from HearingCancelledConfirmation, tests updated
Unit test updated, this will be tested in Preview

DIAC-1341 Cancellation of Production Notice Detained 5

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/FeesHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeesHandlerTest.java

https://tools.hmcts.net/jira/browse/DIAC-1618
Duplicate notifications sent to IRCs/Prisons after editing and submitting a remission appeal

DIAC-1618 clearing payment status

---

src/main/resources/application-hc-mapping.yaml

https://tools.hmcts.net/jira/browse/DIAC-1614
Mapping Swinderby

DIAC-1614 Mapping Swinderby
