src/functionalTest/resources/scenarios/RIA-610-user-details-added-to-case.json
src/functionalTest/resources/templates/minimal-appeal-submitted.json

legalRepresentativeName updated to "A Legal Rep" as per AAT test user data

updated test data: legalRepresentativeName changed to be in line with AAT

---

src/functionalTest/resources/scenarios/RIA-893-send-home-office-evidence-direction.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-893

RIA-893 Send Home Office evidence direction

---

src/functionalTest/resources/scenarios/RIA-722-send-respondent-review-direction.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-722
Send the "respondent review direction" to the respondent as a notification.
```
[ ] Yes
[X] No
```

RIA-722 Send respondent review direction

---

src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/util/MapFieldAssertor.java
src/functionalTest/resources/scenarios/RIA-385-request-hearing-requirements.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-842
Send the hearing requirements direction to legal rep.
```
[ ] Yes
[X] No
```

RIA-842 Send legal rep hearing requirements direction

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AddAppealResponseHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AddAppealResponseHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RespondentReviewAppealResponseAddedUpdaterTest.java

Fix for the RespondentReviewAppealResponseAdded flag
```
[ ] Yes
[X] No
```

[PREVIEW] AddAppealResponseHandler must execute early

---

src/functionalTest/resources/application-functional.yaml
src/functionalTest/resources/scenarios/RIA-941-generate-hearing-ready-bundle.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCase.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseBuilder.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/State.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/DecisionAndReasonsStartedConfirmation.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/StateTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/DecisionAndReasonsStartedConfirmationTest.java

Ria 574 start descions and reasons

---

src/functionalTest/resources/scenarios/RIA-1152-&-1153-generate-decision-and-reasons.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/GenerateDecisionAndReasonsConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppellantNameForDisplayFormatter.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DecisionAndReasonsGeneratedSubStateProgression.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DecisionAndReasonsStartedSubStateProgression.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/GenerateDecisionAndReasonsConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DecisionAndReasonsGeneratedSubStateProgressionTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DecisionAndReasonsStartedSubStateProgressionTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandlerTest.java

Ria 1152 & 1153 generate decision and reasons

---

.gitignore
Dockerfile
Jenkinsfile_CNP
build.gradle
charts/ia-case-api/Chart.yaml
charts/ia-case-api/requirements.yaml
charts/ia-case-api/values.preview.template.yaml
charts/ia-case-api/values.yaml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/State.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/HearingCentreFinder.java
src/main/resources/application.yaml
src/main/resources/bootstrap.yaml

https://tools.hmcts.net/jira/browse/RIA-1493
See Jira
```
[ ] Yes
[x] No
```

RIA-1538 Aks and Helm Charts

---

Jenkinsfile_CNP
src/functionalTest/resources/scenarios/RIA-1152-&-1153-generate-decision-and-reasons.json
src/functionalTest/resources/scenarios/RIA-941-generate-hearing-ready-bundle.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/SendDecisionAndReasonsConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendDecisionAndReasonsPreventer.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/SendDecisionAndReasonsConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendDecisionAndReasonsPreventerTest.java

Ria 1154 send decision and reasons

---

src/functionalTest/resources/scenarios/RIA-575-add-case-note-to-existing-case-notes.json
src/functionalTest/resources/scenarios/RIA-575-add-first-case-note.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/CaseNote.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AddCaseNoteConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AddCaseNoteHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/CaseNoteAppender.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/CaseNoteTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AddCaseNoteConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AddCaseNoteHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/CaseNoteAppenderTest.java

Ria 575 add case note

---

src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/DataFixingTest.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AsylumCaseDataFixingHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/AsylumFieldNameFixer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/DataFixer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/config/AsylumCaseDataConfiguration.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AsylumCaseDataFixingHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/AsylumFieldNameFixerTest.java

RIA-1642: Added functional test
RIA-1642: Functional test
RIA-1642: More unit tests test
```
[ ] Yes
[ ] No
```

RIA-1642: Fixing data

---

src/functionalTest/resources/scenarios/RIA-1603-upload-addendum-evidence-action-available.json
src/functionalTest/resources/scenarios/RIA-1603-upload-addendum-evidence-confirmation.json
src/functionalTest/resources/scenarios/RIA-1603-upload-addendum-evidence-submit.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTag.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentWithMetadata.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/UploadAddendumEvidenceConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UploadAddendumEvidenceActionAvailableUpdater.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UploadAddendumEvidenceHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/DocumentReceiver.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTagTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/UploadAddendumEvidenceConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UploadAddendumEvidenceActionAvailableUpdaterTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UploadAddendumEvidenceHandlerTest.java

[RIA-1603](https://tools.hmcts.net/jira/browse/RIA-1603)
adding addendum evidence + unit tests + functional tests
```
[ ] Yes
[x] No
```

RIA-1603 addendum evidence + unit tests

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/UserRole.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CurrentCaseStateUpdater.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/UserRoleTest.java

[RIA-1568](https://tools.hmcts.net/jira/browse/RIA-1568)
See Jira
```
[ ] Yes
[x] No
```

Ria 1568 overview tab list case

---

Jenkinsfile_CNP
README.md
build.gradle
docker-pactbroker-compose.yml
src/contractTest/java/uk/gov/hmcts/reform/iacaseapi/IdamConsumerTest.java

https://tools.hmcts.net/jira/browse/RIA-1495
See jira
```
[ ] Yes
[x] No
```

Ria 1495 pact testing

---

README.md
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/CcdScenarioRunnerTest.java
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/util/AuthorizationHeadersProvider.java
src/functionalTest/resources/scenarios/RIA-412-RIA-1571-hearing-notice-docmosis-disabled.json
src/functionalTest/resources/scenarios/RIA-412-RIA-1571-hearing-notice-docmosis-enabled.json
src/functionalTest/resources/scenarios/RIA-412-RIA-1571-list-case-confirmation.json
src/functionalTest/resources/scenarios/RIA-412-RIA-1571-list-case-start.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ListCaseConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CurrentCaseStateUpdater.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ListCaseConfirmationTest.java

[RIA-1571](https://tools.hmcts.net/jira/browse/RIA-1571)
branch based on RIA-1568
list case by admin
```
[ ] Yes
[x] No
```

Ria 1571 list case from admin role

---

Jenkinsfile_CNP
build.gradle
charts/ia-case-api/values.yaml
src/functionalTest/resources/application-functional.yaml
src/functionalTest/resources/scenarios/RIA-362-edit-case-listing-confirmation.json
src/functionalTest/resources/scenarios/RIA-362-edit-case-listing-docmosis-disabled.json
src/functionalTest/resources/scenarios/RIA-362-edit-case-listing-docmosis-enabled.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/EditCaseListingConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/EditCaseListingConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandlerTest.java

Ria 362 edit case listing

---

charts/ia-case-api/values.yaml

https://tools.hmcts.net/jira/browse/RIA-1653
```
[ ] Yes
[x] No
```

RIA-1653-update-helm-docker-images

---

src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/DataFixingTest.java
src/functionalTest/resources/scenarios/RIA-572-record-attendees-and-duration.json
src/integrationTest/java/uk/gov/hmcts/reform/iacaseapi/component/RecordAttendeesAndDurationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/iacaseapi/component/testutils/IaCaseApiClient.java
src/integrationTest/java/uk/gov/hmcts/reform/iacaseapi/component/testutils/fixtures/PostSubmitCallbackResponseForTest.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/HoursAndMinutes.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/HearingAttendeesAndDurationRecordedConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordAttendeesAndDurationHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/AsylumCaseValueInitializerFixer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/config/AsylumCaseDataConfiguration.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/HearingAttendeesAndDurationRecordedConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DecisionAndReasonsStartedSubStateProgressionTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordAttendeesAndDurationHandlerTest.java

Ria 572 record attendees and duration

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AppealDecision.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AppealDecisionTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/HoursAndMinutesTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandlerTest.java

[RIA-1622](https://tools.hmcts.net/jira/browse/RIA-1622)
overview pages
```
[ ] Yes
[x] No
```

Ria 1622 overview pages decided

---

Jenkinsfile_CNP
Jenkinsfile_nightly
Jenkinsfile_parameterized

As required by CNP team
```
[ ] Yes
[ ] No
```

Removing deprecated pipeline features

---

build.gradle
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

[RIA-1610](https://tools.hmcts.net/jira/browse/RIA-1610)
See Jira
```
[ ] Yes
[x] No
```

Ria 1610 notify case officer

---

src/functionalTest/resources/scenarios/RIA-823-end-appeal.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EndAppealHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EndAppealHandlerTest.java

[RIA-1766](https://tools.hmcts.net/jira/browse/RIA-1766)
end appeal flags
```
[ ] Yes
[x] No
```

RIA-1766 end appeal flags

---

src/functionalTest/resources/scenarios/RIA-1485-record-granted-withdraw-application-confirmation.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSubmittedConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RecordApplicationConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EndAppealHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RecordApplicationConfirmationTest.java

[RIA-1562](https://tools.hmcts.net/jira/browse/RIA-1562)
Launch end appeal from application
```
[ ] Yes
[x] No
```

RIA-1562 Launch end appeal from overview tab

---

src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/CcdScenarioRunnerTest.java
src/functionalTest/resources/scenarios/RIA-362-RIA-1673-edit-case-listing-docmosis-disabled.json
src/functionalTest/resources/scenarios/RIA-362-RIA-1673-edit-case-listing-docmosis-enabled.json

[RIA-1673](https://tools.hmcts.net/jira/browse/RIA-1673)
See Jira
```
[ ] Yes
[x] No
```

RIA-1673 edited hearing notice

---

Jenkinsfile_CNP
Jenkinsfile_nightly
Jenkinsfile_parameterized
build.gradle
infrastructure/main.tf
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/HearingCentre.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/HearingCentreFinder.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/config/HearingCentreFinderConfiguration.java
src/main/resources/application-postcodes.yaml
src/main/resources/bootstrap.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/HearingCentreTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/HearingCentreFinderTest.java

[RIA-1380](https://tools.hmcts.net/jira/browse/RIA-1380)
See Jira
```
[ ] Yes
[x] No
```

Ria 1380 add hearing centres

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

[RIA-1647](https://tools.hmcts.net/jira/browse/RIA-1647)
end appeal notification ho
```
[ ] Yes
[x] No
```

Ria 1647 end appeal notify ho

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordApplicationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordApplicationHandlerTest.java

[RIA-1674](https://tools.hmcts.net/jira/browse/RIA-1674)
refused application notification
```
[ ] Yes
[x] No
```

RIA-1674 refused application notification

---

build.gradle
src/functionalTest/resources/scenarios/RIA-1485-record-granted-transfer-application-confirmation.json
src/functionalTest/resources/scenarios/RIA-1654-edit-case-listing-admin-officer.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCase.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RecordApplicationConfirmation.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RecordApplicationConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/serialization/AsylumCaseCallbackDeserializerTest.java

[RIA-1654](https://tools.hmcts.net/jira/browse/RIA-1654)
admin edit listing
```
[ ] Yes
[x] No
```

Ria 1654 admin edit case

---

Jenkinsfile_CNP
Jenkinsfile_nightly
Jenkinsfile_parameterized
README.md
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/CcdScenarioRunnerTest.java
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/util/AuthorizationHeadersProvider.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/UserRole.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/UserRoleTest.java

[RIA-1304](https://tools.hmcts.net/jira/browse/RIA-1304)
See Jira
```
[ ] Yes
[x] No
```

Ria 1304 authenticate home office user

---

charts/ia-case-api/Chart.yaml
charts/ia-case-api/values.aat.template.yaml

AKS adding aat config.

---

build.gradle
zap-known-issues.xml

zap testing suppressions whitespaces
```
[ ] Yes
[x] No
```

zap testing fix

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTag.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTagTest.java

N/A
add missing DocumentTag values
```
[ ] Yes
[x] No
```

add missing DocumentTag values

---

src/functionalTest/resources/scenarios/RIA-1308-upload-respondent-evidence-homeoffice-confirmation.json
src/functionalTest/resources/scenarios/RIA-1308-upload-respondent-evidence-homeoffice-submit.json
src/functionalTest/resources/scenarios/RIA-1308-upload-respondent-evidence-homeoffice-superuser-confirmation.json
src/functionalTest/resources/scenarios/RIA-1308-upload-respondent-evidence-homeoffice-superuser-submit.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/UploadHomeOfficeBundleConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UploadRespondentEvidenceHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/UploadHomeOfficeBundleConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UploadRespondentEvidenceHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-1308
Allow Home Office users (authorized) to upload Home Office bundle
```
[ ] Yes
[x] No
```

Ria 1308 upload Home Office bundle

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CurrentCaseStateUpdater.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestRespondentEvidencePreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UploadRespondentEvidenceHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CurrentCaseStateUpdaterTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestRespondentEvidencePreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UploadRespondentEvidenceHandlerTest.java

[RIA-1707](https://tools.hmcts.net/jira/browse/RIA-1707)
See Jira
```
[ ] Yes
[x] No
```

Ria 1707 awaiting ho evidence

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

[RIA-1792](https://tools.hmcts.net/jira/browse/RIA-1792)
Notification to case officer of respondent evidence submitted
```
[ ] Yes
[x] No
```

Ria 1792 notify case officer of respondent evidence submitted

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CurrentCaseStateUpdater.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CurrentCaseStateUpdaterTest.java

[RIA-1357](https://tools.hmcts.net/jira/browse/RIA-1357)
See Jira
```
[ ] Yes
[x] No
```

Ria 1357 case building ho users

---

src/functionalTest/resources/scenarios/RIA-1309-upload-appeal-response-homeoffice-confirmation-generic-user.json
src/functionalTest/resources/scenarios/RIA-1309-upload-appeal-response-homeoffice-confirmation.json
src/functionalTest/resources/scenarios/RIA-1309-upload-appeal-response-homeoffice-submit-generic-user.json
src/functionalTest/resources/scenarios/RIA-1309-upload-appeal-response-homeoffice-submit.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/UploadHomeOfficeAppealResponseConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestRespondentReviewPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UploadHomeOfficeAppealResponseHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/UploadHomeOfficeAppealResponseConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestRespondentReviewPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UploadHomeOfficeAppealResponseHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-1309
Upload appeal reseponse by Home Office
```
[ ] Yes
[X] No
```

Ria 1309 upload ho appeal response

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

[RIA-1793](https://tools.hmcts.net/jira/browse/RIA-1793)
notify case officer for ho uploaded response
merge after RIA-1309 
```
[ ] Yes
[x] No
```

RIA-1793 notify case officer for ho uploaded response

---

src/functionalTest/resources/scenarios/RIA-1278-apc-upload-additional-ho-evidence-submit.json
src/functionalTest/resources/scenarios/RIA-1278-generic-upload-additional-ho-evidence-submit.json
src/functionalTest/resources/scenarios/RIA-1278-lart-upload-additional-ho-evidence-submit.json
src/functionalTest/resources/scenarios/RIA-1278-pou-upload-additional-ho-evidence-submit.json
src/functionalTest/resources/scenarios/RIA-1278-upload-additional-evidence-ho-action-available.json
src/functionalTest/resources/scenarios/RIA-1278-upload-additional-evidence-ho-confirmation.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/UploadAdditionalEvidenceHomeOfficeConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UploadAdditionalEvidenceHomeOfficeActionAvailableUpdater.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UploadAdditionalEvidenceHomeOfficeHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/UploadAdditionalEvidenceHomeOfficeConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UploadAdditionalEvidenceHomeOfficeActionAvailableUpdaterTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UploadAdditionalEvidenceHomeOfficeHandlerTest.java

[RIA-1278](https://tools.hmcts.net/jira/browse/RIA-1278)
additional evidence ho + unit tests + functional tests
```
[ ] Yes
[x] No
```

RIA-1278 additional evidence ho + unit tests + functional tests

---

src/functionalTest/resources/scenarios/RIA-1794-request-response-review.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DirectionTag.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RequestResponseAmendConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RequestResponseReviewConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AddAppealResponseHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestResponseAmendHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestResponseReviewHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewAmendDirectionHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UploadHomeOfficeAppealResponseHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UploadRespondentEvidenceHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/DirectionPartiesResolver.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/DirectionTagResolver.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DirectionTagTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RequestResponseAmendConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RequestResponseReviewConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestResponseAmendHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestResponseReviewHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewAmendDirectionHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/DirectionPartiesResolverTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/DirectionTagResolverTest.java

[RIA-1794](https://tools.hmcts.net/jira/browse/RIA-1794)
See Jira
```
[ ] Yes
[x] No
```

Ria 1794 ho response under review

---

src/functionalTest/resources/scenarios/RIA-1810-upload-amend-appeal-response-add-new-homeoffice-generic-submit.json
src/functionalTest/resources/scenarios/RIA-1810-upload-amend-appeal-response-add-new-homeoffice-lart-submit.json
src/functionalTest/resources/scenarios/RIA-1810-upload-amend-appeal-response-replace-homeoffice-generic-submit.json
src/functionalTest/resources/scenarios/RIA-1810-upload-amend-appeal-response-replace-homeoffice-lart-submit.json

https://tools.hmcts.net/jira/browse/RIA-1810
Changes to amend appeal response and retain all the documents and corresponding tests
```
[ ] Yes
[X] No
```

Ria 1810 amend ho appeal response

---

audit.json

N/A
zap ignore false positives
```
[ ] Yes
[x] No
```

zap false positives

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealReferenceNumberHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LegalRepresentativeDetailsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealReferenceNumberHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LegalRepresentativeDetailsHandlerTest.java

[RIA-1771](https://tools.hmcts.net/jira/browse/RIA-1771)
See Jira
```
[ ] Yes
[x] No
```

Ria 1771 appeal and appellant tabs

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

[RIA-1024](https://tools.hmcts.net/jira/browse/RIA-1024)
See Jira
```
[ ] Yes
[x] No
```

RIA-1024 notify co of case built

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

[RIA-1463](https://tools.hmcts.net/jira/browse/RIA-1463)
See Jira
```
[ ] Yes
[x] No
```

Ria 1463 appeal decision notifications

---

src/functionalTest/resources/scenarios/RIA-1278-upload-additional-evidence-ho-action-available.json
src/functionalTest/resources/scenarios/RIA-1603-upload-addendum-evidence-action-available.json
src/functionalTest/resources/scenarios/RIA-941-RIA-942-generate-hearing-ready-bundle-stitching-disabled.json
src/functionalTest/resources/scenarios/RIA-941-RIA-942-generate-hearing-ready-bundle-stitching-enabled.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

[RIA-942](https://tools.hmcts.net/jira/browse/RIA-942)
Notify homeOffice and legal rep of hearing bundle is ready
```
[ ] Yes
[x] No
```

Ria 942 notify homeOffice and legal rep of hearing bundle is ready

---

src/integrationTest/java/uk/gov/hmcts/reform/iacaseapi/docs/SwaggerPublisher.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/DbAppealReferenceNumberGenerator.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/controllers/PostSubmitCallbackController.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/controllers/PreSubmitCallbackController.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/controllers/advice/CallbackControllerAdvice.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/security/CcdEventAuthorizor.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/security/idam/IdamUserDetailsProvider.java

N/A
performance logs
```
[ ] Yes
[x] No
```

performance logs

---

Jenkinsfile_CNP
Jenkinsfile_nightly
Jenkinsfile_parameterized
infrastructure/main.tf
src/functionalTest/resources/scenarios/RIA-1278-upload-additional-evidence-ho-action-available.json
src/functionalTest/resources/scenarios/RIA-1603-upload-addendum-evidence-action-available.json
src/functionalTest/resources/scenarios/RIA-1845-upload-addendum-evidence-legal-rep-action-available.json
src/functionalTest/resources/scenarios/RIA-480-RIA-600-build-case-confirmation.json
src/functionalTest/resources/scenarios/RIA-481-appeal-skeleton-case-stitching-enabled.json
src/functionalTest/resources/scenarios/RIA-517-case-submitted-confirmation.json
src/functionalTest/resources/scenarios/RIA-706-upload-additional-evidence-action-available.json
src/functionalTest/resources/scenarios/RIA-941-RIA-942-generate-hearing-ready-bundle-stitching-enabled.json
src/functionalTest/resources/scenarios/RIA-941-generate-hearing-bundle-confirmation.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/HearingCentre.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListEditCaseHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/HearingCentreFinder.java
src/main/resources/application-postcodes.yaml
src/main/resources/bootstrap.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/HearingCentreTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListEditCaseHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/HearingCentreFinderTest.java

[RIA-1976](https://tools.hmcts.net/jira/browse/RIA-1976)
See Jira
```
[ ] Yes
[x] No
```

RIA-1976 add new hearing centres

---

charts/ia-case-api/Chart.yaml
charts/ia-case-api/values.preview.template.yaml

N/A
fix charts
```
[ ] Yes
[x] No
```

fix charts for preview

---

infrastructure/main.tf

N/A
fix terraform script
```
[ ] Yes
[x] No
```

fix terraform script

---

src/functionalTest/resources/scenarios/RIA-1278-upload-additional-evidence-ho-action-available.json
src/functionalTest/resources/scenarios/RIA-1603-upload-addendum-evidence-action-available.json
src/functionalTest/resources/scenarios/RIA-1845-upload-addendum-evidence-legal-rep-action-available.json
src/functionalTest/resources/scenarios/RIA-480-RIA-600-build-case-confirmation.json
src/functionalTest/resources/scenarios/RIA-481-appeal-skeleton-case-stitching-enabled.json
src/functionalTest/resources/scenarios/RIA-517-case-submitted-confirmation.json
src/functionalTest/resources/scenarios/RIA-706-upload-additional-evidence-action-available.json
src/functionalTest/resources/scenarios/RIA-941-RIA-942-generate-hearing-ready-bundle-stitching-enabled.json
src/functionalTest/resources/scenarios/RIA-941-generate-hearing-bundle-confirmation.json

N/A
enable stitching tests
```
[ ] Yes
[x] No
```

enable stitching api tests

---

src/functionalTest/resources/scenarios/RIA-1147-exit-appeal-from-the-online-service-confirmation.json
src/functionalTest/resources/scenarios/RIA-1147-exit-appeal-from-the-online-service.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/State.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RemoveAppealFromOnlineConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RemoveAppealFromOnlineHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/StateTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RemoveAppealFromOnlineConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RemoveAppealFromOnlineHandlerTest.java

[RIA-1147](https://tools.hmcts.net/jira/browse/RIA-1147)
Exit appeal from the online service
```
[ ] Yes
[x] No
```

RIA-1147 Exit appeal from online service

---

audit.json

N/A
ignore nightly build warning for mid event endpoint
```
[ ] Yes
[x] No
```

ignore warning for mid event endpoint

---

build.gradle
infrastructure/ithc.tfvars

N/A
AKS migration for ITHC env
```
[ ] Yes
[x] No
```

AKS migration for ITHC env

---

charts/ia-case-api/Chart.yaml

N/A
charts upgrade
```
[ ] Yes
[x] No
```

charts upgrade

---

src/functionalTest/resources/scenarios/RIA-2041-list-case-without-submit-hearing-requirements.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ReviewHearingRequirementsConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListCaseWithoutHearingRequirementsHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ReviewHearingRequirementsConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListCaseWithoutHearingRequirementsHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-2041
List case without Hearing requirements
```
[ ] Yes
[X] No
```

 RIA-2041: Changes to list case without hearing requirements

---

src/functionalTest/resources/scenarios/RIA-2243-admin-officer-list-case-error.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListCasePreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/controllers/PreSubmitCallbackController.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListCasePreparerTest.java

https://tools.hmcts.net/jira/browse/RIA-2243
validation for 'List case' without agreed hearing requirements.
```
[ ] Yes
[X] No
```

Ria 2243 admin list error

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/WelcomeTest.java
src/integrationTest/java/uk/gov/hmcts/reform/iacaseapi/component/testutils/DocumentCaseApiVerifications.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/AsylumCaseCallbackApiDelegator.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/CcdUpdater.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/ProfessionalUsersRetriever.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/controllers/PostSubmitCallbackController.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/controllers/PreSubmitCallbackController.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/controllers/WelcomeController.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/AsylumCaseCallbackApiDelegatorTest.java

N/A
fix security vulnerabilities
```
[ ] Yes
[x] No
```

fix security vulnerabilities

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DerivePostcodeHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DerivePostcodeHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-1465
Updated case list and search filter criteria
```
[ ] Yes
[X] No
```

Ria 1465 search filters

---

src/functionalTest/resources/scenarios/RIA-823-end-appeal.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EndAppealHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EndAppealHandlerTest.java

[RIA-1891](https://tools.hmcts.net/jira/browse/RIA-1891)
mark application completed after ending appeal
```
[ ] Yes
[ ] No
```

RIA-1891 mark application completed after ending appeal

---

src/functionalTest/resources/scenarios/RIA-1485-RIA-1500-record-granted-time-extension-application-confirmation.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RecordApplicationConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ChangeDirectionDueDateHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordApplicationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RecordApplicationConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ChangeDirectionDueDateHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordApplicationHandlerTest.java

[RIA-1500](https://tools.hmcts.net/jira/browse/RIA-1500)
See Jira
```
[ ] Yes
[x] No
```

RIA-1500 extend due date direction from application request

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

[RIA-2045](https://tools.hmcts.net/jira/browse/RIA-2045)
Notification of uploaded additional evidence
```
[ ] Yes
[x] No
```

RIA-2045 notification of uploaded additional evidence

---

Jenkinsfile_CNP

Removing enableDockerBuild from Jenkinsfile which is no longer needed

---

src/functionalTest/resources/scenarios/RIA-1603-upload-addendum-evidence-submit.json
src/functionalTest/resources/scenarios/RIA-1845-upload-addendum-evidence-legal-rep-submit.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

[RIA-2046](https://tools.hmcts.net/jira/browse/RIA-2046)
Notification of uploaded addendum
```
[ ] Yes
[x] No
```

RIA-2046 Notification of uploaded addendum

---

build.gradle

N/A
sonar check poc
```
[ ] Yes
[x] No
```

sonar check poc

---

charts/ia-case-api/values.preview.template.yaml

Removing config which is no longer required.

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

[RIA-2345](RIA-2345-notification-of-change-due-date)
Notification of change direction due date
```
[ ] Yes
[x] No
```

RIA-2345 notification of change due date

---

security.sh

N/A
HTML zap testing report
```
[ ] Yes
[x] No
```

HTML zap testing report

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

[RIA-2297](https://tools.hmcts.net/jira/browse/RIA-2297)
See Jira
```
[ ] Yes
[x] No
```

RIA-2297 edit listing notification to admin team

---

Jenkinsfile_CNP
build.gradle

N/A
IA Demo exception remove
```
[ ] Yes
[x] No
```

IA Demo exception remove

---

src/functionalTest/resources/scenarios/RIA-2374-update-hearing-adjustments-validation.json
src/functionalTest/resources/scenarios/RIA-2374-update-hearing-adjustments.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListEditCaseHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewUpdateHearingRequirementsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewUpdateHearingRequirementsHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-2398
Changes to relisting case after review update hearing requirements
```
[ ] Yes
[X] No
```

Ria 2398 ao list case

---

src/functionalTest/resources/scenarios/RIA-910-RIA-911-RIA-912-RIA-1360-current-case-state-example1.json
src/functionalTest/resources/scenarios/RIA-910-RIA-911-RIA-912-RIA-1360-current-case-state-example2.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CurrentCaseStateUpdater.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CurrentCaseStateUpdaterTest.java

[RIA-1360](https://tools.hmcts.net/jira/browse/RIA-1360)
Judge role
```
[ ] Yes
[x] No
```

RIA-1360 Judge role

---

src/main/resources/application.yaml

update postgres port to match ia-docker configuration

---

Jenkinsfile_CNP
Jenkinsfile_nightly
Jenkinsfile_parameterized
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/CcdScenarioRunnerTest.java
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/util/AuthorizationHeadersProvider.java
src/functionalTest/resources/scenarios/RIA-2468-share-case-validation.json
src/integrationTest/java/uk/gov/hmcts/reform/iacaseapi/component/ShareACaseCcdIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/iacaseapi/component/ShareACaseRefDataIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/iacaseapi/component/testutils/RefDataIntegrationTest.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ShareACasePermissionsHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ShareACasePermissionsHandlerTest.java

[RIA-2468](https://tools.hmcts.net/jira/browse/RIA-2468)
share case validation
```
[ ] Yes
[x] No
```

RIA-2468 share case validation

---

src/functionalTest/resources/scenarios/RIA-2555-hearing-requirements-missing-flag .json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewDraftHearingRequirementsPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewDraftHearingRequirementsPreparerTest.java

Handle review hearing requirements missing flag exceptions more gracefully for user
https://tools.hmcts.net/jira/browse/RIA-2555

RIA-2555 hearing requirements missing flag exceptions handled

---

src/functionalTest/resources/scenarios/RIA-2620-upload-hearing-recording-confirmation.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/UploadHearingRecordingConfirmation.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/UploadHearingRecordingConfirmationTest.java

[RIA-2620](https://tools.hmcts.net/jira/browse/RIA-2620)
upload hearing recording
```
[ ] Yes
[x] No
```

RIA-2620 upload hearing recording

---

src/functionalTest/resources/scenarios/RIA-2723-case-data-maintained-in-pre-hearing-state-change.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java

New event - Send to preHearing state
New event - Send to preHearing state
```
[ ] Yes
[ X] No
```

RIA-2723 New event - Send to preHearing state

---

Jenkinsfile_CNP
Jenkinsfile_nightly
Jenkinsfile_parameterized
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/CcdScenarioRunnerTest.java
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/util/AuthorizationHeadersProvider.java
src/functionalTest/resources/scenarios/RIA-1280-generate-decision-and-reasons-judge.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/GenerateDecisionAndReasonsConfirmation.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/GenerateDecisionAndReasonsConfirmationTest.java

https://tools.hmcts.net/jira/browse/RIA-1280
Prepare Decision and Reasons document by Judge
```
[ ] Yes
[X] No
```

Ria 1280 judge generate decisions

---

src/functionalTest/resources/scenarios/RIA-2239-judge-end-appeal.json
src/main/resources/application.yaml

[RIA-2239](https://tools.hmcts.net/jira/browse/RIA-2239)
Functionality added to allow a judge to end appeal
```
[ ] Yes
[X] No
```

Ria 2239 judge end appeal

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/SendDecisionAndReasonsConfirmation.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/SendDecisionAndReasonsConfirmationTest.java

https://tools.hmcts.net/jira/browse/RIA-1939
Upload and send Decision and Reasons document (FT Judge)
```
[ ] Yes
[X] No
```

Ria 1939 judge upload decision

---

src/functionalTest/resources/scenarios/RIA-2240-change-direction-due-date-start-judge.json
src/functionalTest/resources/scenarios/RIA-2240-change-direction-due-date-submit-judge.json
src/main/resources/application.yaml

[RIA-2240](https://tools.hmcts.net/jira/browse/RIA-2240)
```
[ ] Yes
[X] No
```

Ria 2240 due date judge

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/config/HealthCheckConfiguration.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/config/RestTemplateConfiguration.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/config/SecurityConfiguration.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/health/DownStreamHealthIndicator.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/health/ServiceHealthIndicator.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/health/DownStreamHealthIndicatorTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/health/ServiceHealthIndicatorTest.java

[RIA-2526](https://tools.hmcts.net/jira/browse/RIA-2526)
Case api downstream dependencies health check
```
[ ] Yes
[x] No
```

RIA-2526 downstream services health check

---

src/smokeTest/java/uk/gov/hmcts/reform/iacaseapi/SmokeTest.java

[RIA-1906](https://tools.hmcts.net/jira/browse/RIA-2196)
Smoke test improvement
```
[ ] Yes
[x] No
```

RIA-1906 smoke test improvement

---

src/functionalTest/resources/scenarios/RIA-2634-change-hearing-centre.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ApplicationType.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RecordApplicationConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordApplicationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RecordApplicationConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordApplicationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-2634
Created a new application type of `CHANGE_HEARING_CENTRE` to be used when an application is created to change the designated hearing centre.
Added some logic to only allow this application when certain states are met.
Displaying a message post successful submit of application.
```
[ ] Yes
[x] No
```

RIA-2634: Change of designated hearing centre

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordApplicationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordApplicationHandlerTest.java

[RIA-2833: Change hearing centre](https://tools.hmcts.net/jira/browse/RIA-2833)
Added more states which the event `CHANGE_HEARING_CENTRE` can exist in.
```
[ ] Yes
[x] No
```

RIA-2833: Change hearing centre

---

src/functionalTest/resources/scenarios/RIA-2558-RIA-2644-change-hearing-centre.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-2644
Added the event `CHANGE_HEARING_CENTRE` to the notification sender handler.
Updated the functional tests.
```
[ ] Yes
[x] No
```

RIA-2644: Sending notifcation to legal rep about change of hearing centre

---

src/functionalTest/resources/scenarios/RIA-2558-RIA-2644-RIA-2739-change-hearing-centre.json

https://tools.hmcts.net/jira/browse/RIA-2739
Added the event `CHANGE_HEARING_CENTRE` to the notification sender handler.
Updated the functional tests.
```
[ ] Yes
[x] No
```

RIA-2739: Sending notification to hearing centre

---

src/functionalTest/resources/scenarios/RIA-1293-ftpa-appellant-confirmation.json
src/functionalTest/resources/scenarios/RIA-1293-ftpa-appellant-in-time-submit.json
src/functionalTest/resources/scenarios/RIA-1293-ftpa-appellant-out-of-time-submission-confirmation.json
src/functionalTest/resources/scenarios/RIA-1293-ftpa-appellant-out-of-time-submit.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTag.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/State.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/FtpaAppellantConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaAppellantHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaAppellantPreparer.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTagTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/StateTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/FtpaAppellantConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaAppellantHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaAppellantPreparerTest.java

https://tools.hmcts.net/jira/browse/RIA-1293
FTPA Appellant application to the Upper Tribunal
```
[ ] Yes
[X] No
```

Ria 1293 ftpa appellant

---

src/functionalTest/resources/scenarios/RIA-1293-ftpa-appellant-duplicate-submit-validation.json
src/functionalTest/resources/scenarios/RIA-1293-ftpa-appellant-out-of-time-flag-on-submit.json
src/functionalTest/resources/scenarios/RIA-2581-ftpa-respondent-duplicate-homeoffice-generic-submit-validation.json
src/functionalTest/resources/scenarios/RIA-2581-ftpa-respondent-duplicate-homeoffice-pou-submit-validation.json
src/functionalTest/resources/scenarios/RIA-2581-ftpa-respondent-homeoffice-generic-confirmation.json
src/functionalTest/resources/scenarios/RIA-2581-ftpa-respondent-homeoffice-pou-confirmation.json
src/functionalTest/resources/scenarios/RIA-2581-ftpa-respondent-in-time-homeoffice-generic-submit.json
src/functionalTest/resources/scenarios/RIA-2581-ftpa-respondent-in-time-homeoffice-pou-submit.json
src/functionalTest/resources/scenarios/RIA-2581-ftpa-respondent-out-of-time-flag-set-homeoffice-generic.json
src/functionalTest/resources/scenarios/RIA-2581-ftpa-respondent-out-of-time-flag-set-homeoffice-pou.json
src/functionalTest/resources/scenarios/RIA-2581-ftpa-respondent-out-of-time-homeoffice-generic-submit.json
src/functionalTest/resources/scenarios/RIA-2581-ftpa-respondent-out-of-time-homeoffice-pou-submit.json
src/functionalTest/resources/scenarios/RIA-2581-ftpa-respondent-out-of-time-submission-homeoffice-generic-confirmation.json
src/functionalTest/resources/scenarios/RIA-2581-ftpa-respondent-out-of-time-submission-homeoffice-pou-confirmation.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTag.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/FtpaRespondentConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaRespondentHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaRespondentPreparer.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTagTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/FtpaRespondentConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaRespondentHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaRespondentPreparerTest.java

RIA-2581
RIA-2581: Respondent FTPA submission changes
```
[ ] Yes
[x] No
```

RIA-2581: Respondent FTPA submission changes

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

[RIA-1373](https://tools.hmcts.net/jira/browse/RIA-1373)
Notification of FTPA application submitted.
```
[ ] Yes
[x] No
```

RIA-1373 notification of ftpa application submitted

---

Jenkinsfile_CNP
Jenkinsfile_nightly
Jenkinsfile_parameterized
charts/ia-case-api/Chart.yaml
charts/ia-case-api/values.preview.template.yaml
charts/ia-case-api/values.yaml
infrastructure/main.tf

https://tools.hmcts.net/jira/browse/RIA-2820
RIA-2820 Moved urls out of vault
```
[ ] Yes
[ X] No
```

RIA-2820 Moved urls out of vault

---

build.gradle
lombok.config
src/functionalTest/resources/scenarios/RIA-2783-editDocuments-event.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentWithDescription.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentWithMetadata.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/HearingRecordingDocument.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/field/Document.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/field/HasDocument.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/field/IdValue.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/editdocs/EditDocsAuditLogHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/editdocs/EditDocsAuditService.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EditDocsAboutToSubmitHandler.java
src/main/resources/application-local.yaml
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentWithMetadataTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/field/DocumentTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/field/IdValueTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/editdocs/EditDocsAuditLogHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/editdocs/EditDocsAuditServiceTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EditDocsAboutToSubmitHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-2783

RIA-2783 Feature/ria 2783 delete docs

---

src/functionalTest/resources/scenarios/RIA-1434-leadership-judge-record-appellant-ftpa-decision-confirmation.json
src/functionalTest/resources/scenarios/RIA-1434-leadership-judge-record-appellant-ftpa-decision.json
src/functionalTest/resources/scenarios/RIA-1434-leadership-judge-record-respondent-ftpa-decision.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTag.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/State.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/LeadershipJudgeFtpaDecisionConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LeadershipJudgeFtpaDecisionHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LeadershipJudgeFtpaDecisionMidEvent.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTagTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/StateTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/LeadershipJudgeFtpaDecisionConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LeadershipJudgeFtpaDecisionHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LeadershipJudgeFtpaDecisionMidEventTest.java

[RIA-1434](https://tools.hmcts.net/jira/browse/RIA-1434)
As a Leadership judge record the FTPA decision
```
[ ] Yes
[x] No
```

RIA-1434 leadership judge ftpa decision

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/callback/PreSubmitCallbackResponse.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/PreSubmitCallbackStateHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaAppealDecisionStateHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaAppealStateHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/PreSubmitCallbackDispatcher.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaAppealDecisionStateHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaAppealStateHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/PreSubmitCallbackDispatcherTest.java

https://tools.hmcts.net/jira/browse/RIA-2931
dynamic state update changes
```
[ ] Yes
[X] No
```

Ria 2931 dynamic state update

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaAppellantHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaRespondentHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LeadershipJudgeFtpaDecisionHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaAppellantHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaRespondentHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LeadershipJudgeFtpaDecisionHandlerTest.java

[RIA-2932](https://tools.hmcts.net/jira/browse/RIA-2932)
Ftpa documents should be visible to other parties in granted and partially granted outcomes
```
[ ] Yes
[x] No
```

RIA-2932 ftpa documents display to the other party

---

.gitignore
README.md
bin/validate_case_api.js
package.json

N/A
ia-case-api CCD fields validation
```
[ ] Yes
[x] No
```

ia-case-api CCD fields validation

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandler.java

https://tools.hmcts.net/jira/browse/RIA-2564
Added decisionAvailable flag to handle overview tab visibility
```
[ ] Yes
[X] No
```

Ria 2564 ftpa leadership overview tabs

---

src/functionalTest/resources/scenarios/RIA-2829-PrepairTimeExtension.json
src/functionalTest/resources/scenarios/RIA-2829-ReviewTimeExtension.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DynamicList.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/TimeExtension.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/TimeExtensionDecision.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/TimeExtensionStatus.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/Value.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewTimeExtensionPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewTimeExtensionsHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewDraftHearingRequirementsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewTimeExtensionPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewTimeExtensionsHandlerTest.java

Ria 2829 tcw handles time extension request

---

charts/ia-case-api/Chart.yaml
charts/ia-case-api/values.yaml

N/A
fix ccd url
```
[ ] Yes
[x] No
```

fix ccd url

---

build.gradle

Updating spring boot to 2.2.6.RELEASE to fix CVE-2020-9488, CVE-2020-9488
```
[ ] Yes
[ x] No
```

Fixes CVE-2020-9488, CVE-2020-9488

---

src/functionalTest/resources/scenarios/RIA-1742-flag-case-confirmation.json
src/functionalTest/resources/scenarios/RIA-1742-flag-case-with-anonymity-flag.json
src/functionalTest/resources/scenarios/RIA-1742-flag-case-with-complex-case-flag.json
src/functionalTest/resources/scenarios/RIA-1742-flag-case-with-detained-immigration-appeal-flag.json
src/functionalTest/resources/scenarios/RIA-1742-flag-case-with-foreign-national-offender-flag.json
src/functionalTest/resources/scenarios/RIA-1742-flag-case-with-potentially-violent-person-flag.json
src/functionalTest/resources/scenarios/RIA-1742-flag-case-with-unacceptable-customer-behaviour-flag.json
src/functionalTest/resources/scenarios/RIA-1742-flag-case-with-unaccompanied-minor-flag.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/CaseFlag.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/CaseFlagType.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/flagcase/FlagCaseConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/flagcase/FlagCaseHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/CaseFlagAppender.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/CaseFlagTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/CaseFlagTypeTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/flagcase/FlagCaseConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/flagcase/FlagCaseHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/CaseFlagAppenderTest.java

https://tools.hmcts.net/jira/browse/RIA-1742
- Created a new handler to handle case flags.
- Created a new case flag type enum.
```
[ ] Yes
[x] No
```

RIA-1742: Adding flags to cases

---

src/functionalTest/resources/scenarios/RIA-893-RIA-1897-send-home-office-evidence-direction.json

https://tools.hmcts.net/jira/browse/RIA-1897
- Updated the functional test to reflect the changes added in the `ia-case-notifications-api`.
```
[ ] Yes
[x] No
```

RIA-1897: Sending a notification to legal rep when case officer requests HO evidence

---

src/functionalTest/resources/scenarios/RIA-722-RIA-1898-send-respondent-review-direction.json

https://tools.hmcts.net/jira/browse/RIA-1898
- Updated functional test to reflect the changes on `ia-case-notifications-api`.
```
[ ] Yes
[x] No
```

RIA-1898:  Notification to legal representative on request respondent review event

---

src/functionalTest/resources/scenarios/RIA-2829-PrepairTimeExtension.json
src/functionalTest/resources/scenarios/RIA-2829-ReviewTimeExtension.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/Direction.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DynamicList.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/TimeExtension.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ReviewTimeExtensionConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewTimeExtensionPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewTimeExtensionsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/DateAppender.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/eventvalidation/AsylumCaseEventValidForJourneyTypeChecker.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ReviewTimeExtensionConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewTimeExtensionPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewTimeExtensionsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-2878
Added due date, confirmation page, validation and tests
```
[ ] Yes
[ x ] No
```

Ria 2878 update time extension due date

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/eventvalidation/AsylumCaseEventValidForJourneyTypeChecker.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/editdocs/EditDocsAuditLogHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewTimeExtensionsHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-2301
```
[ ] Yes
[X] No
```

Ria 2301 view clarifying answers

---

src/functionalTest/resources/scenarios/RIA-3017-ConfirmCmaRequirements.json
src/functionalTest/resources/scenarios/RIA-3017-HandleCmaRequirements.json
src/functionalTest/resources/scenarios/RIA-3017-PrepairCmaRequirements.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DirectionTag.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/State.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RequestCmaRequirementsConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestCmaRequirementsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestCmaRequirementsPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/eventvalidation/AsylumCaseEventValidForJourneyTypeChecker.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinitionTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DirectionTagTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/StateTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RequestCmaRequirementsConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestCmaRequirementsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestCmaRequirementsPreparerTest.java

Tcw requests CMA requirements, preparer, handler and confirmation screen.
https://tools.hmcts.net/jira/browse/RIA-3017
```
[ ] Yes
[X] No
```

RIA-3017 TCW requests CMA requirements

---

src/functionalTest/resources/scenarios/RIA-2715-appeal-submitted-access-denied-exception.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/eventvalidation/AsylumCaseEventValidForJourneyTypeChecker.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/eventvalidation/AsylumCaseSendDirectionEventValidForJourneyTypeChecker.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/security/CcdEventAuthorizor.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/eventvalidation/AsylumCaseEventValidForJourneyTypeCheckerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/eventvalidation/AsylumCaseSendDirectionEventValidForJourneyTypeCheckerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/security/CcdEventAuthorizorTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/util/LoggerUtil.java

[RIA-2715](https://tools.hmcts.net/jira/browse/RIA-2715)
See Jira
```
[ ] Yes
[x] No
```

RIA-2715 errors logging as traces

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-2307
Adds sendDirectionWithQuestions and submitClarifyingQuestionAnswers Events to the Notification handler to be able to forward this event to the notifications service
```
[ ] Yes
[ x] No
```

RIA-2307: Request Clarifying Questions & Submit

---

audit.json

[RIA-3171](https://tools.hmcts.net/jira/browse/RIA-3171)
See Jira
```
[ ] Yes
[x] No
```

RIA-3171 failing nightly builds

---

build.gradle
src/functionalTest/resources/scenarios/RIA-236-revocation-grounds.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealGroundsForDisplayFormatter.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealGroundsForDisplayFormatterTest.java

[RIA-3257](https://tools.hmcts.net/jira/browse/RIA-3257)
```
[ ] Yes
[x] No
```

RIA-3257 old appeal-grounds lost after edit

---

Jenkinsfile_CNP
Jenkinsfile_nightly
Jenkinsfile_parameterized
charts/ia-case-api/Chart.yaml
charts/ia-case-api/values.preview.template.yaml
charts/ia-case-api/values.yaml
src/functionalTest/resources/scenarios/RIA-921-automatic-direction.json
src/integrationTest/java/uk/gov/hmcts/reform/iacaseapi/component/testutils/SpringBootIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AutomaticDirectionHandlerTest.java
src/integrationTest/resources/application-integration.yaml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AutomaticDirectionRequestingHearingRequirementsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/Scheduler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/TimedEventServiceApi.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/TimedEventServiceScheduler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/model/TimedEvent.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/config/ServiceTokenGeneratorConfiguration.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AutomaticDirectionRequestingHearingRequirementsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/TimedEventServiceSchedulerTest.java

[RIA-921](https://tools.hmcts.net/jira/browse/RIA-921)
automatic direction
```
[ ] Yes
[x] No
```

RIA-921 automatic direction

---

Jenkinsfile_nightly
audit.json
security.sh

[RIA-3171](https://tools.hmcts.net/jira/browse/RIA-3171)
See Jira
```
[ ] Yes
[x] No
```

nightly build fix --securityrules config and additional parameters

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestRespondentReviewPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestRespondentReviewPreparerTest.java

Updated wording when the TCW requests the respondent reviews the case
argument.
https://tools.hmcts.net/jira/browse/RIA-2300
```
[X] Yes
[] No
```

RIA-2300 request respondent review case argument

---

build.gradle
charts/ia-case-api/Chart.yaml
charts/ia-case-api/values.preview.template.yaml
charts/ia-case-api/values.yaml
src/integrationTest/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AutomaticDirectionHandlerTest.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/DateProvider.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AutomaticDirectionRequestingHearingRequirementsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/FeatureToggler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/SystemDateProvider.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/LaunchDarklyFeatureToggler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/config/FeatureToggleConfiguration.java
src/main/resources/application.yaml
src/main/resources/bootstrap.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AutomaticDirectionRequestingHearingRequirementsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/SystemDateProviderTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/LaunchDarklyFeatureTogglerTest.java

[RIA-3300](https://tools.hmcts.net/jira/browse/RIA-3300)
Launch Darkly and automatic direction feature
```
[ ] Yes
[x] No
```

RIA-3300 Launch Darkly and automatic direction feature

---

src/functionalTest/resources/scenarios/RIA-611-RIA-739-request-case-edit-submit.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-739

RIA-739 add request case edit even to send notification

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AsylumCaseDataFixingHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AutomaticDirectionRequestingHearingRequirementsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AsylumCaseDataFixingHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AutomaticDirectionRequestingHearingRequirementsHandlerTest.java

N/A
feature toggler for LD in every event
```
[ ] Yes
[x] No
```

feature toggler for LD in every event

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java

https://tools.hmcts.net/jira/browse/RIA-3174
Added events for access-needs
```
[ ] Yes
[ x ] No
```

RIA-3174-Added-Events

---

src/functionalTest/resources/scenarios/RIA-1654-RIA-2851-edit-case-listing-admin-officer.json
src/functionalTest/resources/scenarios/RIA-362-RIA-1673-edit-case-listing-docmosis-disabled.json
src/functionalTest/resources/scenarios/RIA-362-RIA-1673-edit-case-listing-docmosis-enabled.json
src/functionalTest/resources/scenarios/RIA-412-RIA-1571-hearing-notice-docmosis-disabled.json
src/functionalTest/resources/scenarios/RIA-412-RIA-1571-hearing-notice-docmosis-enabled.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListEditCaseHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListEditCaseHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-2851
Changing the hearing centre underneath the case details after the case has been listed and edited by TCW.
```
[ ] Yes
[x] No
```

RIA-2851: Change hearing centre when case is edited after being listed.

---

src/functionalTest/resources/scenarios/RIA-1358-update-legal-representatives-details.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/LegalRepresentativeUpdateDetailsConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LegalRepresentativeUpdateDetailsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LegalRepresentativeUpdateDetailsPreparer.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/LegalRepresentativeUpdateDetailsConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LegalRepresentativeUpdateDetailsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LegalRepresentativeUpdateDetailsPreparerTest.java

https://tools.hmcts.net/jira/browse/RIA-1358
Added an event to allow legal representative to update their details.
```
[ ] Yes
[x] No
```

RIA-1358: Update legal representative's details

---

src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/util/AuthorizationHeadersProvider.java

N/A
improve functional tests stability
```
[ ] Yes
[x] No
```

improve functional tests stability

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-3020
Added SUBMIT_CMA_REQUIREMENTS event to be forwarded to notification service
```
[ ] Yes
[x ] No
```

RIA-3020: SUBMIT_CMA_REQUIREMENTS to Notification service

---

src/functionalTest/resources/scenarios/RIA-2122-decision-without-hearing.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java

https://tools.hmcts.net/jira/browse/RIA-2122
```
[ ] Yes
[x] No
```

added event for decision without hearing

---

src/functionalTest/resources/scenarios/RIA-3389-home-office-reference-formatter-letter-plus-seven-digits.json
src/functionalTest/resources/scenarios/RIA-3389-home-office-reference-formatter-non-standard.json
src/functionalTest/resources/scenarios/RIA-3389-home-office-reference-formatter-without-slash.json
src/functionalTest/resources/scenarios/RIA-3389-home-office-reference-formatter.json
src/functionalTest/resources/scenarios/RIA-730-RIA-971-home-office-truncator.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeReferenceNumberTruncator.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeReferenceNumberTruncatorTest.java

[RIA-3389](https://tools.hmcts.net/jira/browse/RIA-3389)
```
[x] Yes
[ ] No
```

RIA-3389 Accept non-standard HO refs

---

build.gradle

N/A
fix vulnerability
```
[ ] Yes
[x] No
```

fix vulnerability

---

src/functionalTest/resources/scenarios/RIA-3091-update-cma-appointment-admin.json
src/functionalTest/resources/scenarios/RIA-3091-update-cma-appointment.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ApplicationType.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/UpdateAppointmentAfterCmaConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateAppointmentAfterCmaHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/UpdateAppointmentAfterCmaConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateAppointmentAfterCmaHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-3091
Added Handler to update CMA Appointment
```
[ ] Yes
[ x ] No
```

RIA-3091-Update-Details-After-Appointment

---

src/functionalTest/resources/scenarios/RIA-3291-RIA-3295-unlink-appeal.json
src/functionalTest/resources/scenarios/RIA-3295-link-appeal.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ReasonForLinkAppealOptions.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-3295

RIA-3295 add link and unlink event to the sendNotification handler

---

src/functionalTest/resources/scenarios/RIA-3291-RIA-3295-RIA-3329-unlink-appeal.json
src/functionalTest/resources/scenarios/RIA-3295-RIA-3329-link-appeal.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-3329

RIA-3329 Feature/ria 3329 link unlink ho notification

---

src/functionalTest/resources/scenarios/RIA-2935-EA-appeal-fee-pay-later-hearing.json
src/functionalTest/resources/scenarios/RIA-2935-EA-appeal-fee-pay-later-without-hearing.json
src/functionalTest/resources/scenarios/RIA-2935-EA-appeal-fee-pay-now-hearing.json
src/functionalTest/resources/scenarios/RIA-2935-EA-appeal-fee-pay-now-without-hearing.json
src/functionalTest/resources/scenarios/RIA-3252-EA-appeal-fee-pay-later.json
src/functionalTest/resources/scenarios/RIA-635-appeal-saved-confirmation-edit.json
src/functionalTest/resources/scenarios/RIA-815-appeal-saved-confirmation-start.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/CaseDetails.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealPaymentConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSavedConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/AsylumCaseFeePaymentService.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/FeePayment.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/CaseDetailsTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSavedConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/AsylumCaseFeePaymentServiceTest.java

https://tools.hmcts.net/jira/browse/RIA-2935
RIA_2935 - Payment by PBA success
```
[ ] Yes
[X] No
```

RIA-2935_PBA_Payment

---

.travis.yml
Dockerfile
build.gradle
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestRespondentReviewHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestRespondentReviewPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestResponseAmendHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/controllers/AsylumCaseTest.java

[RIA-3439](https://tools.hmcts.net/jira/browse/RIA-3439)
```
[x] Yes
[ ] No
```

RIA-3439 Upgrading to Java11

---

build.gradle

[RIA-3479](https://tools.hmcts.net/jira/browse/RIA-3479)
```
[ ] Yes
[x] No
```

RIA-3479 upgrade pitest verion forjava11

---

charts/ia-case-api/values.preview.template.yaml
src/functionalTest/resources/scenarios/RIA-2774-force-request-case-building.json

https://tools.hmcts.net/jira/browse/RIA-2774

add expected notification

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

[RIA-1432](https://tools.hmcts.net/jira/browse/RIA-1432)
```
[ ] Yes
[x] No
```

Ria 1432 notify ftpa appeal decision

---

src/functionalTest/resources/scenarios/RIA-2527-resident-judge-record-appellant-ftpa-decision-confirmation.json
src/functionalTest/resources/scenarios/RIA-2527-resident-judge-record-appellant-ftpa-decision.json
src/functionalTest/resources/scenarios/RIA-2527-resident-judge-record-respondent-ftpa-decision.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ResidentJudgeFtpaDecisionConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaDecisionMidEvent.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ResidentJudgeFtpaDecisionHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ResidentJudgeFtpaDecisionConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaDecisionMidEventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ResidentJudgeFtpaDecisionHandlerTest.java

[RIA-2527](https://tools.hmcts.net/jira/browse/RIA-2527)
As a resident judge record fpta decision
```
[ ] Yes
[x] No
```

RIA-2527 As a resident judge ftpa decision

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ResidentJudgeFtpaDecisionHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ResidentJudgeFtpaDecisionHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-2571
added 'New appeal decision' field to support resident judge decision overview tabs
```
[ ] Yes
[X] No
```

Ria 2571 ftpa resident judge overview tabs

---

src/functionalTest/resources/scenarios/RIA-2527-resident-judge-record-appellant-ftpa-decision-confirmation.json
src/functionalTest/resources/scenarios/RIA-2527-resident-judge-record-appellant-ftpa-decision.json
src/functionalTest/resources/scenarios/RIA-2527-resident-judge-record-respondent-ftpa-decision.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

[RIA-2573](https://tools.hmcts.net/jira/browse/RIA-2573)
```
[ ] Yes
[x] No
```

Ria 2573 ftpa decision resident judge

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/FtpaDecisionOutcomeType.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/FtpaResidentJudgeDecisionOutcomeType.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaDecisionMidEvent.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ResidentJudgeFtpaDecisionHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaDecisionMidEventTest.java

https://tools.hmcts.net/jira/browse/RIA-3211
Aggregated flags to manage the event pages in ftpa decided state
```
[ ] Yes
[X] No
```

Ria 3211 rj ftpa decided

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaFinalDecisionDisplayProvider.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LeadershipJudgeFtpaDecisionHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ResidentJudgeFtpaDecisionHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaFinalDecisionDisplayProviderTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LeadershipJudgeFtpaDecisionHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ResidentJudgeFtpaDecisionHandlerTest.java

[RIA-2919](https://tools.hmcts.net/jira/browse/RIA-2919)
See Jira
```
[ ] Yes
[x] No
```

Ria 2919 final decision for two applications

---

src/integrationTest/java/uk/gov/hmcts/reform/iacaseapi/config/SwaggerPublisher.java

N/A
fix swagger publisher
```
[ ] Yes
[x] No
```

fix swagger publisher

---

src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/EndpointSecurityTest.java

N/A
fix endpoint test
```
[ ] Yes
[x] No
```

fix endpoint test

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/RIA-3372
CVE suppress cleanup
```
[ ] Yes
[X] No
```

RIA-3372: CVE clean up spike

---

src/integrationTest/java/uk/gov/hmcts/reform/iacaseapi/component/RecordAttendeesAndDurationTest.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/HearingAttendeesAndDurationRecordedConfirmation.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/HearingAttendeesAndDurationRecordedConfirmationTest.java

https://tools.hmcts.net/jira/browse/RIA-3297

change confirmation content

---

src/main/resources/application.yaml

removed HO integration api health check as it is not in prod yet
```
[ ] Yes
[X] No
```

removed HO integration api health check as it is not in prod yet

---

src/functionalTest/resources/scenarios/RIA-3498-error-on-submit-when-option-is-payNow-for-HU.json
src/functionalTest/resources/scenarios/RIA-3498-error-on-submit-when-option-is-payNow-for-PA.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SubmitAppealPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSavedConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SubmitAppealPreparerTest.java

[RIA-3498](https://tools.hmcts.net/jira/browse/RIA-3498)
See Jira
```
[ ] Yes
[x] No
```

Ria 3498 error msg submit

---

src/functionalTest/resources/scenarios/RIA-3163-PA-failed-payment-account-deleted-respondent-review-state.json
src/functionalTest/resources/scenarios/RIA-3163-PA-failed-payment-account-on-hold-listing-state.json
src/functionalTest/resources/scenarios/RIA-3163-PA-successful-payment-case-building-state.json.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealPaymentConfirmation.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealPaymentConfirmationTest.java

[RIA-3163](https://tools.hmcts.net/jira/browse/RIA-3163)
Make a payment after submitting the EA/HU/PA appeal types
```
[ ] Yes
[x] No
```

RIA-3163 make a payment after submit appeal

---

src/functionalTest/resources/scenarios/RIA-3409-error-on-payment-when-appeal-in-paidStatus.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePayAndSubmitPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePayAndSubmitPreparerTest.java

https://tools.hmcts.net/jira/browse/RIA-3498
RIA-3409-AvoidPayTwice
```
[ ] Yes
[X] No
```

Ria 3409 avoid pay twice

---

src/functionalTest/resources/scenarios/RIA-3025-successful-payment-for-pa-appeal-type-at-case-building.json
src/functionalTest/resources/scenarios/RIA-3025-successful-payment-for-pa-appeal-type-at-listing.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

[RIA-3025](https://tools.hmcts.net/jira/browse/RIA-3025)
See Jira
```
[ ] Yes
[x] No
```

RIA-3025 notification of pending payment (after appeal submitted)

---

src/functionalTest/resources/scenarios/RIA-2010-add-stateless-edit-appeal.json
src/functionalTest/resources/scenarios/RIA-2010-add-stateless-start-appeal.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/StatelessHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/StatelessHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-2010
Add stateless
```
[ ] Yes
[x] No
```

Pick up stateless and populate nationalities

---

src/functionalTest/resources/scenarios/RIA-2558-RIA-2644-RIA-2739-change-hearing-centre.json
src/functionalTest/resources/scenarios/RIA-2558-RIA-2644-change-hearing-centre.json
src/functionalTest/resources/scenarios/RIA-2558-change-hearing-centre.json
src/functionalTest/resources/scenarios/RIA-588-derive-hearing-center-from-postcode.json
src/functionalTest/resources/scenarios/RIA-588-derive-hearing-center-using-default.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/Location.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ChangeHearingCentreHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DeriveHearingCentreHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/utils/StaffLocation.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DeriveHearingCentreHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/utils/StaffLocationTest.java

https://tools.hmcts.net/jira/browse/RWA-87
Get staff location based on hearing centre
```
[ ] Yes
[ x ] No
```

RWA-87-Get staff location

---

src/functionalTest/resources/scenarios/RIA-1278-upload-additional-evidence-ho-action-available.json
src/functionalTest/resources/scenarios/RIA-1485-record-granted-transfer-application-confirmation.json
src/functionalTest/resources/scenarios/RIA-1485-record-granted-transfer-application.json
src/functionalTest/resources/scenarios/RIA-1485-record-granted-withdraw-application.json
src/functionalTest/resources/scenarios/RIA-1485-record-refused-application.json
src/functionalTest/resources/scenarios/RIA-1935-upload-addendum-evidence-ho-submit.json
src/functionalTest/resources/scenarios/RIA-2373-record-granted-update-hearing-requirements.json
src/functionalTest/resources/scenarios/RIA-2374-update-hearing-adjustments.json
src/functionalTest/resources/scenarios/RIA-2558-RIA-2644-RIA-2739-change-hearing-centre.json
src/functionalTest/resources/scenarios/RIA-2558-RIA-2644-change-hearing-centre.json
src/functionalTest/resources/scenarios/RIA-2558-change-hearing-centre.json
src/functionalTest/resources/scenarios/RIA-2783-edit-documents.json
src/functionalTest/resources/scenarios/RIA-2960-restore-case-state.json

[RIA-2536](https://tools.hmcts.net/jira/browse/RIA-2536)
Changes required to fix functional tests.
```
[ ] Yes
[x] No
```

RIA-2536 notification of application refused

---

src/functionalTest/resources/scenarios/RIA-3059-upload-sensitive-documents-confirmation.json
src/functionalTest/resources/scenarios/RIA-3391-view-sensitive-documents.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTag.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/UploadSensitiveDocsConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/editdocs/EditDocsAuditLogService.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UploadSensitiveDocsAboutToSubmitHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/editdocs/EditDocsAboutToSubmitHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/DocumentReceiver.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTagTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/UploadSensitiveDocsConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/editdocs/EditDocsAuditLogServiceTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UploadSensitiveDocsAboutToSubmitHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/DocumentReceiverTest.java

https://tools.hmcts.net/jira/browse/RIA-3392

RIA-3392 Delete sensitive documents

---

src/functionalTest/resources/scenarios/RIA-2935-EA-appeal-fee-pay-later-hearing.json
src/functionalTest/resources/scenarios/RIA-2935-EA-appeal-fee-pay-later-without-hearing.json
src/functionalTest/resources/scenarios/RIA-2935-EA-appeal-fee-pay-now-hearing.json
src/functionalTest/resources/scenarios/RIA-2935-EA-appeal-fee-pay-now-without-hearing.json
src/functionalTest/resources/scenarios/RIA-3252-EA-appeal-fee-pay-later.json
src/functionalTest/resources/scenarios/RIA-3412-pay-and-submit-appeal.json
src/functionalTest/resources/scenarios/RIA-3468-pa-appeal-type-pay-now.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSubmittedConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePayAndSubmitHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentDisplayProvider.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSubmittedConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePayAndSubmitHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentDisplayProviderTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentHandlerTest.java

[RIA-3434](https://tools.hmcts.net/jira/browse/RIA-3434)
See Jira
```
[ ] Yes
[x] No
```

Ria 3434 pay offline by card pa

---

src/functionalTest/resources/scenarios/RIA-3278-appeal-fee-pay-later-EA-change-state-to-payment-pending-with-hearing.json
src/functionalTest/resources/scenarios/RIA-3278-appeal-fee-pay-later-EA-change-state-to-payment-pending-without-hearing.json
src/functionalTest/resources/scenarios/RIA-3278-appeal-fee-pay-later-HU-change-state-to-payment-pending-with-hearing.json
src/functionalTest/resources/scenarios/RIA-3278-appeal-fee-pay-later-PA-change-state-to-appeal-submitted-with-hearing.json
src/functionalTest/resources/scenarios/RIA-3278-appeal-fee-pay-later-PA-change-state-to-appeal-submitted-without-hearing.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/State.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealPaymentConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSavedConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSubmittedConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentStateHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/StateTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSavedConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSubmittedConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentStateHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-3278
RIA-3278_State_Payment_Pending
```
[ ] Yes
[X] No
```

Ria 3278 state payment pending

---

src/functionalTest/resources/scenarios/RIA-2957-adjourn-without-a-date-confirmation.json
src/functionalTest/resources/scenarios/RIA-362-edit-case-listing-confirmation.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AdjournWithoutDateConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/EditCaseListingConfirmation.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AdjournWithoutDateConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/EditCaseListingConfirmationTest.java

https://tools.hmcts.net/jira/browse/RIA-3347
```
[ ] Yes
[ x ] No
```

RIA-3447 updated labels

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

[RIA-3103](https://tools.hmcts.net/jira/browse/RIA-3103)
```
[ ] Yes
[x] No
```

TAB-3103 Send notification when Request response amend

---

.gitignore
build.gradle
lombok.config
src/functionalTest/resources/scenarios/RIA-2783-edit-documents.json
src/integrationTest/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EditDocsCaseNoteServiceTest.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/editdocs/AuditDetails.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/editdocs/EditDocsAuditLogService.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/editdocs/EditDocsAuditService.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/editdocs/EditDocsCaseNoteService.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/editdocs/EditDocsAuditLogHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/editdocs/EditDocsAuditLogServiceTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/editdocs/EditDocsAuditServiceTest.java

https://tools.hmcts.net/jira/browse/RIA-3348

RIA-3348 Rename case note subject

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-3219
Enable notification when appeal marked as paid
```
[ ] Yes
[ X] No
```

Ria 3219 enable notification when appeal marked as paid

---

src/functionalTest/resources/scenarios/RIA-3574-pa-duplicate-payment-error.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentPreparerTest.java

[RIA-3574](https://tools.hmcts.net/jira/browse/RIA-3574)
Duplicate payments error handling
```
[ ] Yes
[x] No
```

RIA-3574 duplicate payment handling

---

src/functionalTest/resources/scenarios/RIA-3471-ea-appeal-type-pay-now-ou-of-time.json
src/functionalTest/resources/scenarios/RIA-3471-hu-appeal-type-pay-now-ou-of-time.json
src/functionalTest/resources/scenarios/RIA-3471-pa-appeal-type-pay-now-ou-of-time.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealPayAndSubmittedConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSubmittedConfirmation.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealPayAndSubmittedConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSubmittedConfirmationTest.java

https://tools.hmcts.net/jira/browse/RIA-3471
RIA-3471_Out_Of_Time scenario for F & P
```
[ ] Yes
[X] No
```

Ria 3471 out of time

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/field/PaymentStatus.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePayAndSubmitHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/field/PaymentStatusTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentStateHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MarkPaymentPaidStateHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-3592
RIA-3592 payment_method and payment_status
```
[ ] Yes
[X] No
```

Ria 3592 payment method

---

src/functionalTest/resources/scenarios/RIA-3553-record-edit-appeal-after-submit-appeal-confirmation.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordApplicationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordApplicationHandlerTest.java

[RIA-3553](https://tools.hmcts.net/jira/browse/RIA-3553)
```
[ ] Yes
[x] No
```

RIA-3553 Allow appeal update details after appeal-submitted state

---

infrastructure/main.tf

RIA-3668 
Azure upgrade
```
[ ] Yes
[x] No
```

Azure upgrade

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CancelAutomaticDirectionRequestingHearingRequirementsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CancelAutomaticDirectionRequestingHearingRequirementsHandlerTest.java

[RIA-3594](https://tools.hmcts.net/jira/browse/RIA-3594)
```
[ ] Yes
[x] No
```

RIA-3594 Cancel a timed event schedule after sending a direction

---

src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/util/MapValueExpander.java
src/functionalTest/resources/scenarios/RIA-1358-update-legal-representatives-details.json
src/functionalTest/resources/scenarios/RIA-2208-add-case-note-to-admin-officer.json
src/functionalTest/resources/scenarios/RIA-2774-force-request-case-building.json
src/functionalTest/resources/scenarios/RIA-2775-force-case-progression-to-case-under-review.json
src/functionalTest/resources/scenarios/RIA-2776-force-case-to-submit-hearing-requirements.json
src/functionalTest/resources/scenarios/RIA-2783-edit-documents.json
src/functionalTest/resources/scenarios/RIA-575-add-case-note-to-existing-case-notes.json
src/functionalTest/resources/scenarios/RIA-575-add-first-case-note.json
src/functionalTest/resources/scenarios/RIA-610-user-details-added-to-case.json
src/functionalTest/resources/templates/minimal-aip-appeal-submitted.json
src/functionalTest/resources/templates/minimal-appeal-submitted.json

N/A
Launch Darkly user prefix
```
[ ] Yes
[x] No
```

Launch Darkly user prefix

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MarkPaymentPaidHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MarkPaymentPaidHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-3654
RIA-3654 validation non_payment
```
[ ] Yes
[X] No
```

Ria 3654 validation non payment

---

src/functionalTest/resources/scenarios/RIA-3332-home-office-integration-flag-set-mark-appeal-paid.json
src/functionalTest/resources/scenarios/RIA-3332-home-office-integration-flag-set-pay-and-submit-appeal.json
src/functionalTest/resources/scenarios/RIA-3332-home-office-response-for-appeal-submitted-mark-appeal-paid.json
src/functionalTest/resources/scenarios/RIA-3332-home-office-response-for-appeal-submitted-pay-and-submit-appeal.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseValidateHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseValidatePreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseValidateHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseValidatePreparerTest.java

RIA-3332:Home office validation flow with F&P changes
No code change but to test functionality of Home Office after F&P changes were merged to master
https://tools.hmcts.net/jira/browse/RIA-3332
```
[ ] Yes
[ x] No
```

RIA-3332:Home office validation flow with F&P changes test

---

src/functionalTest/resources/scenarios/RIA-3390-home-office-integration-flag-set.json
src/functionalTest/resources/scenarios/RIA-3390-request-home-office-data-error-already-existing.json
src/functionalTest/resources/scenarios/RIA-3390-request-home-office-data-fail.json
src/functionalTest/resources/scenarios/RIA-3390-request-home-office-data-success.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseValidateHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeRequestHomeOfficeDataPreparer.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseValidateHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseValidatePreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeRequestHomeOfficeDataPreparerTest.java

RIA-3390: Request Home Office data event flow
https://tools.hmcts.net/jira/browse/RIA-3390
For handling scenario where we do not receive HO data in the validation tab, new event is created, which will allow TCW to get details from Home office
```
[ ] Yes
[ x] No
```

RIA-3390: Request Home Office data event flow

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-3155
Enable notifications to parties when appeal reinstaed
```
[ ] Yes
[ X] No
```

Ria 3155 enable notifications to parties when appeal reinstated

---

src/functionalTest/resources/scenarios/RIA-2239-judge-end-appeal.json
src/functionalTest/resources/scenarios/RIA-823-end-appeal.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EndAppealHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EndAppealHandlerTest.java

N/A
fix broken link in applications tab
```
[ ] Yes
[x] No
```

fix broken link in applications tab

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-3453
RIA-3453 enable notification for online application
```
[ ] Yes
[ X] No
```

Ria 3453 enable notifications when application online submitted

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-3454
Enable notification when an application has been decided
```
[ ] Yes
[ X] No
```

Ria 3454 notifications when application online decided

---

Jenkinsfile_CNP
build.gradle
src/contractTest/java/uk/gov/hmcts/reform/iacaseapi/IdamConsumerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/NationalityTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AutomaticDirectionRequestingHearingRequirementsHandlerTest.java

[RIA-3338](https://tools.hmcts.net/jira/browse/RIA-3338)
```
[x] Yes
[ ] No
```

RIA-3338 Configure PACT tests for IDAM

---

src/functionalTest/resources/scenarios/RIA-3652-request-new-hearing-requirements-case-officer.json
src/functionalTest/resources/scenarios/RIA-3652-request-new-hearing-requirements-errors-case-officer.json
src/functionalTest/resources/scenarios/RIA-3652-request-new-hearing-requirements-errors-judge.json
src/functionalTest/resources/scenarios/RIA-3652-request-new-hearing-requirements-judge.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DirectionTag.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestNewHearingRequirementsDirectionHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestNewHearingRequirementsDirectionPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/DirectionPartiesResolver.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/DirectionTagResolver.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DirectionTagTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestNewHearingRequirementsDirectionHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestNewHearingRequirementsDirectionPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/DirectionPartiesResolverTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/DirectionTagResolverTest.java

[RIA-3652](https://tools.hmcts.net/jira/browse/RIA-3652)
See Jira
**Please Note:** This build fails on its functional tests as it is dependent on deployment of the accompanying PR for notifications (https://github.com/hmcts/ia-case-notifications-api/pull/386) 
```
[ ] Yes
[x] No
```

Ria 3652 direction and state change ftpa decision reheard

---

src/main/resources/application.yaml

[RIA-3495](https://tools.hmcts.net/jira/browse/RIA-3495)
Timed event service health check added
```
[ ] Yes
[x] No
```

RIA-3495 health check for timed event service

---

src/functionalTest/resources/scenarios/RIA-3389-home-office-reference-formatter-letter-plus-seven-digits.json
src/functionalTest/resources/scenarios/RIA-3389-home-office-reference-formatter-without-slash.json
src/functionalTest/resources/scenarios/RIA-3389-home-office-reference-formatter.json
src/functionalTest/resources/scenarios/RIA-3680-home-office-reference-formatter.json
src/functionalTest/resources/scenarios/RIA-3680-home-office-reference-mid-event.json
src/functionalTest/resources/scenarios/RIA-3680-home-office-reference-mid-event_edit_appeal.json
src/functionalTest/resources/scenarios/RIA-730-RIA-971-home-office-truncator.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeReferenceNumberTruncator.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/StartAppealMidEvent.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeReferenceNumberTruncatorTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/StartAppealMidEventTest.java

[RIA-3680](https://tools.hmcts.net/jira/browse/RIA-3680)
```
[ ] Yes
[x] No
```

RIA-3680 Add validation for Home Office References

---

src/functionalTest/resources/scenarios/RIA-1293-ftpa-appellant-in-time-submit.json
src/functionalTest/resources/scenarios/RIA-1293-ftpa-appellant-out-of-time-submit.json
src/functionalTest/resources/scenarios/RIA-2581-ftpa-respondent-in-time-homeoffice-generic-submit.json
src/functionalTest/resources/scenarios/RIA-2581-ftpa-respondent-in-time-homeoffice-pou-submit.json
src/functionalTest/resources/scenarios/RIA-2581-ftpa-respondent-out-of-time-homeoffice-generic-submit.json
src/functionalTest/resources/scenarios/RIA-2581-ftpa-respondent-out-of-time-homeoffice-pou-submit.json

N/A
fix functional tests
```
[ ] Yes
[x] No
```

fix functional tests - add missing property

---

src/functionalTest/resources/scenarios/RIA-3582-record-agreed-hearing-requirements-ftpa-reheard.json
src/functionalTest/resources/scenarios/RIA-3582-record-agreed-hearing-requirements.json
src/functionalTest/resources/scenarios/RIA-3582-review-submit-hearing-adjustments-cleared-adjustments.json
src/functionalTest/resources/scenarios/RIA-3582-review-submit-hearing-adjustments-current-adjustments-standard-appeal.json
src/functionalTest/resources/scenarios/RIA-3582-review-submit-hearing-adjustments-current-adjustments.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/PreviousHearing.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DraftHearingRequirementsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestNewHearingRequirementsDirectionHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewDraftHearingRequirementsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/PreviousHearingTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DraftHearingRequirementsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewDraftHearingRequirementsHandlerTest.java

[RIA-3582](https://tools.hmcts.net/jira/browse/RIA-3582)
See Jira
**Please Note:** This build fails on functional tests RIA-3652 & RIA-3582 as it's dependent on deployment of the accompanying notification PR's: (hmcts/ia-case-notifications-api#386) and (hmcts/ia-case-notifications-api#394)
```
[ ] Yes
[x] No
```

Ria 3582 tcw review requirements

---

src/functionalTest/resources/scenarios/RIA-3386-list-case-ftpa-reheard-without-hearing-requirements-flag-on.json
src/functionalTest/resources/scenarios/RIA-3386-list-case-without-hearing-requirements-flag-off.json
src/functionalTest/resources/scenarios/RIA-3386-list-case-without-hearing-requirements-flag-on.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/HearingConductionOptions.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DraftHearingRequirementsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListCaseWithoutHearingRequirementsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestNewHearingRequirementsDirectionHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/HearingConductionOptionsTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DraftHearingRequirementsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListCaseWithoutHearingRequirementsHandlerTest.java

[RIA-3386](https://tools.hmcts.net/jira/browse/RIA-3386)
See Jira
```
[ ] Yes
[x] No
```

Ria 3386 reheard hearing requirements not submitted

---

src/functionalTest/resources/scenarios/RIA-3783-home-office-reference-cid-padding-edit-appeal.json
src/functionalTest/resources/scenarios/RIA-3783-home-office-reference-cid-padding.json
src/functionalTest/resources/templates/minimal-appeal-started.json
src/functionalTest/resources/templates/minimal-appeal-submitted.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeReferenceFormatter.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeReferenceFormatterTest.java

https://tools.hmcts.net/jira/browse/RIA-3783
Home Office CID reference number zero padding changes
```
[ ] Yes
[X] No
```

RIA-3783: Home Office CID reference number zero padding changes

---

src/functionalTest/resources/scenarios/RIA-3683-list-case-submit-flag-off.json
src/functionalTest/resources/scenarios/RIA-3683-list-case-submit-flag-on.json
src/functionalTest/resources/scenarios/RIA-3683-list-reheard-case-submit.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTag.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/HearingConductionOptions.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/editdocs/EditDocsAuditLogService.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListCaseWithoutHearingRequirementsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListEditCaseHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/editdocs/EditDocsAboutToSubmitHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/editdocs/EditDocsMidEventHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinitionTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTagTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/HearingConductionOptionsTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/editdocs/EditDocsAuditLogServiceTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListCaseWithoutHearingRequirementsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListEditCaseHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/editdocs/EditDocsAboutToSubmitHandlerTest.java

[RIA-3683](https://tools.hmcts.net/jira/browse/RIA-3683)
See Jira
```
[ ] Yes
[x] No
```

Ria 3683 ao lists reheard case

---

src/functionalTest/resources/scenarios/RIA-3129-create-case-summary-for-reheard.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CreateCaseSummaryHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CreateCaseSummaryPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CreateCaseSummaryHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CreateCaseSummaryPreparerTest.java

[RIA-3129](https://tools.hmcts.net/jira/browse/RIA-3129)
Create case summary as part of reheard
```
[ ] Yes
[x] No
```

RIA-3129 Create case summary has part of reheard

---

src/functionalTest/resources/scenarios/RIA-3555-RIA-3763-submit-new-hearing-requirements.json
src/functionalTest/resources/scenarios/RIA-3582-RIA-3763-review-submit-hearing-adjustments-cleared-adjustments.json
src/functionalTest/resources/scenarios/RIA-3582-RIA-3763-review-submit-hearing-adjustments-current-adjustments-standard-appeal.json
src/functionalTest/resources/scenarios/RIA-3582-RIA-3763-review-submit-hearing-adjustments-current-adjustments.json
src/functionalTest/resources/scenarios/RIA-3763-list-case-without-hearing-requirements-no-requirements-exist-flag-on.json
src/functionalTest/resources/scenarios/RIA-3763-list-case-without-hearing-requirements-single-requirements-exist-flag-on.json
src/functionalTest/resources/scenarios/RIA-3763-submit-hearing-requirements-single-requirements-exist.json
src/functionalTest/resources/scenarios/RIA-3763-submit-reheard-hearing-requirements-multiple-requirements-exist.json
src/functionalTest/resources/scenarios/RIA-3763-submit-reheard-hearing-requirements-single-requirements-exist.json
src/functionalTest/resources/scenarios/RIA-3763-update-hearing-requirements-case-officer-single-requirements-exist.json
src/functionalTest/resources/scenarios/RIA-3763-update-hearing-requirements-single-requirements-exist.json
src/functionalTest/resources/scenarios/RIA-3763-update-reheard-hearing-requirements-multiple-requirements-exist.json
src/functionalTest/resources/scenarios/RIA-3763-update-reheard-hearing-requirements-single-requirements-exist.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/PreviousHearing.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DraftHearingRequirementsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListCaseWithoutHearingRequirementsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestNewHearingRequirementsDirectionHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateHearingRequirementsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/PreviousRequirementsAndRequestsAppender.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/PreviousHearingTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DraftHearingRequirementsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListCaseWithoutHearingRequirementsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestNewHearingRequirementsDirectionHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateHearingRequirementsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/PreviousRequirementsAndRequestsAppenderTest.java

[RIA-3763](https://tools.hmcts.net/jira/browse/RIA-3763)
See Jira
```
[ ] Yes
[x] No
```

Ria 3763 remove requests and requirements from previous hearings

---

src/functionalTest/resources/scenarios/RIA-3555-RIA-3763-RIA-3784-submit-new-hearing-requirements.json
src/functionalTest/resources/scenarios/RIA-3582-RIA-3763-RIA-3784-review-submit-hearing-adjustments-cleared-adjustments.json
src/functionalTest/resources/scenarios/RIA-3582-RIA-3763-RIA-3784-review-submit-hearing-adjustments-current-adjustments-standard-appeal.json
src/functionalTest/resources/scenarios/RIA-3582-RIA-3763-RIA-3784-review-submit-hearing-adjustments-current-adjustments.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/PreviousHearing.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DraftHearingRequirementsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListCaseWithoutHearingRequirementsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestNewHearingRequirementsDirectionHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/PreviousHearingTest.java

[RIA-3784](https://tools.hmcts.net/jira/browse/RIA-3784)
See Jira
```
[ ] Yes
[x] No
```

Ria 3784 remove recordings from previous hearings

---

src/functionalTest/resources/scenarios/RIA-3130-customise-reheard-hearing-bundle-preparer.json
src/functionalTest/resources/scenarios/RIA-3130-finalBundling-to-preHearing.json
src/functionalTest/resources/scenarios/RIA-3130-generate-hearing-ready-bundle-stitching-enabled.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AdvancedBundlingCallbackHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AdvancedFinalBundlingStitchingCallbackHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CustomiseHearingBundleHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CustomiseHearingBundlePreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UploadAdditionalEvidenceHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UploadAdditionalEvidenceHomeOfficeHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/FtpaDisplayService.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AdvancedBundlingCallbackHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AdvancedFinalBundlingStitchingCallbackHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CustomiseHearingBundleHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CustomiseHearingBundlePreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UploadAdditionalEvidenceHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UploadAdditionalEvidenceHomeOfficeHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/FtpaDisplayServiceTest.java

https://tools.hmcts.net/jira/browse/RIA-3130
Final bundling to prehearing
```
[ ] Yes
[X ] No
```

Ria 3130 final bundling to pre hearing

---

src/functionalTest/resources/scenarios/RIA-3131-ftpa-reheard-prepare-decision-and-reasons-flag-on.json
src/functionalTest/resources/scenarios/RIA-3131-ftpa-reheard-start-decision-and-reasons-flag-on.json
src/functionalTest/resources/scenarios/RIA-3131-normal-case-prepare-decision-and-reasons-flag-on.json
src/functionalTest/resources/scenarios/RIA-3131-normal-case-start-decision-and-reasons-flag-on.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DecisionAndReasonsGeneratedPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DecisionAndReasonsPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DecisionAndReasonsGeneratedPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DecisionAndReasonsPreparerTest.java

[RIA-3131](https://tools.hmcts.net/jira/browse/RIA-3131)
See Jira
```
[ ] Yes
[x] No
```

Ria 3131 pre hearing to decision

---

src/functionalTest/resources/scenarios/RIA-3132-ftpa-reheard-appellant-flag-on.json
src/functionalTest/resources/scenarios/RIA-3132-ftpa-reheard-respondent-flag-on.json
src/functionalTest/resources/scenarios/RIA-3132-ftpa-reheard-send-decision-and-reasons-start.json
src/functionalTest/resources/scenarios/RIA-3132-send-decision-and-reasons-start.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaAppellantPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaRespondentPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendDecisionAndReasonsPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaAppellantPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaRespondentPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendDecisionAndReasonsPreparerTest.java

[RIA-3132](https://tools.hmcts.net/jira/browse/RIA-3132)
See Jira
```
[ ] Yes
[x] No
```

Ria 3132 decision to decided

---

src/functionalTest/resources/scenarios/RIA-3130-finalBundling-to-preHearing.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CustomiseHearingBundleHandler.java

https://tools.hmcts.net/jira/browse/RIA-3130
see jira
```
[ ] Yes
[X ] No
```

RIA-3130 restore addendum after reheard hearing generation

---

charts/ia-case-api/Chart.yaml
charts/ia-case-api/values.yaml
infrastructure/main.tf
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/controllers/PreSubmitCallbackController.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/controllers/PreSubmitCallbackControllerTest.java

[RIA-3701](https://tools.hmcts.net/jira/browse/RIA-3701)
postgresql 11 and feature flag switch
```
[ ] Yes
[x] No
```

RIA-3701 postgresql 11 and feature flag switch

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentPreparerTest.java

[RIA-3516](https://tools.hmcts.net/jira/browse/RIA-3516)
RP and DC appeal types hearing options
```
[ ] Yes
[x] No
```

RIA-3516 RP and DC appeal types hearing options

---

charts/ia-case-api/Chart.yaml
charts/ia-case-api/values.yaml
src/main/resources/bootstrap.yaml

N/A
Postgresql migration to version 11
```
[ ] Yes
[x] No
```

Postgresql migration to version 11

---

src/functionalTest/resources/scenarios/RIA-3686-submit-appeal-with-legal-aid-remission.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/RemissionType.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealReferenceNumberHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/RemissionTypeTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentHandlerTest.java

[RIA-3686](https://tools.hmcts.net/jira/browse/RIA-3686)
Legal rep submits appeal using one of the below remission types
• Section 17
• Section 20
• Home Office waiver
```
[ ] Yes
[x] No
```

RIA-3686 Legal rep submit appeal with other remission types

---

config/owasp/suppressions.xml

N/A
Suppress vulnerability irrelevant to our http client usage
```
[ ] Yes
[x] No
```

Suppress vulnerability irrelevant to our http client usage

---

src/functionalTest/resources/scenarios/RIA-3084-submit-appeal-with-help-with-fees.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSubmittedConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSubmittedConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentStateHandlerTest.java

[RIA-3084](https://tools.hmcts.net/jira/browse/RIA-3084)
Legal rep submits appeal with help with fees
```
[ ] Yes
[x] No
```

RIA-3084 Legal rep submits appeal with help with fees

---

src/functionalTest/resources/scenarios/RIA-1925-upload-decision-letter.json
src/functionalTest/resources/scenarios/RIA-3085-submit-appeal-with-exceptional-circumstances-remission.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/RemissionType.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSubmittedConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/RemissionTypeTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSubmittedConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentPreparerTest.java

RIA-3085: Legal rep submits appeal with Exceptional circumstances remission for fees
https://tools.hmcts.net/jira/browse/RIA-3085
```
[ ] Yes
[ x] No
```

RIA-3085: Legal rep submits appeal with Exceptional circumstances remission for fees

---

src/functionalTest/resources/scenarios/RIA-3517-record-remission-decision-partially-approved.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

Ria 3690 
remission decision notification
```
[ ] Yes
[x] No
```

Ria 3690 remission decision notification

---

build.gradle

N/A
update Tomcat version
```
[ ] Yes
[x] No
```

update Tomcat version

---

src/functionalTest/resources/scenarios/RIA-2935-EA-appeal-fee-pay-later-hearing.json
src/functionalTest/resources/scenarios/RIA-2935-EA-appeal-fee-pay-later-without-hearing.json
src/functionalTest/resources/scenarios/RIA-2935-EA-appeal-fee-pay-now-hearing.json
src/functionalTest/resources/scenarios/RIA-2935-EA-appeal-fee-pay-now-without-hearing.json
src/functionalTest/resources/scenarios/RIA-3025-successful-payment-for-pa-appeal-type-at-case-building.json
src/functionalTest/resources/scenarios/RIA-3025-successful-payment-for-pa-appeal-type-at-listing.json
src/functionalTest/resources/scenarios/RIA-3082-EA-failed-payment-account-deleted-pay-now-with-hearing.json
src/functionalTest/resources/scenarios/RIA-3082-EA-failed-payment-account-deleted-pay-now-without-hearing.json
src/functionalTest/resources/scenarios/RIA-3082-EA-failed-payment-account-on-hold-pay-now-with-hearing.json
src/functionalTest/resources/scenarios/RIA-3082-EA-successful-payment-pay-now-with-hearing.json
src/functionalTest/resources/scenarios/RIA-3082-EA-successful-payment-pay-now-without-hearing.json
src/functionalTest/resources/scenarios/RIA-3082-HU-failed-payment-account-on-hold-pay-now-with-hearing.json
src/functionalTest/resources/scenarios/RIA-3082-PA-failed-payment-account-deleted-pay-now-without-hearing.json
src/functionalTest/resources/scenarios/RIA-3163-PA-failed-payment-account-deleted-respondent-review-state.json
src/functionalTest/resources/scenarios/RIA-3163-PA-failed-payment-account-on-hold-listing-state.json
src/functionalTest/resources/scenarios/RIA-3163-PA-successful-payment-case-building-state.json.json
src/functionalTest/resources/scenarios/RIA-3412-pay-and-submit-appeal.json
src/functionalTest/resources/scenarios/RIA-3468-pa-appeal-type-pay-now.json
src/functionalTest/resources/scenarios/RIA-3471-ea-appeal-type-pay-now-ou-of-time.json
src/functionalTest/resources/scenarios/RIA-3471-hu-appeal-type-pay-now-ou-of-time.json
src/functionalTest/resources/scenarios/RIA-3471-pa-appeal-type-pay-now-ou-of-time.json
src/functionalTest/resources/scenarios/RIA-3473-mark-hu-appeal-as-paid.json
src/functionalTest/resources/scenarios/RIA-3473-mark-pa-appeal-as-paid.json
src/functionalTest/resources/scenarios/RIA-3517-record-remission-decision-approved-validation.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordRemissionDecisionMidEvent.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordRemissionDecisionMidEventTest.java

Elastic search issue fixed by amending feeAmount case field to feeAmountGbp
```
[ ] Yes
[x] No
```

Amended feeAmount case field to feeAmountGbp

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordRemissionDecisionStateHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeePaymentHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordRemissionDecisionStateHandlerTest.java

[RIA-3829](https://tools.hmcts.net/jira/browse/RIA-3829)
Overview tabs for Record remission decision updated
```
[ ] Yes
[x] No
```

RIA-3829 Record remission decision overview tabs

---

charts/ia-case-api/Chart.yaml
charts/ia-case-api/values.yaml
infrastructure/main.tf
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/controllers/PreSubmitCallbackController.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/controllers/PreSubmitCallbackControllerTest.java

[RIA-3849](https://tools.hmcts.net/jira/browse/RIA-3849)
cleanup after migration to Postgresql 11
```
[ ] Yes
[x] No
```

RIA-3849 cleanup after migration to Postgresql 11

---

build.gradle
config/owasp/suppressions.xml

RIA-3885:Fix mutation test
https://tools.hmcts.net/jira/browse/RIA-3885
```
[ ] Yes
[ x] No
```

RIA-3885:Fix mutation test

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/health/ServiceHealthIndicator.java

RIA-3736:Add URI to health check exception log
https://tools.hmcts.net/jira/browse/RIA-3736
```
[ ] Yes
[ x] No
```

RIA-3736:Add URI to health check exception log

---

src/functionalTest/resources/scenarios/RIA-3308-home-office-notifications-for-request_respondent_evidence-multiple-nationalities.json
src/functionalTest/resources/scenarios/RIA-3308-home-office-notifications-for-request_respondent_evidence-stateless.json
src/functionalTest/resources/scenarios/RIA-3308-home-office-notifications-for-request_respondent_evidence.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseNotificationsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseNotificationsHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-3308
Changes to trigger HomeOffice notifications for request-evidence-bundle event
```
[ ] Yes
[X] No
```

RIA-3308: Changes to trigger HomeOffice notifications for request-evidence-bundle event

---

src/functionalTest/resources/scenarios/RIA-3600-home-office-notifications-for-request_respondent_review.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseNotificationsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseNotificationsHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-3600
changes to trigger request review notification to Home Office
```
[ ] Yes
[X] No
```

Ria 3600 request review notification

---

src/functionalTest/resources/scenarios/RIA-3306-home-office-notifications-for-case-listing.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseNotificationsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseNotificationsHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-3306
changes to trigger HO notification on listing a case
```
[ ] Yes
[X] No
```

Ria 3306 hearing notification

---

src/functionalTest/resources/scenarios/RIA-3309-ho-notifications-for-edit-case-listing-decision.json
src/functionalTest/resources/scenarios/RIA-3309-ho-notifications-for-edit-case-listing-finalbundling.json
src/functionalTest/resources/scenarios/RIA-3309-ho-notifications-for-edit-case-listing-prehearing.json
src/functionalTest/resources/scenarios/RIA-3309-ho-notifications-for-edit-case-listing-prepareforhearing.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseNotificationsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseNotificationsHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-3309
RIA-3309 ho hearing
```
[ ] Yes
[X] No
```

Ria 3309 ho hearing

---

src/functionalTest/resources/scenarios/RIA-3316-ho-notifications-for-edit-adjourn-no-date-decision.json
src/functionalTest/resources/scenarios/RIA-3316-ho-notifications-for-edit-adjourn-no-date-finalbundling.json
src/functionalTest/resources/scenarios/RIA-3316-ho-notifications-for-edit-adjourn-no-date-prehearing.json
src/functionalTest/resources/scenarios/RIA-3316-ho-notifications-for-edit-adjourn-no-date-prepareforhearing.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseNotificationsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseNotificationsHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-3316
RIA-3316 Adjourn with no hearing date
```
[ ] Yes
[X] No
```

Ria 3316 no hearing date

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AdjournWithoutDateConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/EditCaseListingConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ListCaseConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RequestRespondentEvidenceConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RequestRespondentReviewConfirmation.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AdjournWithoutDateConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/EditCaseListingConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ListCaseConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RequestRespondentEvidenceConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RequestRespondentReviewConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseNotificationsHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-3601
Notification failure confirmation message on errors
```
[ ] Yes
[X] No
```

Ria 3601 notifications retry

---

src/functionalTest/resources/scenarios/RIA-3314-send-decision-reasons-failure-confirmation-adminofficer.json
src/functionalTest/resources/scenarios/RIA-3314-send-decision-reasons-failure-confirmation-caseofficer.json
src/functionalTest/resources/scenarios/RIA-3314-send-decision-reasons-failure-confirmation-judge.json
src/functionalTest/resources/scenarios/RIA-3314-send-decision-reasons-success-confirmation-judge.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/SendDecisionAndReasonsConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseNotificationsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/SendDecisionAndReasonsConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseNotificationsHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-3314
trigger Home Office decided notification and notification failure message
```
[ ] Yes
[X] No
```

Ria 3314 decided notification

---

src/functionalTest/resources/scenarios/RIA-3305-ho-notifications-for-async-stitching-complete.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AdvancedFinalBundlingStitchingCallbackHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AdvancedFinalBundlingStitchingCallbackHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-3305
RIA-3305 hearing bundle ready
```
[ ] Yes
[X] No
```

Ria 3305 hearing bundle ready

---

src/functionalTest/resources/scenarios/RIA-3313-ftpa-appellant-notification-decided.json
src/functionalTest/resources/scenarios/RIA-3313-ftpa-appellant-notification-ftpa-decided.json
src/functionalTest/resources/scenarios/RIA-3313-ftpa-appellant-notification-ftpa-submitted.json
src/functionalTest/resources/scenarios/RIA-3313-ftpa-respondent-notification-homeoffice-generic-decided.json
src/functionalTest/resources/scenarios/RIA-3313-ftpa-respondent-notification-homeoffice-generic-ftpa-decided.json
src/functionalTest/resources/scenarios/RIA-3313-ftpa-respondent-notification-homeoffice-generic-ftpa-submitted.json
src/functionalTest/resources/scenarios/RIA-3313-ftpa-respondent-notification-homeoffice-pou-decided.json
src/functionalTest/resources/scenarios/RIA-3313-ftpa-respondent-notification-homeoffice-pou-ftpa-decided.json
src/functionalTest/resources/scenarios/RIA-3313-ftpa-respondent-notification-homeoffice-pou-ftpa-submitted.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseNotificationsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseNotificationsHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-3313
trigger home office notification when FTPA submitted 
```
[ ] Yes
[X] No
```

Ria 3313 ftpa submitted notification

---

src/functionalTest/resources/scenarios/RIA-3307-leadership-judge-record-appellant-ftpa-decision-ho-notification.json
src/functionalTest/resources/scenarios/RIA-3307-leadership-judge-record-appellant-ftpa-decision-notification-failed-confirmation.json
src/functionalTest/resources/scenarios/RIA-3307-leadership-judge-respondent-ftpa-decision-ho-notification.json
src/functionalTest/resources/scenarios/RIA-3307-resident-judge-appellant-ftpa-decision-ho-notification-remade-allowed.json
src/functionalTest/resources/scenarios/RIA-3307-resident-judge-appellant-ftpa-decision-ho-notification.json
src/functionalTest/resources/scenarios/RIA-3307-resident-judge-record-appellant-ftpa-decision-notification-failed-confirmation.json
src/functionalTest/resources/scenarios/RIA-3307-resident-judge-respondent-ftpa-decision-ho-notification-remade-dismissed.json
src/functionalTest/resources/scenarios/RIA-3307-resident-judge-respondent-ftpa-decision-ho-notification.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/LeadershipJudgeFtpaDecisionConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ResidentJudgeFtpaDecisionConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseNotificationsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/LeadershipJudgeFtpaDecisionConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ResidentJudgeFtpaDecisionConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseNotificationsHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-3307
ftpa decided notification trigger
```
[ ] Yes
[X] No
```

Ria 3307 ftpa decided notification

---

src/functionalTest/resources/scenarios/RIA-3302-end-appeal-failure-confirmation-admin.json
src/functionalTest/resources/scenarios/RIA-3302-end-appeal-failure-confirmation-caseofficer.json
src/functionalTest/resources/scenarios/RIA-3302-end-appeal-failure-confirmation-judge.json
src/functionalTest/resources/scenarios/RIA-3302-end-appeal-success-confirmation-admin.json
src/functionalTest/resources/scenarios/RIA-3302-end-appeal-success-confirmation-caseofficer.json
src/functionalTest/resources/scenarios/RIA-3302-end-appeal-success-confirmation-judge.json
src/functionalTest/resources/scenarios/RIA-3302-ho-notifications-for-end-appeal-with-appeal-submitted-co.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/EndAppealConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseNotificationsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/EndAppealConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseNotificationsHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-3302
RIA-3302_ho_end_appeal
```
[ ] Yes
[X] No
```

Ria 3302 ho end appeal

---

src/functionalTest/resources/scenarios/RIA-3691-home-office-notification-failure-send-direction-confirmation.json
src/functionalTest/resources/scenarios/RIA-3691-home-office-notification-success-send-direction-confirmation-legal-rep.json
src/functionalTest/resources/scenarios/RIA-3691-home-office-notification-success-send-direction-confirmation.json
src/functionalTest/resources/scenarios/RIA-3691-home-office-notifications-for-amend-bundle-send_direction.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/SendDirectionConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseNotificationsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/SendDirectionConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseNotificationsHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-3691
RIA-3961 ho amend bundle
```
[ ] Yes
[X] No
```

Ria 3961 ho amend bundle

---

src/functionalTest/resources/scenarios/RIA-3692-home-office-notification-amend-response-for-respondent-review.json
src/functionalTest/resources/scenarios/RIA-3692-home-office-notification-failure-amend-response-confirmation.json
src/functionalTest/resources/scenarios/RIA-3692-home-office-notification-success-amend-response-confirmation.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RequestResponseAmendConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseNotificationsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RequestResponseAmendConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseNotificationsHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-3692
RIA-3692 ho amend response
```
[ ] Yes
[X] No
```

Ria 3692 ho amend response

---

src/functionalTest/resources/scenarios/RIA-3039-end-appeal-state-saved-for-reinstate.json
src/functionalTest/resources/scenarios/RIA-3039-reinstate-ended-appeal-to-previous-state.json
src/functionalTest/resources/scenarios/RIA-3693-ho-notifications-for-change-direction-due-date-awaitingRespondentEvidence.json
src/functionalTest/resources/scenarios/RIA-3693-ho-notifications-for-change-direction-due-date-requestRespondentReview.json
src/functionalTest/resources/scenarios/RIA-3693-ho-notifications-for-failure-confirmation-change-direction-due-date-evidence.json
src/functionalTest/resources/scenarios/RIA-3693-ho-notifications-for-failure-confirmation-change-direction-due-date-review.json
src/functionalTest/resources/scenarios/RIA-3693-ho-notifications-for-success-confirmation-change-direction-due-date-evidence.json
src/functionalTest/resources/scenarios/RIA-3693-ho-notifications-for-success-confirmation-change-direction-due-date-review.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ChangeDirectionDueDateConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseNotificationsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ChangeDirectionDueDateConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseNotificationsHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-3693
RIA-3693 ho direction due date
```
[ ] Yes
[X] No
```

Ria 3693 ho direction due date

---

src/functionalTest/resources/scenarios/RWA-318-Allocate-a-case-to-caseworker-about-to-submit.json
src/functionalTest/resources/scenarios/RWA-318-Allocate-a-case-to-caseworker-midevent.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/CaseDetails.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/roleassignment/Assignment.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/roleassignment/Attributes.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/roleassignment/QueryRequest.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/roleassignment/RequestedRoles.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/roleassignment/RoleAssignment.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/roleassignment/RoleAssignmentResource.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/roleassignment/RoleName.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/roleassignment/RoleRequest.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordApplicationHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/allocatecase/AllocateTheCaseHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/allocatecase/AllocateTheCaseMidEventHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/PreSubmitCallbackDispatcher.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/RoleAssignmentApi.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/RoleAssignmentService.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/CaseDetailsTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AdjournWithoutDateConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AllocateTheCaseHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestCaseBuildingHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/allocatecase/AllocateTheCaseHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/allocatecase/AllocateTheCaseMidEventHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/RoleAssignmentServiceTest.java

https://tools.hmcts.net/jira/browse/RWA-318

AC4: populate dynamic list with the list of caseworkers ids for now.

---

src/functionalTest/resources/scenarios/RWA-318-Allocate-a-case-to-caseworker-about-to-submit.json
src/functionalTest/resources/scenarios/RWA-318-Allocate-a-case-to-caseworker-confirmation-page.json
src/functionalTest/resources/scenarios/RWA-318-Allocate-a-case-to-caseworker-midevent.json
src/functionalTest/resources/scenarios/RWA-318-Allocate-a-case-to-caseworker.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/CaseDetails.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/roleassignment/Assignment.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/roleassignment/Attributes.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/roleassignment/QueryRequest.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/roleassignment/RequestedRoles.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/roleassignment/RoleAssignment.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/roleassignment/RoleAssignmentResource.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/roleassignment/RoleName.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/roleassignment/RoleRequest.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordApplicationHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/allocatecase/AllocateTheCaseHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/allocatecase/AllocateTheCaseMidEventHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/allocatecase/DisableAllocateTheCaseHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/PreSubmitCallbackDispatcher.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/RoleAssignmentApi.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/RoleAssignmentService.java
src/main/resources/application-local.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/CaseDetailsTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AdjournWithoutDateConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AllocateTheCaseHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DisableAllocateTheCaseHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestCaseBuildingHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/allocatecase/AllocateTheCaseHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/allocatecase/AllocateTheCaseMidEventHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/RoleAssignmentServiceTest.java

https://tools.hmcts.net/jira/browse/RWA-318

RWA-318 Allocate a case to a user (CCD event)- Part 2

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseNotificationsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseNotificationsHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-3693
Fixed merge issues
```
[ ] Yes
[X] No
```

RIA-3693: Fixed merge issues

---

src/functionalTest/resources/scenarios/RIA-3039-reinstate-ended-appeal-to-previous-state.json
src/functionalTest/resources/scenarios/RIA-3039-reinstate-error-if-not-ended-appeal.json
src/functionalTest/resources/scenarios/RIA-3451-case-officer-decide-an-application.json
src/functionalTest/resources/scenarios/RIA-3451-judge-decide-an-application.json
src/functionalTest/resources/scenarios/RIA-3457-legal-rep-make-an-application.json
src/functionalTest/resources/scenarios/RIA-3457-respondent-make-an-application.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DecideAnApplicationHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DecideAnApplicationMidEvent.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DecideAnApplicationPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MakeAnApplicationHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MakeAnApplicationMidEvent.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MakeAnApplicationPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReinstateAppealStateHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DecideAnApplicationHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DecideAnApplicationMidEventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DecideAnApplicationPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MakeAnApplicationHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MakeAnApplicationMidEventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MakeAnApplicationPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReinstateAppealStateHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-3815
RIA-3815
```
[ ] Yes
[ X] No
```

RIA-3815 cleanup reinstate and make an application feature flag

---

src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/RWA-319

RWA-319 point role-assignment to ia-docker wiremock by default

---

src/functionalTest/resources/scenarios/RIA-892-RIA-2694-request-respondent-evidence-start.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestRespondentEvidencePreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestRespondentEvidencePreparerTest.java

https://tools.hmcts.net/jira/browse/RIA-3821
RIA-3821 ooc bundle_direction)
```
[ ] Yes
[X] No
```

RIA-3821_ooc_bundle_direction

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestRespondentReviewPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestRespondentReviewPreparerTest.java

https://tools.hmcts.net/jira/browse/RIA-3836
RIA-3836 ooc_content
```
[ ] Yes
[X] No
```

RIA-3836_ooc_content

---

src/functionalTest/resources/scenarios/RIA-1794-RIA-2694-request-response-review.json
src/functionalTest/resources/scenarios/RIA-697-RIA-237-RIA-985-RIA-2694-add-appeal-response-initial.json
src/functionalTest/resources/scenarios/RIA-697-RIA-237-RIA-985-RIA-2694-add-appeal-response-replace.json
src/functionalTest/resources/scenarios/RIA-837-RIA-2694-send-legal-rep-review-direction.json
src/functionalTest/resources/scenarios/RIA-921-automatic-direction.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AutoLegalRepresentativeReviewDirectionHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestResponseReviewHandler.java

https://tools.hmcts.net/jira/browse/RIA-3838
RIA-3838 ooc_content
```
[ ] Yes
[X] No
```

RIA-3838_ooc_content

---

src/functionalTest/resources/scenarios/RIA-2047-RIA-2694-direction-to-request-hearing-requirements.json
src/functionalTest/resources/scenarios/RIA-2048-RIA-2694-request-hearing-requirements-legal-rep.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestHearingRequirementsDirectionHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestHearingRequirementsDirectionTest.java

https://tools.hmcts.net/jira/browse/RIA-3839
RIA-3839 ooc content for Submit Hearing Requirements direction
```
[ ] Yes
[X] No
```

RIA-3839_ooc_content

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestNewHearingRequirementsDirectionHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestNewHearingRequirementsDirectionPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestNewHearingRequirementsDirectionPreparerTest.java

https://tools.hmcts.net/jira/browse/RIA-3840
RIA-3840 ooc content Reheard Submit Hearing Requirements
```
[ ] Yes
[X] No
```

RIA-3840_ooc_content

---

src/functionalTest/resources/scenarios/RIA-480-RIA-600-build-case-confirmation-feature-disabled.json
src/functionalTest/resources/scenarios/RIA-517-case-submitted-confirmation-feature-disabled.json
src/functionalTest/resources/scenarios/RIA-517-case-submitted-confirmation-feature-enabled.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/CaseSubmittedConfirmation.java

https://tools.hmcts.net/jira/browse/RIA-3841
RIA-3841 ooc content build case
```
[ ] Yes
[X] No
```

RIA-3841_ooc_content

---

Jenkinsfile_CNP
Jenkinsfile_nightly
Jenkinsfile_parameterized
charts/ia-case-api/values.preview.template.yaml
src/functionalTest/resources/scenarios/RIA-3846-do-not-set-organisation-policy-start-appeal-flag-off.json
src/functionalTest/resources/scenarios/RIA-3846-set-organisation-policy-start-appeal-flag-on.json
src/functionalTest/resources/scenarios/RIA-815-appeal-saved-confirmation-start.json
src/integrationTest/java/uk/gov/hmcts/reform/iacaseapi/component/NewShareACaseCcdIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/iacaseapi/component/ShareACaseRefDataIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/iacaseapi/component/testutils/SpringBootIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/iacaseapi/component/testutils/WithAcaAssignmentsStub.java
src/integrationTest/java/uk/gov/hmcts/reform/iacaseapi/component/testutils/WithCcdAssignmentsStub.java
src/integrationTest/java/uk/gov/hmcts/reform/iacaseapi/component/testutils/WithReferenceDataStub.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ref/OrganisationEntityResponse.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSavedConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealReferenceNumberHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LegalRepOrganisationFormatter.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/CcdCaseAssignment.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/ProfessionalOrganisationRetriever.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/model/ccd/Organisation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/model/ccd/OrganisationPolicy.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSavedConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealReferenceNumberHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LegalRepOrganisationFormatterTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/CcdCaseAssignmentTest.java
wiremock/mappings/wiremock-refdata-organisation-mappings.json

[RIA-3845](https://tools.hmcts.net/jira/browse/RIA-3845)
See Jira
```
[ ] Yes
[x] No
```

Ria 3845 setup initial permission

---

charts/ia-case-api/Chart.yaml
charts/ia-case-api/values.yaml

[RIA-3845](https://tools.hmcts.net/jira/browse/RIA-3845)
Added missing AAC url and accompanying chart bump
```
[ ] Yes
[x] No
```

RIA-3845 missing AAC url and chart bump

---

src/functionalTest/resources/scenarios/RIA-3848-share-case-org-policy-validation.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ShareACaseUserListPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ShareACaseUserListPreparerTest.java

RIA-3848
RIA-3848 Org Policy check for old cases
```
[ ] Yes
[x] No
```

RIA-3848 Org Policy check for old cases

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/LegRepAddressUk.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ref/OrganisationEntityResponse.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LegalRepOrganisationFormatter.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/ProfessionalOrganisationRetriever.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LegalRepOrganisationFormatterTest.java

N/A
fix Ref Data issue + adding more logs
```
[ ] Yes
[x] No
```

fix Ref Data issue + adding more logs

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/LegRepAddressUk.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/LegRepAddressUkTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LegalRepOrganisationFormatterTest.java

N/A
Ref Data fix removal of dxAddress
```
[ ] Yes
[x] No
```

Ref Data fix removal of dxAddress

---

src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/roleassignment/AssignmentTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/roleassignment/RequestedRolesTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/roleassignment/RoleNameTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/roleassignment/RoleRequestTest.java

N/A
add mutation tests
```
[ ] Yes
[x] No
```

add mutation tests

---

charts/ia-case-api/Chart.yaml

[RIA-3710](https://tools.hmcts.net/jira/browse/RIA-3710)
```
[ ] Yes
[x] No
```

RIA-3710 Migrate to Helm charts v2

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ref/OrganisationEntityResponse.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSavedConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LegalRepOrganisationFormatter.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/ProfessionalOrganisationRetriever.java

N/A
Additional ID logging for our PRD endpoint call. 
```
[ ] Yes
[x] No
```

Additional id logging for different PRD endpoints

---

src/functionalTest/resources/scenarios/RIA-2240-change-direction-due-date-submit-judge.json
src/functionalTest/resources/scenarios/RIA-602-RIA-723-change-direction-due-date-submit.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ChangeDirectionDueDateHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ChangeDirectionDueDateHandlerTest.java

[RIA-4029](https://tools.hmcts.net/jira/browse/RIA-4029)
```
[ ] Yes
[x] No
```

RIA-4029 TCW can't change a direction due date

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DirectionHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewAmendDirectionHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DirectionHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewAmendDirectionHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-3749
RIA-3749 - HO notification note missing for RIA-3692
```
[ ] Yes
[X] No
```

Ria 3749 direction

---

build.gradle
config/owasp/suppressions.xml
src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/util/LaunchDarklyFunctionalTestClient.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/LaunchDarklyFeatureToggler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/config/FeatureToggleConfiguration.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UploadSensitiveDocsAboutToSubmitHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/LaunchDarklyFeatureTogglerTest.java

[RIA-4054](https://tools.hmcts.net/jira/browse/RIA-4054)
```
[ ] Yes
[x] No
```

RIA-4054 Upgrade launchdarkly version to 5.2.2 and Guava to 30.0

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/CcdCaseAssignment.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/CcdCaseAssignmentTest.java

N/A
Additional Case ID logging for CCD and AAC endpoint calls invoked during Share a Case.
```
[ ] Yes
[x] No
```

Case id logging for CCD and AAC api calls

---

src/functionalTest/resources/scenarios/RIA-3792-manage-fee-update-of-fee-update-recorded.json
src/functionalTest/resources/scenarios/RIA-3792-manage-fee-update-of-refund-approved.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ManageFeeUpdateConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdateHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdatePreparer.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ManageFeeUpdateConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdateHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdatePreparerTest.java

[RIA-3792](https://tools.hmcts.net/jira/browse/RIA-3792)
Case-officer and Admin-officer manage fee update
```
[ ] Yes
[x] No
```

RIA-3792 Case-officer and Admin-officer manage fee update

---

src/functionalTest/resources/scenarios/RIA-3792-manage-fee-update-of-fee-update-recorded.json
src/functionalTest/resources/scenarios/RIA-3792-manage-fee-update-of-refund-approved.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdateHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdatePreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdateHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdatePreparerTest.java

[RIA-3790](https://tools.hmcts.net/jira/browse/RIA-3790)
Manage fee update with option feeUpdateRecorded for Case-officer and Admin-officer
```
[ ] Yes
[x] No
```

RIA-3790 Manage fee update with option feeUpdateRecorded

---

src/contractTest/java/uk/gov/hmcts/reform/iacaseapi/IdamConsumerTest.java

[RIA-3950](https://tools.hmcts.net/jira/browse/RIA-3950)
```
[ ] Yes
[x] No
```

RIA-3950 resolve issues with idam-api pact test

---

src/functionalTest/resources/scenarios/RIA-4026-appeal-submitted-with-belfast-postcode.json
src/main/resources/application-postcodes.yaml

[RIA-4026](https://tools.hmcts.net/jira/browse/RIA-4026)
Belfast postcodes defaulted to Glasgow hearing centre
```
[ ] Yes
[x] No
```

RIA-4026 Belfast postcodes defaulted to Glasgow hearing centre

---

src/functionalTest/resources/scenarios/RIA-3876-out-of-country-screening-no-start-appeal.json
src/functionalTest/resources/scenarios/RIA-3876-out-of-country-screening-start-appeal.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryPreparerTest.java

RIA-3876:Add out of country screen in start appeal
https://tools.hmcts.net/jira/browse/RIA-3876
```
[ ] Yes
[ x] No
```

RIA-3876:Add out of country screen in start appeal

---

src/functionalTest/resources/scenarios/RIA-3861-out-of-country-non-sponsor-client-left-country.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java

https://tools.hmcts.net/jira/browse/RIA-3861
RIA-3861 OOC appeal - no sponsor-Refuse a HR or protection claim
```
[ ] Yes
[X] No
```

Ria 3861 ooc refuse

---

src/functionalTest/resources/scenarios/RIA-3851-ooc-no-sponsor-company-address-derive-hearing-center.json
src/functionalTest/resources/scenarios/RIA-3851-ooc-no-sponsor-no-company-address-default-hearing-center.json
src/functionalTest/resources/scenarios/RIA-3851-ooc-sponsor-address-derive-hearing-center.json
src/functionalTest/resources/scenarios/RIA-3851-out-of-country-sponsor-start-appeal.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DeriveHearingCentreHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DeriveHearingCentreHandlerTest.java

RIA-3851: Add sponsor for OOC
https://tools.hmcts.net/jira/browse/RIA-3851
```
[ ] Yes
[x ] No
```

RIA-3851: Add sponsor for OOC

---

src/functionalTest/resources/scenarios/RIA-3954-ftpa-appellant-in-time-flag-off-submit-ooc.json
src/functionalTest/resources/scenarios/RIA-3954-ftpa-appellant-out-of-time-flag-on-submit-ooc.json
src/functionalTest/resources/scenarios/RIA-3954-ftpa-respondent-in-time-flag-set-homeoffice-generic-ooc.json
src/functionalTest/resources/scenarios/RIA-3954-ftpa-respondent-out-of-time-flag-set-homeoffice-generic-ooc.json
src/functionalTest/resources/scenarios/RIA-3954-out-of-country-submission-in-time-for-refusal-of-human-rights.json
src/functionalTest/resources/scenarios/RIA-3954-out-of-country-submission-out-of-time-for-refusal-of-human-rights.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EditAppealAfterSubmitHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaAppellantPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaRespondentPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeDecisionDateChecker.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/OutOfCountryDecisionTypeTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EditAppealAfterSubmitHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaAppellantPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FtpaRespondentPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeDecisionDateCheckerTest.java

https://tools.hmcts.net/jira/browse/RIA-3954
See ticket
```
[ ] Yes
[ X] No
```

Ria 3954 ooc out of time

---

src/functionalTest/resources/scenarios/RIA-3878-out-of-country-edit-appeal-to-in-country.json
src/functionalTest/resources/scenarios/RIA-3878-out-of-country-edit-appeal-to-out-country.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealGroundsForDisplayFormatter.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryEditAppealHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryEditAppealHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryPreparerTest.java

RIA-3878: Edit appeal for Out of country appeal
https://tools.hmcts.net/jira/browse/RIA-3878
```
[ ] Yes
[x ] No
```

RIA-3878: Edit appeal for Out of country appeal

---

src/functionalTest/resources/scenarios/RIA-3827-add_appeal-response-ooc-appeal.json
src/functionalTest/resources/scenarios/RIA-3827-add_appeal-response-uk-appeal.json
src/functionalTest/resources/scenarios/RIA-3827-request-response-review-ooc-appeal.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AutoLegalRepresentativeReviewDirectionHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AutomaticDirectionRequestingHearingRequirementsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestResponseReviewHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AutoLegalRepresentativeReviewDirectionHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AutomaticDirectionRequestingHearingRequirementsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestResponseReviewHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-3827
RIA-3827 - ooc content change on time event
```
[ ] Yes
[X] No
```

RIA-3827_ooc_content

---

build.gradle
config/owasp/suppressions.xml

N/A
HMCTS java gradle plugin + removing suppressions
```
[ ] Yes
[x] No
```

HMCTS java gradle plugin + removing suppressions

---

src/integrationTest/java/uk/gov/hmcts/reform/iacaseapi/entities/AssignmentTest.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/roleassignment/ActorIdType.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/roleassignment/Classification.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/roleassignment/GrantType.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/roleassignment/RoleCategory.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/roleassignment/RoleType.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/config/JacksonConfiguration.java

https://tools.hmcts.net/jira/browse/RWA-391
Handling unknown values from RoleAssignment Service response
```
[ ] Yes
[x] No
```

Rwa 391 role assignment

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/allocatecase/AllocateTheCaseToCaseWorkerHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/allocatecase/AllocateTheCaseToMeHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/allocatecase/AllocateTheCaseToCaseWorkerHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/allocatecase/AllocateTheCaseToMeHandlerTest.java

https://tools.hmcts.net/jira/browse/RWA-405

clear field from the case to reset values

---

build.gradle
config/owasp/suppressions.xml
src/functionalTest/resources/scenarios/RIA-3313-ftpa-appellant-notification-decided.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/Application.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/controllers/PostSubmitCallbackController.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/controllers/PreSubmitCallbackController.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/controllers/WelcomeController.java

[RIA-4070](https://tools.hmcts.net/jira/browse/RIA-4070)
```
[ ] Yes
[x] No
```

RIA-4070 Upgrade guava version 30.0

---

src/functionalTest/resources/scenarios/RIA-3313-ftpa-appellant-notification-decided.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AdvancedFinalBundlingStitchingCallbackHandler.java

https://tools.hmcts.net/jira/browse/RIA-3305
RIA-3305 ho_Stitching_complete_fix
```
[ ] Yes
[X] No
```

RIA-3305_ho_Stitching_complete_fix

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryEditAppealHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryHandler.java

Additional logs added for Out Of Country handlers for traceability
```
[ ] Yes
[X] No
```

Additional logs added for Out Of Country handlers for traceability

---

src/contractTest/java/uk/gov/hmcts/reform/iacaseapi/consumer/ccd/CcdCaseAssignmentProviderBaseTest.java
src/functionalTest/resources/scenarios/RIA-3731-remove-representation-cor.json
src/functionalTest/resources/scenarios/RIA-3731-remove-representation.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/field/ChangeOrganisationRequest.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RemoveRepresentationConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/SendPostNotificationHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RemoveRepresentationPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/PostSubmitCallbackDispatcher.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/CcdCaseAssignment.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RemoveRepresentationConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LegalRepOrganisationFormatterTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RemoveRepresentationPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/PostSubmitCallbackDispatcherTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/AsylumCasePostNotificationApiSenderTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/CcdCaseAssignmentTest.java

[RIA-3731](https://tools.hmcts.net/jira/browse/RIA-3731)
See Jira
```
[ ] Yes
[x] No
```

Ria 3731 remove representation

---

src/functionalTest/resources/scenarios/RIA-3951-remove-legal-representative-ao-cor.json
src/functionalTest/resources/scenarios/RIA-3951-remove-legal-representative-ao.json
src/functionalTest/resources/scenarios/RIA-3951-remove-legal-representative-tcw-cor.json
src/functionalTest/resources/scenarios/RIA-3951-remove-legal-representative-tcw.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RemoveRepresentationConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RemoveRepresentationPreparer.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RemoveRepresentationConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RemoveRepresentationPreparerTest.java

[RIA-3951](https://tools.hmcts.net/jira/browse/RIA-3951)
See Jira
```
[ ] Yes
[x] No
```

Ria 3951 remove legal rep

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/RoleAssignmentService.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/RoleAssignmentServiceTest.java

https://tools.hmcts.net/jira/browse/RWA-469

update role category to use LEGAL_OPERATIONS rather than STAFF

---

.github/workflows/swagger.yml
src/functionalTest/resources/scenarios/RIA-3218-apply-for-a-late-remission.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RequestFeeRemissionConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestFeeRemissionHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestFeeRemissionPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/RemissionDetailsAppender.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RequestFeeRemissionConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestFeeRemissionHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestFeeRemissionPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

[RIA-3218](https://tools.hmcts.net/jira/browse/RIA-3218)
Legal rep apply for a late remission
```
[ ] Yes
[x] No
```

RIA-3218 Legal rep apply for a late remission

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/allocatecase/AllocateTheCaseToCaseWorkerMidEventHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/CaseWorkerService.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/RoleAssignmentService.java

add more logging for issue 469

---

src/functionalTest/resources/scenarios/RIA-3830-record-remission-decision-for-late-remission.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MarkPaymentPaidPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordRemissionDecisionPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestFeeRemissionPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MarkPaymentPaidPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordRemissionDecisionPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestFeeRemissionHandlerTest.java

[RIA-3830](https://tools.hmcts.net/jira/browse/RIA-3830)
Admin officer records remission decision for a late remission
```
[ ] Yes
[x] No
```

RIA-3830 Admin officer records remission decision for a late remission

---

src/contractTest/java/uk/gov/hmcts/reform/iacaseapi/consumer/roleassignment/RoleAssignmentApiConsumerTest.java

TA-529: Disable RoleAssignmentApiConsumerTest

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdateMidEvent.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MarkPaymentPaidPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordRemissionDecisionPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdateMidEventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MarkPaymentPaidPreparerTest.java

[RIA-3794](https://tools.hmcts.net/jira/browse/RIA-3794)
As a case-officer manage fee update for fee remission changed.
```
[ ] Yes
[x] No
```

RIA-3794 Manage fee update for fee remission changed

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/allocatecase/AllocateTheCaseToCaseWorkerMidEventHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/CaseWorkerService.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/RoleAssignmentService.java

This reverts commit 2f404d2c33a19e467449484ecad3d210a7d2063b.
```
[ ] Yes
[ ] No
```

Revert "add more logging for issue 469 (#847)"

---

src/functionalTest/resources/scenarios/RIA-4235-update-legal-representatives-details-after-noc.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LegalRepresentativeUpdateDetailsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LegalRepresentativeUpdateDetailsHandlerTest.java

RIA-4235 
remove NoC marker after Legal Rep update
```
[ ] Yes
[x] No
```

RIA-4235 remove NoC marker after Legal Rep update

---

src/functionalTest/resources/scenarios/RWA-137-Allocate-a-case-to-me.json
src/functionalTest/resources/scenarios/RWA-318-Allocate-a-case-to-caseworker-confirmation-page.json
src/functionalTest/resources/scenarios/RWA-318-Allocate-a-case-to-caseworker-midevent.json
src/functionalTest/resources/scenarios/RWA-340-Allocate-a-case-to-caseworker-negative-scenario-midevent.json

N/A
disable wa tests
```
[ ] Yes
[ ] No
```

disable wa tests (non prod feature)

---

src/functionalTest/resources/scenarios/RIA-3795-manage-fee-update-of-additional-fee-requested.json
src/functionalTest/resources/scenarios/RIA-3795-manage-fee-update-of-fee-update-not-required.json
src/functionalTest/resources/scenarios/RIA-3795-manage-fee-update-of-refund-approved.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ManageFeeUpdateConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdateHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdateMidEvent.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdatePreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ManageFeeUpdateConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdateHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdateMidEventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdatePreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordRemissionDecisionMidEventTest.java

RIA-3795: Manage fee update status flow refundApproved,additionalFee,feeUpdateNotRequired options
https://tools.hmcts.net/jira/browse/RIA-3795
```
[ ] Yes
[ x] No
```

RIA-3795: Manage fee update status flow refundApproved,additionalFee,feeUpdateNotRequired options

---

src/functionalTest/resources/scenarios/RIA-3813-manage-fee-update-of-refund-approved-not-required.json
src/functionalTest/resources/scenarios/RIA-3813-manage-fee-update-of-refund-instructed.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ManageFeeUpdateConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdateHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdateMidEvent.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdatePreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ManageFeeUpdateConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdateMidEventTest.java

RIA-3813:Manage fee update refund instructed
https://tools.hmcts.net/jira/browse/RIA-3813
```
[ ] Yes
[x ] No
```

RIA-3813:Manage fee update refund instructed

---

src/functionalTest/resources/scenarios/RIA-3814-manage-fee-update-post-refund-instructed-additional-fee.json
src/functionalTest/resources/scenarios/RIA-3814-manage-fee-update-post-refund-instructed-not-required.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdateHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdateMidEvent.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdateMidEventTest.java

RIA-3814:Manage fee update post refund instructed steps
https://tools.hmcts.net/jira/browse/RIA-3814
```
[ ] Yes
[x ] No
```

RIA-3814:Manage fee update post refund instructed steps

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSavedConfirmation.java

[RIA-4081](https://tools.hmcts.net/jira/browse/RIA-4081)
Reversed the share-a-case calls, and more logging
```
[ ] Yes
[x] No
```

RIA-4081 Reverse the order of share-a-case calls and logging

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSavedConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeReferenceFormatter.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LegalRepOrganisationFormatter.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSavedConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeReferenceFormatterTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LegalRepOrganisationFormatterTest.java

https://tools.hmcts.net/jira/browse/RIA-4000
Fixed start appeal flow for aip journey
```
[ ] Yes
[X] No
```

RIA-4000: Fixed start appeal flow for aip journey

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealSubmitHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealSubmitHandlerTest.java

Added additional logging to track ooc applications on appeal submit
```
[ ] Yes
[X] No
```

Added additional logging to track ooc applications on appeal submit

---

README.md
src/functionalTest/resources/scenarios/RWA-492-Allocate-a-case-reset-options-scenario-about-to-start.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/allocatecase/AllocateTheCaseResetOptionsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/allocatecase/AllocateTheCaseToCaseWorkerHandler.java
src/main/resources/application-wa-local.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/allocatecase/AllocateTheCaseResetOptionsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/allocatecase/AllocateTheCaseToCaseWorkerHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/allocatecase/AllocateTheCaseToMeHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/allocatecase/DisableAllocateTheCaseToCaseWorkerHandlerTest.java

https://tools.hmcts.net/jira/browse/RWA-492

rwa-492 bug fix

---

src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdateMidEventTest.java

[RIA-3882](https://tools.hmcts.net/jira/browse/RIA-3882)
Admin officer journey chooses fee update not required after additional fee required
```
[ ] Yes
[x] No
```

RIA-3882 Admin officer journey chooses fee update not required after additional fee required

---

src/functionalTest/resources/scenarios/RIA-3880-manage-fee-update-after-fee-update-not-required.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdatePreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdatePreparerTest.java

RIA-3880:Manage fee update not allowed post fee update not required
https://tools.hmcts.net/jira/browse/RIA-3880
```
[ ] Yes
[ x] No
```

RIA-3880:Manage fee update not allowed post fee update not required

---

src/functionalTest/resources/scenarios/RIA-3731-remove-representation.json
src/functionalTest/resources/scenarios/RIA-3951-remove-legal-representative-ao.json
src/functionalTest/resources/scenarios/RIA-3951-remove-legal-representative-tcw.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RemoveRepresentationPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RemoveRepresentationPreparerTest.java

[RIA-4292](https://tools.hmcts.net/jira/browse/RIA-4292)
See Jira
```
[ ] Yes
[x] No
```

Updated NoC error messages for remove representation

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryAppender.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryAppenderTest.java

[RIA-4114](https://tools.hmcts.net/jira/browse/RIA-4114)
```
[ ] Yes
[x] No
```

RIA-4114 TCW can't update an appeal detail using edit appeal

---

build.gradle
charts/ia-case-api/Chart.yaml

N/A
fix cve and upgrade charts
```
[ ] Yes
[x] No
```

fix cve and upgrade charts

---

src/integrationTest/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/allocatethecase/CaseWorkerRefDataMock.java
src/integrationTest/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/allocatethecase/CaseWorkerServiceTest.java
src/integrationTest/resources/case-worker-ref-data-response.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/allocatecase/AllocateTheCaseToCaseWorkerMidEventHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/CaseWorkerService.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/model/refdata/CaseWorkerProfile.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/allocatecase/AllocateTheCaseToCaseWorkerMidEventHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/CaseWorkerServiceTest.java

N/A
fix potential performance issue
```
[ ] Yes
[x] No
```

fix potential performance issue

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/DbAppealReferenceNumberGenerator.java

[RIA-4252](https://tools.hmcts.net/jira/browse/RIA-4252)
```
[ ] Yes
[x] No
```

RIA-4252 Fix duplicate submitAppeal creation

---

src/functionalTest/resources/scenarios/RIA-3389-home-office-reference-formatter-letter-plus-seven-digits.json
src/functionalTest/resources/scenarios/RIA-3389-home-office-reference-formatter-non-standard.json
src/functionalTest/resources/scenarios/RIA-3389-home-office-reference-formatter-without-slash.json
src/functionalTest/resources/scenarios/RIA-3389-home-office-reference-formatter.json
src/functionalTest/resources/scenarios/RIA-3680-home-office-reference-formatter.json
src/functionalTest/resources/scenarios/RIA-581-appeal-reference-number-generation.json

Just fixing regEp
```
[ ] Yes
[x] No
```

Fix regEx of appeal refrence

---

src/functionalTest/resources/scenarios/RIA-4042-record-out-of-time-decision.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTag.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/OutOfTimeDecisionDetails.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/OutOfTimeDecisionType.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RecordOutOfTimeDecisionConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeDecisionDateChecker.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordOutOfTimeDecisionHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordOutOfTimeDecisionPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestRespondentEvidencePreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/OutOfTimeDecisionDetailsAppender.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTagTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/OutOfTimeDecisionDetailsTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/OutOfTimeDecisionTypeTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RecordOutOfTimeDecisionConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeDecisionDateCheckerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordOutOfTimeDecisionHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordOutOfTimeDecisionPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestRespondentEvidencePreparerTest.java

[RIA-4042](https://tools.hmcts.net/jira/browse/RIA-4042)
Case-officer records appeal out of time decision
```
[ ] Yes
[x] No
```

RIA-4042 Case officer record out of time decision

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

[RIA-4037](https://tools.hmcts.net/jira/browse/RIA-4081)
Notification of record out of time decision
```
[ ] Yes
[x] No
```

RIA-4037 Notification of record out of time decision

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/BaseLocation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AddBaseLocationFromHearingCentreForOldCasesFixHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/BaseLocationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AddBaseLocationFromHearingCentreForOldCasesFixHandlerTest.java

[RIA-4315](https://tools.hmcts.net/jira/browse/RIA-4315)
Glasgow change and Arnhem House location
```
[ ] Yes
[x] No
```

RIA-4315 additional locations

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewDraftHearingRequirementsPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewUpdateHearingRequirementsPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewDraftHearingRequirementsPreparerTest.java

[RIA-4113](https://tools.hmcts.net/jira/browse/RIA-4113)
See Jira
```
[ ] Yes
[x] No
```

RIA-4113 review update hearing requirements and adjustments

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LegalRepresentativeDetailsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LegalRepresentativeDetailsHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-4287
separated legal rep details for AIP appeals
```
[ ] Yes
[X] No
```

RIA-4287: separated legal rep details for AIP appeals

---

Jenkinsfile_nightly
security.sh

N/A
fix security test script and enable functional tests in nightly build
```
[ ] Yes
[x] No
```

fix security test script and enable functional tests in nightly build

---

Jenkinsfile_nightly

N/A
fix nightly build test user credentials
```
[ ] Yes
[x] No
```

fix nightly build test user credentials

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/CheckValues.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealGroundsForDisplayFormatter.java

N/A
fix grounds optional tick
```
[ ] Yes
[x] No
```

fix grounds optional tick

---

src/functionalTest/resources/scenarios/RIA-4473-decision-without-hearing-changes.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/HearingCentre.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DecisionWithoutHearingHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/HearingCentreTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DecisionWithoutHearingHandlerTest.java

[RIA-4473](https://tools.hmcts.net/jira/browse/RIA-4473)
```
[ ] Yes
[x] No
```

RIA-4473 Decision without hearing route

---

Jenkinsfile_nightly

N/A
fix nightly build env variable
```
[ ] Yes
[x] No
```

fix nightly build env variable

---

src/functionalTest/resources/scenarios/RIA-1358-RIA-4293-update-legal-representatives-details.json
src/functionalTest/resources/scenarios/RIA-4234-RIA-4293-previous-representative-details-after-noc.json
src/functionalTest/resources/scenarios/RIA-4234-RIA-4293-previous-representative-details-no-noc.json
src/functionalTest/resources/scenarios/RIA-4234-previous-representative-details-after-noc.json
src/functionalTest/resources/scenarios/RIA-4234-previous-representative-details-no-noc.json
src/functionalTest/resources/scenarios/RIA-4235-RIA-4293-update-legal-representatives-details-after-noc.json
src/functionalTest/resources/scenarios/RIA-4293-cleared-fields-update-representative-details.json
src/functionalTest/resources/scenarios/RIA-4293-company-name-ref-data-start-appeal.json
src/functionalTest/resources/scenarios/RIA-4293-persisted-fields-update-representative-details.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/PreviousRepresentation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LegalRepresentativeUpdateDetailsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LegalRepresentativeUpdateDetailsPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/CompanyNameProvider.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/PreviousRepresentationAppender.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/CcdCaseAssignment.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/PreviousRepresentationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LegalRepresentativeUpdateDetailsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LegalRepresentativeUpdateDetailsPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/CompanyNameProviderTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/PreviousRepresentationAppenderTest.java

[RIA-4293](https://tools.hmcts.net/jira/browse/RIA-4293)
See Jira
```
[ ] Yes
[x] No
```

Ria 4293 noc prompt to update details

---

src/functionalTest/resources/scenarios/RIA-4336-appellant-make-an-application.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/UserRole.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/MakeAnApplicationAppender.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/MakeAnApplicationTypesProvider.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/UserRoleTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/MakeAnApplicationAppenderTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/MakeAnApplicationTypesProviderTest.java

https://tools.hmcts.net/jira/browse/RIA-4336
Integrating AiP flow and citizen role so we can make an application
```
[ ] Yes
[ x ] No
```

RIA-4336: Integrate aip flow and citizen role for make an application event

---

src/main/resources/application-local.yaml
src/main/resources/application-wa-local.yaml

https://tools.hmcts.net/jira/browse/RWA-640
fix the wa dev env

https://tools.hmcts.net/jira/browse/RWA-640

---

src/functionalTest/resources/scenarios/RWA-584-add-case-management-category-start-appeal-appellant.json

RIA-4456
temporary disable AIP test - to fix in RIA-4456
```
[ ] Yes
[x] No
```

temporary disable AIP test - to fix in RIA-4456

---

build.gradle

N/A
remove maven repo url
```
[ ] Yes
[x] No
```

remove maven repo url

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CaseManagementCategoryAppender.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/FeesHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CaseManagementCategoryAppenderTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeesHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-4456
Fixed aip appeal issue when Fee and Pay is enabled
```
[ ] Yes
[X] No
```

RIA-4456: Fixed aip appeal issue when Fee and Pay is enabled

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CaseManagementCategoryAppender.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CaseManagementCategoryAppenderTest.java

https://tools.hmcts.net/jira/browse/RWA-662

revert changes and leave only the few changes I need

---

src/functionalTest/resources/scenarios/RIA-4272-direction-publish-on-send-home-office-evidence-direction.json
src/functionalTest/resources/scenarios/RIA-892-RIA-2694-request-respondent-evidence-start.json
src/functionalTest/resources/scenarios/RIA-892-request-respondent-evidence-confirmation.json
src/functionalTest/resources/scenarios/RIA-892-request-respondent-evidence-submit.json
src/functionalTest/resources/scenarios/RIA-893-RIA-1897-send-home-office-evidence-direction.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RequestHomeOfficeDataConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AdvancedFinalBundlingStitchingCallbackHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AipEditAppealPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseNotificationsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseValidateHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseValidatePreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeRequestHomeOfficeDataPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestRespondentEvidencePreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/HomeOfficeApi.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/HomeOfficeApiService.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RequestHomeOfficeDataConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AdvancedFinalBundlingStitchingCallbackHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AipEditAppealPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseNotificationsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseValidateHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseValidatePreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeRequestHomeOfficeDataPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestRespondentEvidencePreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/HomeOfficeApiServiceTest.java

[RIA-4557](https://tools.hmcts.net/jira/browse/RIA-4557)
Request HomeOffice data of the matching appellant details
```
[ ] Yes
[x] No
```

RIA-4557 Request HomeOffice data of the matching appellant details

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EditAppealAfterSubmitHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeRequestHomeOfficeDataPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EditAppealAfterSubmitHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeRequestHomeOfficeDataPreparerTest.java

[RIA-4556](https://tools.hmcts.net/jira/browse/RIA-4556)
Request Home Office data can retried any number of times
```
[ ] Yes
[x] No
```

RIA-4556 Request Home Office data event retry

---

charts/ia-case-api/Chart.yaml
charts/ia-case-api/values.yaml
config/owasp/suppressions.xml

N/A
add ingress host + suppress CVE
```
[ ] Yes
[x] No
```

add ingress host + suppress CVE

---

src/functionalTest/resources/scenarios/RIA-4351-error-upper-tribunal-bundling-appellant-reheard-rule-32.json
src/functionalTest/resources/scenarios/RIA-4351-error-upper-tribunal-bundling-appellant-reheard-rule-35.json
src/functionalTest/resources/scenarios/RIA-4351-error-upper-tribunal-bundling-appellant-remade-rule-32.json
src/functionalTest/resources/scenarios/RIA-4351-error-upper-tribunal-bundling-respondent-reheard-rule-32.json
src/functionalTest/resources/scenarios/RIA-4351-error-upper-tribunal-bundling-respondent-reheard-rule-35.json
src/functionalTest/resources/scenarios/RIA-4351-error-upper-tribunal-bundling-respondent-remade-rule-32.json
src/functionalTest/resources/scenarios/RIA-4351-generate-upper-tribunal-bundle-confirmation.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTag.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/GenerateUpperTribunalBundleConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AdvancedFinalBundlingStateHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AdvancedFinalBundlingStitchingCallbackHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpperTribunalBundlePreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpperTribunalStitchingCallbackHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/FtpaDisplayService.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTagTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/GenerateUpperTribunalBundleConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AdvancedFinalBundlingStitchingCallbackHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpperTribunalBundlePreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpperTribunalStitchingCallbackHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/FtpaDisplayServiceTest.java

[RIA-4351](https://tools.hmcts.net/jira/browse/RIA-4351)
See Jira
```
[ ] Yes
[x] No
```

RIA-4351 generate upper tribunal bundle

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListCasePreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/utils/StaffLocation.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListCasePreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/utils/StaffLocationTest.java

[RIA-3734](https://tools.hmcts.net/jira/browse/RIA-3734)
```
[ ] Yes
[x] No
```

RIA-3734 select GlasgowTribunals for Glasgow hearing centre

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppellantNameForDisplayFormatter.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CaseManagementCategoryAppender.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppellantNameForDisplayFormatterTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CaseManagementCategoryAppenderTest.java

[RWA-707](https://tools.hmcts.net/jira/browse/RWA-707)
see ticket
```
[ ] Yes
[ X] No
```

Remove the adminCaseUpdate event from the ia ccd def

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AdvancedFinalBundlingStitchingCallbackHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeAppealTypeChecker.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseNotificationsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseValidateHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseValidatePreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeRequestHomeOfficeDataPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestRespondentEvidencePreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AdvancedFinalBundlingStitchingCallbackHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeAppealTypeCheckerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseNotificationsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseValidateHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseValidatePreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeRequestHomeOfficeDataPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestRespondentEvidencePreparerTest.java

[RIA-4815](https://tools.hmcts.net/jira/browse/RIA-4815)
Enabled HomeOffice API requests for PA and RP appeal types only
```
[ ] Yes
[x] No
```

RIA-4815 Enabled HomeOffice API for PA and RP appeal types

---

src/functionalTest/resources/scenarios/RIA-4471-RIA-4774-RIA-4911-edit-payment-method-to-pay-by-card-eu-appeal.json
src/functionalTest/resources/scenarios/RIA-4471-RIA-4774-RIA-4911-edit-payment-method-to-pay-by-card-hu-appeal.json
src/functionalTest/resources/scenarios/RIA-4471-RIA-4774-RIA-4911-edit-payment-method-to-pay-by-card-pa-appeal.json
src/functionalTest/resources/scenarios/RIA-4471-RIA-4774-RIA-4911-error-on-edit-payment-method-payment-paid.json
src/functionalTest/resources/scenarios/RIA-4471-RIA-4774-RIA-4911-error-on-edit-payment-method-payment-pending.json
src/functionalTest/resources/scenarios/RIA-4911-error-on-edit-payment-method-payment-failed-inflight-appeals-without-remissions.json
src/functionalTest/resources/scenarios/RIA-4911-error-on-edit-payment-method-payment-pending-remission-approved.json
src/functionalTest/resources/scenarios/RIA-4911-error-on-edit-payment-method-payment-pending-remission-part-approved.json
src/functionalTest/resources/scenarios/RIA-4911-no-error-on-edit-payment-method-payment-pending-inflight-appeals-without-remissions.json
src/functionalTest/resources/scenarios/RIA-4911-no-error-on-edit-payment-method-payment-pending-remission-rejected.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/EditPaymentMethodPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/FeesAndStatusCheckPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/MarkPaymentPaidPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/PaymentStateHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/RollbackPaymentPreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/EditPaymentMethodPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/FeesAndStatusCheckPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/MarkPaymentPaidPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/PaymentStateHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/RollbackPaymentPreparerTest.java

git push --set-upstream origin RIA-4911-RIA-4774-integration
updated validation logic for changing the payment method - integrated with RIA-4774 conflicts
```
[ ] Yes
[X] No
```

Ria 4911 ria 4774 integration

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/FeesAndStatusCheckPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/FeesHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/FeesHandlerTest.java

[RIA-4801](https://tools.hmcts.net/jira/browse/RIA-4801)
Fee lookup for AIP journey
```
[ ] Yes
[x] No
```

RIA-4801 AIP appeal fee lookup

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MarkEvidenceAsReviewedActionAvailableUpdater.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MarkEvidenceAsReviewedActionAvailableUpdaterTest.java

https://tools.hmcts.net/jira/browse/RIA-4747
RIA-4747 Review additional evidence event
```
[ ] Yes
[X] No
```

RIA-4747_link

---

src/functionalTest/resources/scenarios/RIA-2176-build-case-legal-rep-list-uploaded-files-about_to_start.json
src/functionalTest/resources/scenarios/RIA-2558-RIA-2644-RIA-2739-change-hearing-centre.json
src/functionalTest/resources/scenarios/RIA-2957-RIA-2959-RIA-3712-adjourn-without-a-date.json
src/functionalTest/resources/scenarios/RIA-365-notify-case-officers-of-submitted-appeal.json
src/functionalTest/resources/scenarios/RIA-3683-list-case-submit-flag-off.json
src/functionalTest/resources/scenarios/RIA-3683-list-case-submit-flag-on.json
src/functionalTest/resources/scenarios/RIA-3683-list-reheard-case-submit.json
src/functionalTest/resources/scenarios/RIA-3734-case-listing-belfast-hearing-venue.json
src/functionalTest/resources/scenarios/RIA-480-RIA-600-build-case-append-feature-disabled.json
src/functionalTest/resources/scenarios/RIA-480-RIA-600-build-case-append-feature-enabled.json
src/functionalTest/resources/scenarios/RIA-480-RIA-600-build-case-confirmation-feature-disabled.json
src/functionalTest/resources/scenarios/RIA-480-RIA-600-build-case-confirmation-feature-enabled.json
src/functionalTest/resources/scenarios/RIA-480-RIA-600-build-case-initial-feature-disabled.json
src/functionalTest/resources/scenarios/RIA-480-RIA-600-build-case-initial-feature-enabled.json
src/functionalTest/resources/scenarios/RIA-481-appeal-skeleton-case-stitching-save-and-continue-disabled.json
src/functionalTest/resources/scenarios/RIA-517-case-submitted-confirmation-feature-disabled.json
src/functionalTest/resources/scenarios/RIA-910-RIA-911-RIA-912-case-building-ready-for-submission.json

[RIA-4748](https://tools.hmcts.net/jira/browse/RIA-4748)
```
[ ] Yes
[x] No
```

RIA-4748 Place all notifications to caseworkers behind a feature flag

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java

[RIA-4797](https://tools.hmcts.net/jira/browse/RIA-4797)
Update payment status via payment batch job
```
[ ] Yes
[x] No
```

RIA-4797 Update payment status as a system user

---

src/functionalTest/resources/scenarios/RIA-4973-set-case-name.json
src/functionalTest/resources/scenarios/RIA-4973-set-incorrect-case-name.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/AsylumFieldCaseNameFixer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/config/AsylumCaseDataConfiguration.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/AsylumFieldCaseNameFixerTest.java

[RIA-4973](https://tools.hmcts.net/jira/browse/RIA-4973)
See Jira
```
[ ] Yes
[x] No
```

RIA-4973 appellant name for caseName field

---

src/main/resources/application.yaml

RIA-4863
allow draftHearingRequirements event for citizen role

RIA-4863: allow draftHearingRequirements event for citizen role

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTag.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTagTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandlerTest.java

RIA-4925 Bundling: Appeal reasons document template set up

---

src/functionalTest/resources/scenarios/RIA-3144-SetupAppellantDocuments.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTag.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DocumentTagTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/GenerateDocumentHandlerTest.java

RIA-4928 Bundling: Clarifying questions document template set up

---

src/functionalTest/resources/scenarios/RIA-3144-SetupAppellantDocuments.json
src/functionalTest/resources/scenarios/RIA-4722-complete-clarifying-questions.json
src/functionalTest/resources/scenarios/RIA-4722-direction-request-clarifying-questions.json
src/functionalTest/resources/scenarios/RIA-4722-reinstate-preclarifying-state.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CompleteClarifyingQuestionsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReinstateCaseStateToPreClarifyingStateHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendDirectionWithQuestionsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CompleteClarifyingQuestionsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReinstateCaseStateToPreClarifyingStateHandlerTest.java

:
###https://tools.hmcts.net/jira/browse/RIA-4722 ###
```
[ ] Yes
[x ] No
```

RIA-4722 Process to enable correct state to be set when clarifying questions is completed

---

charts/ia-case-api/Chart.yaml

https://tools.hmcts.net/jira/browse/RIA-5503
```
[ ] Yes
[x] No
```

RIA-5503: Upgrade base helm charts to latest

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/Subscriber.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/SubscriberType.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryEditAppealAipHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryEditAppealHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/SubscriberTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/SubscriberTypeTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryEditAppealAipHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryHandlerTest.java

[RIA-4965](https://tools.hmcts.net/jira/browse/RIA-4965)
Feature branch for release
```
[ ] Yes
[x] No
```

RIA-4965 AIP OOC

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryEditAppealAipHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeDecisionDateChecker.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeReferenceNumberTruncator.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryEditAppealAipHandlerTest.java

Reverts hmcts/ia-case-api#1031

Revert "RIA-4965 new case field for aip journey"

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MarkEvidenceAsReviewedActionAvailableUpdater.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MarkEvidenceAsReviewedActionAvailableUpdaterTest.java

https://tools.hmcts.net/jira/browse/RIA-5142
```
[ ] Yes
[x] No
```

RIA-5142: Update handler for 'markEvidenceAsReviewed' event

---

build.gradle
config/owasp/suppressions.xml

Bumped postgresql to version 42.3.3
```
[ ] Yes
[x] No
```

Ria 5679 quick fix

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSavedConfirmation.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSavedConfirmationTest.java

Payment options changes for RIA-5719

---

config/owasp/suppressions.xml
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/RIA-5807
```
[ ] Yes
[x] No
```

RIA-5807 Enable Addendum Evidence Feature for AIP

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSavedConfirmation.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSavedConfirmationTest.java

Changed to fix message in case of remission

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/FeesAndStatusCheckPreparer.java

Temp suppress vulns ria 5721

---

charts/ia-case-api/Chart.yaml
charts/ia-case-api/values.preview.template.yaml
charts/ia-case-api/values.yaml
config/owasp/suppressions.xml

Charts java update aip

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

[RIA-5777](https://tools.hmcts.net/jira/browse/RIA-5777)
- 'endAppealAutomatically' added to SendNotificationHandler
```
[ ] Yes
[x] No
```

RIA-5777 Add END_APPEAL_AUTOMATICALLY event to SendNotificationHandler

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-5725
Adding UPDATE_PAYMENT_STATUS event into notification handler to allow LR and HO notifications to get sent out
```
[ ] Yes
[X] No
```

RIA-5725 successful payment LR HO notification

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSavedConfirmation.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSavedConfirmationTest.java

RIA-6038: Changed content in appeal saved confirmation

---

config/owasp/suppressions.xml
src/contractTest/java/uk/gov/hmcts/reform/iacaseapi/consumer/ccd/CcdSupplementaryConsumerTest.java
src/contractTest/java/uk/gov/hmcts/reform/iacaseapi/consumer/ccd/CcdSupplementaryProviderBaseTest.java
src/contractTest/resources/application.properties
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSubmittedConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/payment/PayAndSubmitConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/CcdSupplementaryUpdater.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSubmittedConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/PayAndSubmitConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/CcdSupplementaryUpdaterTest.java

https://tools.hmcts.net/jira/browse/RIA-6096
https://tools.hmcts.net/jira/browse/RIA-6099
Added supplementary data update API call for Appeal for LR
AIP journey share the same submit events.
```
[ ] Yes
[ x ] No
```

Ria 6096 gs supplementary data lr

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/PaymentStateHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/PaymentStateHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-6141
- changed paymentStateHandler to allow PA pay now to go to pendingPayment state
- added new unit tests
```
[ ] Yes
[X] No
```

RIA-6141 - State set to pendingPayment for PA pay now cases

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/AsylumFieldCaseNameFixer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/AsylumFieldCaseNameFixerTest.java

https://tools.hmcts.net/jira/browse/RIA-6093
Populating case name for global search
```
[ ] Yes
[x] No
```

RIA-6093 - Populating case name for global search

---

build.gradle
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AppealType.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AppealTypeTest.java

- [RIA-5587](https://tools.hmcts.net/jira/browse/RIA-5587)
- [RIA-5895](https://tools.hmcts.net/jira/browse/RIA-5895)
- [RIA-5586](https://tools.hmcts.net/jira/browse/RIA-5586)
- [RIA-6163](https://tools.hmcts.net/jira/browse/RIA-6163)
- Added EU ("EU Settlement Scheme" to AppealType enum)
```
[ ] Yes
[x] No
```

RIA-5587 Add EU appealType

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeAppealTypeChecker.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ManageFeeUpdatePreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordRemissionDecisionPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestFeeRemissionPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/EditPaymentMethodPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/FeesAndStatusCheckPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/FeesHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/MarkPaymentPaidPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/AsylumFieldCaseCategoryFixer.java

JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/RIA-6177
Change description
Update the DMN file and Add EUSS appeal type to the list .
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[ x] No

Added EUSS to case data

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSubmittedConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/GenerateServiceRequestMakeAPaymentConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RecordRemissionDecisionConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HasServiceRequestAlreadyValueHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/AsylumCasePostFeePaymentService.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/PostFeePayment.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSubmittedConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/GenerateServiceRequestMakeAPaymentConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RecordRemissionDecisionConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HasServiceRequestAlreadyValueHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-6161
- Added classes for PostSubmit callbacks to ia-case-payment-api
```
[ ] Yes
[ ] No
```

RIA-6161 PostSubmit classes, and callback to payment-api

---

src/functionalTest/java/uk/gov/hmcts/reform/iacaseapi/CcdScenarioRunnerTest.java
src/functionalTest/resources/scenarios/RIA-6049-pipActivated-event-adds-subscription-data.json
src/functionalTest/resources/scenarios/RIA-6050-transform-LR-case-data-to-AIP-case-data.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/PinInPostActivated.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/PinInPostActivatedTest.java

https://tools.hmcts.net/jira/browse/RIA-6050
```
[ ] Yes
[x] No
```

RIA-6050 Appellant views Skeleton Argument/Evidence

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/CaseDetails.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/payment/PayAndSubmitConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AsylumSupplementaryDataFixingHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordApplicationHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/AsylumFieldCaseNameFixer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/PreSubmitCallbackDispatcher.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/CcdSupplementaryUpdater.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/CaseDetailsTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AsylumSupplementaryDataFixingHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestCaseBuildingHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/AsylumFieldCaseNameFixerTest.java

https://tools.hmcts.net/jira/browse/RIA-6281
Adding handler & updating models to add casenameinternalhmcts & supplementary data if non exists for old cases.
```
[ ] Yes
[x] No
```

Ria 6281 wa3 case data fix

---

src/functionalTest/resources/scenarios/RIA-6335-change-state-to-caseUnderReview.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AipToLegalRepJourneyHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AipToLegalRepJourneyHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-6335
AIP to LR Noc, when case state is reasonsForAppealSubmitted change case state to caseUnderReview
```
[ ] Yes
[X] No
```

RIA-6335 Something went wrong page Page Displayed for LR

---

src/functionalTest/resources/scenarios/RIA-6335-change-state-to-caseUnderReview.json
src/functionalTest/resources/scenarios/RIA-6336-change-state-to-caseBuilding.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AipToLegalRepJourneyHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AipToLegalRepJourneyHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-6336
AIP to LR Noc, when case state is awaitingReasonsForAppeal change case state to caseBuilding
```
[ ] Yes
[X] No
```

RIA-6336 Case not appearing in case list when LR completes NOC

---

src/functionalTest/resources/scenarios/RIA-6337-noc-complete-clarifying-questions.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AipToLegalRepJourneyHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CompleteClarifyingQuestionsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AipToLegalRepJourneyHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CompleteClarifyingQuestionsHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-6337
LR unable to access case due to Awaiting clarifying question answers state:
* Completed clarifying questions with default answer.
* Change current state back to state before clarifying questions were asked.
```
[ ] Yes
[X] No
```

RIA-6337 LR unable to access case due to Awaiting clarifying questions

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/PinInPostActivated.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/PinInPostActivatedTest.java

https://tools.hmcts.net/jira/browse/RIA-6356
When appellant takes over case from legal representative update case state as follows:
caseBuilding -> awaitingReasonsForAppeal 
caseUnderReview -> reasonsForAppealSubmitted
```
[ ] Yes
[X] No
```

RIA-6356 LR to AIP Case states for NOC

---

src/functionalTest/resources/application-functional.yaml
src/functionalTest/resources/scenarios/RIA-6049-pipActivated-event-adds-subscription-data.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/PinInPostActivated.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/PinInPostActivatedTest.java

https://tools.hmcts.net/jira/browse/RIA-6319
```
[ ] Yes
[x] No
```

RIA-6319: Notifications sent when Appellant takes over case

---

src/functionalTest/resources/scenarios/RIA-6335-change-state-to-caseUnderReview.json
src/functionalTest/resources/scenarios/RIA-6337-noc-complete-clarifying-questions.json
src/functionalTest/resources/scenarios/RIA-6388-map-subscription-to-appellant-contact-details-for-aip-to-lr-noc.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AipToLegalRepJourneyHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AipToLegalRepJourneyHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-6388
```
[ ] Yes
[x] No
```

RIA-6388: Appellant Notification when LR comes off record after NOC

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ChangeRepresentationConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AipToLegalRepJourneyHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ChangeRepresentationConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AipToLegalRepJourneyHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-6388
```
[ ] Yes
[x] No
```

Appellant Notification when LR comes off record after NOC

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RemoveRepresentationPreparer.java

Reverts hmcts/ia-case-api#1134

Revert "RIA-6366 - fix to stop incorrect value update for NOC request"

---

config/owasp/suppressions.xml
src/contractTest/java/uk/gov/hmcts/reform/iacaseapi/consumer/ccd/CcdSupplementaryConsumerTest.java
src/contractTest/java/uk/gov/hmcts/reform/iacaseapi/consumer/ccd/CcdSupplementaryProviderBaseTest.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/AsylumFieldCaseNameFixer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/CcdSupplementaryUpdater.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/config/AsylumCaseDataConfiguration.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/AsylumFieldCaseNameFixerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/CcdSupplementaryUpdaterTest.java

Added a feature flag for R3 functionalities.
```
[ ] Yes
[ ] No
```

Ria 6294 WA R3 Feature flag

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DetentionStatus.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DetentionStatusHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DetentionStatusTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DetentionStatusHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-6422
- Added DetentionStatus enums
- Added handler to set this value in backend plus tests
```
[ ] Yes
[X] No
```

Ria 6422 handler detention status

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DetentionStatus.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/DetentionStatusTest.java

https://tools.hmcts.net/jira/browse/RIA-6424
The template for this document needs to be updated to include the new ADA questions.
```
[ ] Yes
[ x] No
```

DetentionStatus Changes

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EndAppealHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EndAppealHandlerTest.java

https://tools.hmcts.net/jira/browse/SNI-2395
code fix for filter paid event in ending automatically event
```
[ ] Yes
[x ] No
```

code fix for filter paid event in ending autmatically event

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/field/BailApplicationStatus.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/BailApplicationNumberHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/BailApplicationNumberHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-6459
Added validation on Bail Application Number
```
[ ] Yes
[X ] No
```

RIA-6459 - Applied validation on bail application number

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordRemissionDecisionStateHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RecordRemissionDecisionStateHandlerTest.java

Ria 6519 allow case progression upon remission approval on EUSS appeal
Ria 6519 allow case progression upon remission approval on EUSS appeal
```
[ ] Yes
[ X] No
```

Ria 6519 allow case progression upon remission approval on EUSS appeal

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ApplicationType.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/MakeAnApplicationTypes.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MakeAnApplicationMidEvent.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/MakeAnApplicationTypesProvider.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/MakeAnApplicationTypesTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/MakeAnApplicationTypesProviderTest.java

[RIA-6501](https://tools.hmcts.net/jira/browse/RIA-6501)
- added new type of Application to be made (`TRANSFER_OUT_OF_ACCELERATED_DETAINED_APPEALS_PROCESS`)
- added variation of `JUDGE_REVIEW` for LRs (`JUDGE_REVIEW_LR`)
- edited logic to populate dynamicList of applications with new value and to change `JUDGE_REVIEW` to `JUDGE_REVIEW_LR` when a LR completes the event
```
[ ] Yes
[x] No
```

RIA-6501 Add new MakeAnApplicationTypes and amend handlers

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DateOfBirthValidationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DateOfBirthValidationHandlerTest.java

- Non-AAA cases could not get past a mid event after the DOB question so making this field optional
```
[ ] Yes
[X] No
```

RIA-6549: Making field optional to support non-AAA cases

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealTypeHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealTypeHandlerTest.java

[RIA-6550](https://tools.hmcts.net/jira/browse/RIA-6550)
- Added condition to skip appeal type mapping in case it's an AIP journey
- Fixed pre-existing code style issues
```
[ ] Yes
[x] No
```

RIA-6550 Skip appeal type handler if AIP

---

src/functionalTest/resources/scenarios/RIA-412-RIA-1571-list-case-confirmation.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ListCaseConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListCasePreparer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ListCaseConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ListCasePreparerTest.java

https://tools.hmcts.net/jira/browse/RIA-6527
```
[ ] Yes
[ ] No
```

RIA-6527: List the case Event - ADA

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ReviewUpdateHearingRequirementsConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryEditAppealHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeDecisionDateChecker.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeReferenceFormatter.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ReviewUpdateHearingRequirementsConfirmationTest.java

https://tools.hmcts.net/jira/browse/RIA-6535
added a confirmation screen that has updated content. 
"All parties will be able to see the agreed adjustments in the hearing and appointment tab." in the body
```
[ ] Yes
[ x] No
```

Added new update hearing adjustments confirmationpage

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HearingTypeHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HearingTypeHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-6518
Updated hearing type handler to handle start appeal journey
```
[ ] Yes
[ x ] No
```

RIA-6518 Updated hearing type handler to handle start appeal journey

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LetterSentOrReceivedHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/LetterSentOrReceivedHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-6482
- adding admin authorisation to editAppealAfterSubmit event
- adding event into the letter sent/received handler
```
[ ] Yes
[X] No
```

Ria-6482 admin edit appeal post submit

---

src/functionalTest/resources/scenarios/RIA-1308-upload-respondent-evidence-amend-homeoffice-generic-submit.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeDecisionDateChecker.java

Updates to fix sonar issue around decision date checker
Updates to fix sonar issue around decision date checker
```
[ ] Yes
[ X] No
```

Updates to fix sonar issue around decision date checker

---

src/functionalTest/resources/scenarios/RIA-6420-submit-accelerated-detained-appeal-out-of-time.json

https://tools.hmcts.net/jira/browse/RIA-6420
Added missing functional tests for ADA out of time
```
[ ] Yes
[X] No
```

RIA-6420 - Added functional tests for ADA out of time.

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/FeesAndStatusCheckPreparer.java

Update to fix edit appeal issue when remission is applicable
Update to fix edit appeal issue when remission is applicable
```
[ ] Yes
[X ] No
```

RIA-6581 Updates to fix edit appeal issue

---

src/main/resources/application.yaml

updates to add "mark appeal as paid" event for caseofficer 
updates to add "mark appeal as paid" event for caseofficer 
```
[ ] Yes
[X ] No
```

updates to add "mark appeal as paid" event for caseofficer

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/BaseLocation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/utils/StaffLocation.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/BaseLocationTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/utils/StaffLocationTest.java

https://tools.hmcts.net/jira/browse/RIA-6495
Fixed Yarlswood mismatched error
```
[ ] Yes
[ x ] No
```

RIA-6495 Yarlswood mismatched error

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ReviewHearingRequirementsConfirmation.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ReviewHearingRequirementsConfirmationTest.java

https://tools.hmcts.net/jira/browse/RIA-6532
```
[ ] Yes
[x] No
```

RIA-6532: Review hearing requirements event - ADA

---

src/functionalTest/resources/scenarios/RIA-6420-submit-accelerated-detained-appeal-out-of-time.json
src/functionalTest/resources/scenarios/RIA-6441-detained-edit-appeal-after-submit-in-time-submit.json
src/functionalTest/resources/templates/minimal-ada-appeal-submitted.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DetentionFacilityEditAppealHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DetentionFacilityEditAppealHandlerTest.java

- If detention facility changes from Prison to irc/other, remove custodial date from case data.
- Added functional test for Post submit Edit appeal for Detained appeal.
```
[ ] Yes
[x] No
```

RIA-6441: Changes for QA for Edit appeal post submit

---

src/functionalTest/resources/scenarios/RIA-6437-add-stateless-age-assessment-submit-appeal-out-of-time.json

[RIA-6427](https://tools.hmcts.net/jira/browse/RIA-6427)
- added extra functional test for submission of AG appeal type when out of time
```
[ ] Yes
[x] No
```

RIA-6427 Add extra functional test for submitting AG appeal out of time

---

src/functionalTest/resources/scenarios/RIA-6437-add-stateless-age-assessment-submit-appeal-out-of-time.json

RIA-6437: Fix functional test - added appeal Type in inputs

---

src/functionalTest/resources/scenarios/RIA-6542-aip-dc-submit-appeal.json
src/functionalTest/resources/scenarios/RIA-6542-aip-ea-submit-appeal.json
src/functionalTest/resources/scenarios/RIA-6542-aip-pa-payLater-submit-appeal.json
src/functionalTest/resources/scenarios/RIA-6542-aip-pa-payNow-submit-appeal.json
src/functionalTest/resources/templates/minimal-aip-appeal-started.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AppealSubmittedConfirmation.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/FeesAndStatusCheckPreparer.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/FeesHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/PaymentStateHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/payment/FeesAndStatusCheckPreparerTest.java

https://tools.hmcts.net/jira/browse/RIA-6542
- Changes necessary for the payment flow in AIP to mirror the one for a LR
```
[ ] Yes
[x] No
```
.
.
.
.
.
.

RIA-6542 AIP new payment flow

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DeriveHearingCentreHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DerivePostcodeHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DeriveHearingCentreHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DerivePostcodeHandlerTest.java

- Enable Hearing Centre lookup  from AA_APPELLANT_ADDRESS for AgeAssessment Appeals.
- Update logic for derivePostCode from AA_APPELLANT_ADDRESS for AA Appeals.
```
[ ] Yes
[x] No
```

RIA-6437: Resolve QA bugs

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/AsylumCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewUpdateHearingRequirementsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendDecisionAndReasonsHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateHearingRequirementsHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/ReviewUpdateHearingRequirementsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendDecisionAndReasonsHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-6567
RIA-6567 - ADA flow Update Hearing Adjustments event added
* Added additional statuses ada hearing requirements events can be called from
```
[ ] Yes
[x] No
```

RIA-6567 - ADA flow Update Hearing Adjustments event added

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestRespondentEvidencePreparer.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestRespondentEvidencePreparerTest.java

https://tools.hmcts.net/jira/browse/RIA-6555
* Set direction due date for Request respondent evidence direction to 3 days for ADA appeal
```
[ ] Yes
[x] No
```

RIA-6555 LR Notification when HO has been directed to submit the bundle

---

src/contractTest/java/uk/gov/hmcts/reform/iacaseapi/consumer/ccd/CcdSupplementaryConsumerTest.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AsylumSupplementaryDataFixingHandler.java
src/main/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/CcdSupplementaryUpdater.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/infrastructure/clients/CcdSupplementaryUpdaterTest.java

[RIA-6516](https://tools.hmcts.net/jira/browse/RIA-6516)
- Same changes from the original ticket, but without the baggage of 5 months of commits (hard to rebase correctly)
```
[ ] Yes
[x] No
```

Copy of changes from RIA-6516 for merging into AIP PAYMENTS

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-6671
* Enable notification for AIP journey on paymentAppeal event
```
[ ] Yes
[x] No
```

RIA-6671 AIP Payment - Successful payment Notification

---

src/functionalTest/resources/scenarios/RIA-6696-ada-require-upfront-case-listing.json
src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AdaCaseBuildingPreventer.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AdaCaseBuildingPreventerTest.java

https://tools.hmcts.net/jira/browse/RIA-6696
RIA-6696 - Require up front listing for ADA cases
```
[ ] Yes
[x] No
```

RIA-6696 - Require up front listing for ADA cases

---

src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DetentionFacilityEditAppealHandler.java
src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/DetentionFacilityEditAppealHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-6591
Cleared fields to remove them from appeal tab if case field info is edited.
HAS_PENDING_BAIL_APPLICATIONS
BAIL_APPLICATION_NUMBER
```
[ ] Yes
[ x] No
```

RIA-6591 appeal tab clearing fields

---

Jenkinsfile_CNP
Jenkinsfile_parameterized
build.gradle
charts/ia-case-api/Chart.yaml

To upgrade java chart version
To upgrade java chart version
```
[ ] Yes
[X ] No
```

To upgrade java chart version

---

charts/ia-case-api/Chart.yaml
config/owasp/suppressions.xml

To revise chart version
To revise chart version
```
[ ] Yes
[X ] No
```

To revise chart version
